// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newAppStarred(db *gorm.DB, opts ...gen.DOOption) appStarred {
	_appStarred := appStarred{}

	_appStarred.appStarredDo.UseDB(db, opts...)
	_appStarred.appStarredDo.UseModel(&model.AppStarred{})

	tableName := _appStarred.appStarredDo.TableName()
	_appStarred.ALL = field.NewAsterisk(tableName)
	_appStarred.ID = field.NewInt64(tableName, "id")
	_appStarred.AppID = field.NewInt64(tableName, "app_id")
	_appStarred.UserID = field.NewInt64(tableName, "user_id")

	_appStarred.fillFieldMap()

	return _appStarred
}

type appStarred struct {
	appStarredDo

	ALL    field.Asterisk
	ID     field.Int64
	AppID  field.Int64
	UserID field.Int64

	fieldMap map[string]field.Expr
}

func (a appStarred) Table(newTableName string) *appStarred {
	a.appStarredDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appStarred) As(alias string) *appStarred {
	a.appStarredDo.DO = *(a.appStarredDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appStarred) updateTableName(table string) *appStarred {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.AppID = field.NewInt64(table, "app_id")
	a.UserID = field.NewInt64(table, "user_id")

	a.fillFieldMap()

	return a
}

func (a *appStarred) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appStarred) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 3)
	a.fieldMap["id"] = a.ID
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["user_id"] = a.UserID
}

func (a appStarred) clone(db *gorm.DB) appStarred {
	a.appStarredDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appStarred) replaceDB(db *gorm.DB) appStarred {
	a.appStarredDo.ReplaceDB(db)
	return a
}

type appStarredDo struct{ gen.DO }

type IAppStarredDo interface {
	gen.SubQuery
	Debug() IAppStarredDo
	WithContext(ctx context.Context) IAppStarredDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppStarredDo
	WriteDB() IAppStarredDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppStarredDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppStarredDo
	Not(conds ...gen.Condition) IAppStarredDo
	Or(conds ...gen.Condition) IAppStarredDo
	Select(conds ...field.Expr) IAppStarredDo
	Where(conds ...gen.Condition) IAppStarredDo
	Order(conds ...field.Expr) IAppStarredDo
	Distinct(cols ...field.Expr) IAppStarredDo
	Omit(cols ...field.Expr) IAppStarredDo
	Join(table schema.Tabler, on ...field.Expr) IAppStarredDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppStarredDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppStarredDo
	Group(cols ...field.Expr) IAppStarredDo
	Having(conds ...gen.Condition) IAppStarredDo
	Limit(limit int) IAppStarredDo
	Offset(offset int) IAppStarredDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppStarredDo
	Unscoped() IAppStarredDo
	Create(values ...*model.AppStarred) error
	CreateInBatches(values []*model.AppStarred, batchSize int) error
	Save(values ...*model.AppStarred) error
	First() (*model.AppStarred, error)
	Take() (*model.AppStarred, error)
	Last() (*model.AppStarred, error)
	Find() ([]*model.AppStarred, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppStarred, err error)
	FindInBatches(result *[]*model.AppStarred, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AppStarred) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppStarredDo
	Assign(attrs ...field.AssignExpr) IAppStarredDo
	Joins(fields ...field.RelationField) IAppStarredDo
	Preload(fields ...field.RelationField) IAppStarredDo
	FirstOrInit() (*model.AppStarred, error)
	FirstOrCreate() (*model.AppStarred, error)
	FindByPage(offset int, limit int) (result []*model.AppStarred, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppStarredDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appStarredDo) Debug() IAppStarredDo {
	return a.withDO(a.DO.Debug())
}

func (a appStarredDo) WithContext(ctx context.Context) IAppStarredDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appStarredDo) ReadDB() IAppStarredDo {
	return a.Clauses(dbresolver.Read)
}

func (a appStarredDo) WriteDB() IAppStarredDo {
	return a.Clauses(dbresolver.Write)
}

func (a appStarredDo) Session(config *gorm.Session) IAppStarredDo {
	return a.withDO(a.DO.Session(config))
}

func (a appStarredDo) Clauses(conds ...clause.Expression) IAppStarredDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appStarredDo) Returning(value interface{}, columns ...string) IAppStarredDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appStarredDo) Not(conds ...gen.Condition) IAppStarredDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appStarredDo) Or(conds ...gen.Condition) IAppStarredDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appStarredDo) Select(conds ...field.Expr) IAppStarredDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appStarredDo) Where(conds ...gen.Condition) IAppStarredDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appStarredDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IAppStarredDo {
	return a.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (a appStarredDo) Order(conds ...field.Expr) IAppStarredDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appStarredDo) Distinct(cols ...field.Expr) IAppStarredDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appStarredDo) Omit(cols ...field.Expr) IAppStarredDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appStarredDo) Join(table schema.Tabler, on ...field.Expr) IAppStarredDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appStarredDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppStarredDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appStarredDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppStarredDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appStarredDo) Group(cols ...field.Expr) IAppStarredDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appStarredDo) Having(conds ...gen.Condition) IAppStarredDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appStarredDo) Limit(limit int) IAppStarredDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appStarredDo) Offset(offset int) IAppStarredDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appStarredDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppStarredDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appStarredDo) Unscoped() IAppStarredDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appStarredDo) Create(values ...*model.AppStarred) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appStarredDo) CreateInBatches(values []*model.AppStarred, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appStarredDo) Save(values ...*model.AppStarred) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appStarredDo) First() (*model.AppStarred, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppStarred), nil
	}
}

func (a appStarredDo) Take() (*model.AppStarred, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppStarred), nil
	}
}

func (a appStarredDo) Last() (*model.AppStarred, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppStarred), nil
	}
}

func (a appStarredDo) Find() ([]*model.AppStarred, error) {
	result, err := a.DO.Find()
	return result.([]*model.AppStarred), err
}

func (a appStarredDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppStarred, err error) {
	buf := make([]*model.AppStarred, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appStarredDo) FindInBatches(result *[]*model.AppStarred, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appStarredDo) Attrs(attrs ...field.AssignExpr) IAppStarredDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appStarredDo) Assign(attrs ...field.AssignExpr) IAppStarredDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appStarredDo) Joins(fields ...field.RelationField) IAppStarredDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appStarredDo) Preload(fields ...field.RelationField) IAppStarredDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appStarredDo) FirstOrInit() (*model.AppStarred, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppStarred), nil
	}
}

func (a appStarredDo) FirstOrCreate() (*model.AppStarred, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppStarred), nil
	}
}

func (a appStarredDo) FindByPage(offset int, limit int) (result []*model.AppStarred, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appStarredDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appStarredDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appStarredDo) Delete(models ...*model.AppStarred) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appStarredDo) withDO(do gen.Dao) *appStarredDo {
	a.DO = *do.(*gen.DO)
	return a
}
