// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newConfigMapTemplate(db *gorm.DB, opts ...gen.DOOption) configMapTemplate {
	_configMapTemplate := configMapTemplate{}

	_configMapTemplate.configMapTemplateDo.UseDB(db, opts...)
	_configMapTemplate.configMapTemplateDo.UseModel(&model.ConfigMapTemplate{})

	tableName := _configMapTemplate.configMapTemplateDo.TableName()
	_configMapTemplate.ALL = field.NewAsterisk(tableName)
	_configMapTemplate.ID = field.NewInt64(tableName, "id")
	_configMapTemplate.Name = field.NewString(tableName, "name")
	_configMapTemplate.Template = field.NewString(tableName, "template")
	_configMapTemplate.ConfigMapID = field.NewInt64(tableName, "config_map_id")
	_configMapTemplate.MetaData = field.NewString(tableName, "meta_data")
	_configMapTemplate.Description = field.NewString(tableName, "description")
	_configMapTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_configMapTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_configMapTemplate.User = field.NewString(tableName, "user")
	_configMapTemplate.Deleted = field.NewBool(tableName, "deleted")

	_configMapTemplate.fillFieldMap()

	return _configMapTemplate
}

type configMapTemplate struct {
	configMapTemplateDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Template    field.String
	ConfigMapID field.Int64
	MetaData    field.String
	Description field.String
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (c configMapTemplate) Table(newTableName string) *configMapTemplate {
	c.configMapTemplateDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c configMapTemplate) As(alias string) *configMapTemplate {
	c.configMapTemplateDo.DO = *(c.configMapTemplateDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *configMapTemplate) updateTableName(table string) *configMapTemplate {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Name = field.NewString(table, "name")
	c.Template = field.NewString(table, "template")
	c.ConfigMapID = field.NewInt64(table, "config_map_id")
	c.MetaData = field.NewString(table, "meta_data")
	c.Description = field.NewString(table, "description")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.User = field.NewString(table, "user")
	c.Deleted = field.NewBool(table, "deleted")

	c.fillFieldMap()

	return c
}

func (c *configMapTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *configMapTemplate) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["template"] = c.Template
	c.fieldMap["config_map_id"] = c.ConfigMapID
	c.fieldMap["meta_data"] = c.MetaData
	c.fieldMap["description"] = c.Description
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["user"] = c.User
	c.fieldMap["deleted"] = c.Deleted
}

func (c configMapTemplate) clone(db *gorm.DB) configMapTemplate {
	c.configMapTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c configMapTemplate) replaceDB(db *gorm.DB) configMapTemplate {
	c.configMapTemplateDo.ReplaceDB(db)
	return c
}

type configMapTemplateDo struct{ gen.DO }

type IConfigMapTemplateDo interface {
	gen.SubQuery
	Debug() IConfigMapTemplateDo
	WithContext(ctx context.Context) IConfigMapTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConfigMapTemplateDo
	WriteDB() IConfigMapTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConfigMapTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConfigMapTemplateDo
	Not(conds ...gen.Condition) IConfigMapTemplateDo
	Or(conds ...gen.Condition) IConfigMapTemplateDo
	Select(conds ...field.Expr) IConfigMapTemplateDo
	Where(conds ...gen.Condition) IConfigMapTemplateDo
	Order(conds ...field.Expr) IConfigMapTemplateDo
	Distinct(cols ...field.Expr) IConfigMapTemplateDo
	Omit(cols ...field.Expr) IConfigMapTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IConfigMapTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConfigMapTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConfigMapTemplateDo
	Group(cols ...field.Expr) IConfigMapTemplateDo
	Having(conds ...gen.Condition) IConfigMapTemplateDo
	Limit(limit int) IConfigMapTemplateDo
	Offset(offset int) IConfigMapTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConfigMapTemplateDo
	Unscoped() IConfigMapTemplateDo
	Create(values ...*model.ConfigMapTemplate) error
	CreateInBatches(values []*model.ConfigMapTemplate, batchSize int) error
	Save(values ...*model.ConfigMapTemplate) error
	First() (*model.ConfigMapTemplate, error)
	Take() (*model.ConfigMapTemplate, error)
	Last() (*model.ConfigMapTemplate, error)
	Find() ([]*model.ConfigMapTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConfigMapTemplate, err error)
	FindInBatches(result *[]*model.ConfigMapTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ConfigMapTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConfigMapTemplateDo
	Assign(attrs ...field.AssignExpr) IConfigMapTemplateDo
	Joins(fields ...field.RelationField) IConfigMapTemplateDo
	Preload(fields ...field.RelationField) IConfigMapTemplateDo
	FirstOrInit() (*model.ConfigMapTemplate, error)
	FirstOrCreate() (*model.ConfigMapTemplate, error)
	FindByPage(offset int, limit int) (result []*model.ConfigMapTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConfigMapTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c configMapTemplateDo) Debug() IConfigMapTemplateDo {
	return c.withDO(c.DO.Debug())
}

func (c configMapTemplateDo) WithContext(ctx context.Context) IConfigMapTemplateDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c configMapTemplateDo) ReadDB() IConfigMapTemplateDo {
	return c.Clauses(dbresolver.Read)
}

func (c configMapTemplateDo) WriteDB() IConfigMapTemplateDo {
	return c.Clauses(dbresolver.Write)
}

func (c configMapTemplateDo) Session(config *gorm.Session) IConfigMapTemplateDo {
	return c.withDO(c.DO.Session(config))
}

func (c configMapTemplateDo) Clauses(conds ...clause.Expression) IConfigMapTemplateDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c configMapTemplateDo) Returning(value interface{}, columns ...string) IConfigMapTemplateDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c configMapTemplateDo) Not(conds ...gen.Condition) IConfigMapTemplateDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c configMapTemplateDo) Or(conds ...gen.Condition) IConfigMapTemplateDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c configMapTemplateDo) Select(conds ...field.Expr) IConfigMapTemplateDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c configMapTemplateDo) Where(conds ...gen.Condition) IConfigMapTemplateDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c configMapTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IConfigMapTemplateDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c configMapTemplateDo) Order(conds ...field.Expr) IConfigMapTemplateDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c configMapTemplateDo) Distinct(cols ...field.Expr) IConfigMapTemplateDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c configMapTemplateDo) Omit(cols ...field.Expr) IConfigMapTemplateDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c configMapTemplateDo) Join(table schema.Tabler, on ...field.Expr) IConfigMapTemplateDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c configMapTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConfigMapTemplateDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c configMapTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IConfigMapTemplateDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c configMapTemplateDo) Group(cols ...field.Expr) IConfigMapTemplateDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c configMapTemplateDo) Having(conds ...gen.Condition) IConfigMapTemplateDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c configMapTemplateDo) Limit(limit int) IConfigMapTemplateDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c configMapTemplateDo) Offset(offset int) IConfigMapTemplateDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c configMapTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConfigMapTemplateDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c configMapTemplateDo) Unscoped() IConfigMapTemplateDo {
	return c.withDO(c.DO.Unscoped())
}

func (c configMapTemplateDo) Create(values ...*model.ConfigMapTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c configMapTemplateDo) CreateInBatches(values []*model.ConfigMapTemplate, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c configMapTemplateDo) Save(values ...*model.ConfigMapTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c configMapTemplateDo) First() (*model.ConfigMapTemplate, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigMapTemplate), nil
	}
}

func (c configMapTemplateDo) Take() (*model.ConfigMapTemplate, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigMapTemplate), nil
	}
}

func (c configMapTemplateDo) Last() (*model.ConfigMapTemplate, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigMapTemplate), nil
	}
}

func (c configMapTemplateDo) Find() ([]*model.ConfigMapTemplate, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConfigMapTemplate), err
}

func (c configMapTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConfigMapTemplate, err error) {
	buf := make([]*model.ConfigMapTemplate, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c configMapTemplateDo) FindInBatches(result *[]*model.ConfigMapTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c configMapTemplateDo) Attrs(attrs ...field.AssignExpr) IConfigMapTemplateDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c configMapTemplateDo) Assign(attrs ...field.AssignExpr) IConfigMapTemplateDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c configMapTemplateDo) Joins(fields ...field.RelationField) IConfigMapTemplateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c configMapTemplateDo) Preload(fields ...field.RelationField) IConfigMapTemplateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c configMapTemplateDo) FirstOrInit() (*model.ConfigMapTemplate, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigMapTemplate), nil
	}
}

func (c configMapTemplateDo) FirstOrCreate() (*model.ConfigMapTemplate, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigMapTemplate), nil
	}
}

func (c configMapTemplateDo) FindByPage(offset int, limit int) (result []*model.ConfigMapTemplate, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c configMapTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c configMapTemplateDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c configMapTemplateDo) Delete(models ...*model.ConfigMapTemplate) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *configMapTemplateDo) withDO(do gen.Dao) *configMapTemplateDo {
	c.DO = *do.(*gen.DO)
	return c
}
