// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newConfigMap(db *gorm.DB, opts ...gen.DOOption) configMap {
	_configMap := configMap{}

	_configMap.configMapDo.UseDB(db, opts...)
	_configMap.configMapDo.UseModel(&model.ConfigMap{})

	tableName := _configMap.configMapDo.TableName()
	_configMap.ALL = field.NewAsterisk(tableName)
	_configMap.ID = field.NewInt64(tableName, "id")
	_configMap.Name = field.NewString(tableName, "name")
	_configMap.MetaData = field.NewString(tableName, "meta_data")
	_configMap.AppID = field.NewInt64(tableName, "app_id")
	_configMap.Description = field.NewString(tableName, "description")
	_configMap.OrderID = field.NewInt64(tableName, "order_id")
	_configMap.CreateTime = field.NewTime(tableName, "create_time")
	_configMap.UpdateTime = field.NewTime(tableName, "update_time")
	_configMap.User = field.NewString(tableName, "user")
	_configMap.Deleted = field.NewBool(tableName, "deleted")

	_configMap.fillFieldMap()

	return _configMap
}

type configMap struct {
	configMapDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	MetaData    field.String
	AppID       field.Int64
	Description field.String
	OrderID     field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (c configMap) Table(newTableName string) *configMap {
	c.configMapDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c configMap) As(alias string) *configMap {
	c.configMapDo.DO = *(c.configMapDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *configMap) updateTableName(table string) *configMap {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Name = field.NewString(table, "name")
	c.MetaData = field.NewString(table, "meta_data")
	c.AppID = field.NewInt64(table, "app_id")
	c.Description = field.NewString(table, "description")
	c.OrderID = field.NewInt64(table, "order_id")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.User = field.NewString(table, "user")
	c.Deleted = field.NewBool(table, "deleted")

	c.fillFieldMap()

	return c
}

func (c *configMap) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *configMap) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["meta_data"] = c.MetaData
	c.fieldMap["app_id"] = c.AppID
	c.fieldMap["description"] = c.Description
	c.fieldMap["order_id"] = c.OrderID
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["user"] = c.User
	c.fieldMap["deleted"] = c.Deleted
}

func (c configMap) clone(db *gorm.DB) configMap {
	c.configMapDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c configMap) replaceDB(db *gorm.DB) configMap {
	c.configMapDo.ReplaceDB(db)
	return c
}

type configMapDo struct{ gen.DO }

type IConfigMapDo interface {
	gen.SubQuery
	Debug() IConfigMapDo
	WithContext(ctx context.Context) IConfigMapDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConfigMapDo
	WriteDB() IConfigMapDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConfigMapDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConfigMapDo
	Not(conds ...gen.Condition) IConfigMapDo
	Or(conds ...gen.Condition) IConfigMapDo
	Select(conds ...field.Expr) IConfigMapDo
	Where(conds ...gen.Condition) IConfigMapDo
	Order(conds ...field.Expr) IConfigMapDo
	Distinct(cols ...field.Expr) IConfigMapDo
	Omit(cols ...field.Expr) IConfigMapDo
	Join(table schema.Tabler, on ...field.Expr) IConfigMapDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConfigMapDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConfigMapDo
	Group(cols ...field.Expr) IConfigMapDo
	Having(conds ...gen.Condition) IConfigMapDo
	Limit(limit int) IConfigMapDo
	Offset(offset int) IConfigMapDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConfigMapDo
	Unscoped() IConfigMapDo
	Create(values ...*model.ConfigMap) error
	CreateInBatches(values []*model.ConfigMap, batchSize int) error
	Save(values ...*model.ConfigMap) error
	First() (*model.ConfigMap, error)
	Take() (*model.ConfigMap, error)
	Last() (*model.ConfigMap, error)
	Find() ([]*model.ConfigMap, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConfigMap, err error)
	FindInBatches(result *[]*model.ConfigMap, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ConfigMap) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConfigMapDo
	Assign(attrs ...field.AssignExpr) IConfigMapDo
	Joins(fields ...field.RelationField) IConfigMapDo
	Preload(fields ...field.RelationField) IConfigMapDo
	FirstOrInit() (*model.ConfigMap, error)
	FirstOrCreate() (*model.ConfigMap, error)
	FindByPage(offset int, limit int) (result []*model.ConfigMap, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConfigMapDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c configMapDo) Debug() IConfigMapDo {
	return c.withDO(c.DO.Debug())
}

func (c configMapDo) WithContext(ctx context.Context) IConfigMapDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c configMapDo) ReadDB() IConfigMapDo {
	return c.Clauses(dbresolver.Read)
}

func (c configMapDo) WriteDB() IConfigMapDo {
	return c.Clauses(dbresolver.Write)
}

func (c configMapDo) Session(config *gorm.Session) IConfigMapDo {
	return c.withDO(c.DO.Session(config))
}

func (c configMapDo) Clauses(conds ...clause.Expression) IConfigMapDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c configMapDo) Returning(value interface{}, columns ...string) IConfigMapDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c configMapDo) Not(conds ...gen.Condition) IConfigMapDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c configMapDo) Or(conds ...gen.Condition) IConfigMapDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c configMapDo) Select(conds ...field.Expr) IConfigMapDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c configMapDo) Where(conds ...gen.Condition) IConfigMapDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c configMapDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IConfigMapDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c configMapDo) Order(conds ...field.Expr) IConfigMapDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c configMapDo) Distinct(cols ...field.Expr) IConfigMapDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c configMapDo) Omit(cols ...field.Expr) IConfigMapDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c configMapDo) Join(table schema.Tabler, on ...field.Expr) IConfigMapDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c configMapDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConfigMapDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c configMapDo) RightJoin(table schema.Tabler, on ...field.Expr) IConfigMapDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c configMapDo) Group(cols ...field.Expr) IConfigMapDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c configMapDo) Having(conds ...gen.Condition) IConfigMapDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c configMapDo) Limit(limit int) IConfigMapDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c configMapDo) Offset(offset int) IConfigMapDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c configMapDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConfigMapDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c configMapDo) Unscoped() IConfigMapDo {
	return c.withDO(c.DO.Unscoped())
}

func (c configMapDo) Create(values ...*model.ConfigMap) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c configMapDo) CreateInBatches(values []*model.ConfigMap, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c configMapDo) Save(values ...*model.ConfigMap) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c configMapDo) First() (*model.ConfigMap, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigMap), nil
	}
}

func (c configMapDo) Take() (*model.ConfigMap, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigMap), nil
	}
}

func (c configMapDo) Last() (*model.ConfigMap, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigMap), nil
	}
}

func (c configMapDo) Find() ([]*model.ConfigMap, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConfigMap), err
}

func (c configMapDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConfigMap, err error) {
	buf := make([]*model.ConfigMap, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c configMapDo) FindInBatches(result *[]*model.ConfigMap, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c configMapDo) Attrs(attrs ...field.AssignExpr) IConfigMapDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c configMapDo) Assign(attrs ...field.AssignExpr) IConfigMapDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c configMapDo) Joins(fields ...field.RelationField) IConfigMapDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c configMapDo) Preload(fields ...field.RelationField) IConfigMapDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c configMapDo) FirstOrInit() (*model.ConfigMap, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigMap), nil
	}
}

func (c configMapDo) FirstOrCreate() (*model.ConfigMap, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConfigMap), nil
	}
}

func (c configMapDo) FindByPage(offset int, limit int) (result []*model.ConfigMap, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c configMapDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c configMapDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c configMapDo) Delete(models ...*model.ConfigMap) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *configMapDo) withDO(do gen.Dao) *configMapDo {
	c.DO = *do.(*gen.DO)
	return c
}
