// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newCronjobTemplate(db *gorm.DB, opts ...gen.DOOption) cronjobTemplate {
	_cronjobTemplate := cronjobTemplate{}

	_cronjobTemplate.cronjobTemplateDo.UseDB(db, opts...)
	_cronjobTemplate.cronjobTemplateDo.UseModel(&model.CronjobTemplate{})

	tableName := _cronjobTemplate.cronjobTemplateDo.TableName()
	_cronjobTemplate.ALL = field.NewAsterisk(tableName)
	_cronjobTemplate.ID = field.NewInt64(tableName, "id")
	_cronjobTemplate.Name = field.NewString(tableName, "name")
	_cronjobTemplate.Template = field.NewString(tableName, "template")
	_cronjobTemplate.CronjobID = field.NewInt64(tableName, "cronjob_id")
	_cronjobTemplate.MetaData = field.NewString(tableName, "meta_data")
	_cronjobTemplate.Description = field.NewString(tableName, "description")
	_cronjobTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_cronjobTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_cronjobTemplate.User = field.NewString(tableName, "user")
	_cronjobTemplate.Deleted = field.NewBool(tableName, "deleted")

	_cronjobTemplate.fillFieldMap()

	return _cronjobTemplate
}

type cronjobTemplate struct {
	cronjobTemplateDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Template    field.String
	CronjobID   field.Int64
	MetaData    field.String
	Description field.String
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (c cronjobTemplate) Table(newTableName string) *cronjobTemplate {
	c.cronjobTemplateDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cronjobTemplate) As(alias string) *cronjobTemplate {
	c.cronjobTemplateDo.DO = *(c.cronjobTemplateDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cronjobTemplate) updateTableName(table string) *cronjobTemplate {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Name = field.NewString(table, "name")
	c.Template = field.NewString(table, "template")
	c.CronjobID = field.NewInt64(table, "cronjob_id")
	c.MetaData = field.NewString(table, "meta_data")
	c.Description = field.NewString(table, "description")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.User = field.NewString(table, "user")
	c.Deleted = field.NewBool(table, "deleted")

	c.fillFieldMap()

	return c
}

func (c *cronjobTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cronjobTemplate) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["template"] = c.Template
	c.fieldMap["cronjob_id"] = c.CronjobID
	c.fieldMap["meta_data"] = c.MetaData
	c.fieldMap["description"] = c.Description
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["user"] = c.User
	c.fieldMap["deleted"] = c.Deleted
}

func (c cronjobTemplate) clone(db *gorm.DB) cronjobTemplate {
	c.cronjobTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cronjobTemplate) replaceDB(db *gorm.DB) cronjobTemplate {
	c.cronjobTemplateDo.ReplaceDB(db)
	return c
}

type cronjobTemplateDo struct{ gen.DO }

type ICronjobTemplateDo interface {
	gen.SubQuery
	Debug() ICronjobTemplateDo
	WithContext(ctx context.Context) ICronjobTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICronjobTemplateDo
	WriteDB() ICronjobTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICronjobTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICronjobTemplateDo
	Not(conds ...gen.Condition) ICronjobTemplateDo
	Or(conds ...gen.Condition) ICronjobTemplateDo
	Select(conds ...field.Expr) ICronjobTemplateDo
	Where(conds ...gen.Condition) ICronjobTemplateDo
	Order(conds ...field.Expr) ICronjobTemplateDo
	Distinct(cols ...field.Expr) ICronjobTemplateDo
	Omit(cols ...field.Expr) ICronjobTemplateDo
	Join(table schema.Tabler, on ...field.Expr) ICronjobTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICronjobTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICronjobTemplateDo
	Group(cols ...field.Expr) ICronjobTemplateDo
	Having(conds ...gen.Condition) ICronjobTemplateDo
	Limit(limit int) ICronjobTemplateDo
	Offset(offset int) ICronjobTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICronjobTemplateDo
	Unscoped() ICronjobTemplateDo
	Create(values ...*model.CronjobTemplate) error
	CreateInBatches(values []*model.CronjobTemplate, batchSize int) error
	Save(values ...*model.CronjobTemplate) error
	First() (*model.CronjobTemplate, error)
	Take() (*model.CronjobTemplate, error)
	Last() (*model.CronjobTemplate, error)
	Find() ([]*model.CronjobTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CronjobTemplate, err error)
	FindInBatches(result *[]*model.CronjobTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CronjobTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICronjobTemplateDo
	Assign(attrs ...field.AssignExpr) ICronjobTemplateDo
	Joins(fields ...field.RelationField) ICronjobTemplateDo
	Preload(fields ...field.RelationField) ICronjobTemplateDo
	FirstOrInit() (*model.CronjobTemplate, error)
	FirstOrCreate() (*model.CronjobTemplate, error)
	FindByPage(offset int, limit int) (result []*model.CronjobTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICronjobTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cronjobTemplateDo) Debug() ICronjobTemplateDo {
	return c.withDO(c.DO.Debug())
}

func (c cronjobTemplateDo) WithContext(ctx context.Context) ICronjobTemplateDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cronjobTemplateDo) ReadDB() ICronjobTemplateDo {
	return c.Clauses(dbresolver.Read)
}

func (c cronjobTemplateDo) WriteDB() ICronjobTemplateDo {
	return c.Clauses(dbresolver.Write)
}

func (c cronjobTemplateDo) Session(config *gorm.Session) ICronjobTemplateDo {
	return c.withDO(c.DO.Session(config))
}

func (c cronjobTemplateDo) Clauses(conds ...clause.Expression) ICronjobTemplateDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cronjobTemplateDo) Returning(value interface{}, columns ...string) ICronjobTemplateDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cronjobTemplateDo) Not(conds ...gen.Condition) ICronjobTemplateDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cronjobTemplateDo) Or(conds ...gen.Condition) ICronjobTemplateDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cronjobTemplateDo) Select(conds ...field.Expr) ICronjobTemplateDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cronjobTemplateDo) Where(conds ...gen.Condition) ICronjobTemplateDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cronjobTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) ICronjobTemplateDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cronjobTemplateDo) Order(conds ...field.Expr) ICronjobTemplateDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cronjobTemplateDo) Distinct(cols ...field.Expr) ICronjobTemplateDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cronjobTemplateDo) Omit(cols ...field.Expr) ICronjobTemplateDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cronjobTemplateDo) Join(table schema.Tabler, on ...field.Expr) ICronjobTemplateDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cronjobTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICronjobTemplateDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cronjobTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) ICronjobTemplateDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cronjobTemplateDo) Group(cols ...field.Expr) ICronjobTemplateDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cronjobTemplateDo) Having(conds ...gen.Condition) ICronjobTemplateDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cronjobTemplateDo) Limit(limit int) ICronjobTemplateDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cronjobTemplateDo) Offset(offset int) ICronjobTemplateDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cronjobTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICronjobTemplateDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cronjobTemplateDo) Unscoped() ICronjobTemplateDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cronjobTemplateDo) Create(values ...*model.CronjobTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cronjobTemplateDo) CreateInBatches(values []*model.CronjobTemplate, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cronjobTemplateDo) Save(values ...*model.CronjobTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cronjobTemplateDo) First() (*model.CronjobTemplate, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CronjobTemplate), nil
	}
}

func (c cronjobTemplateDo) Take() (*model.CronjobTemplate, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CronjobTemplate), nil
	}
}

func (c cronjobTemplateDo) Last() (*model.CronjobTemplate, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CronjobTemplate), nil
	}
}

func (c cronjobTemplateDo) Find() ([]*model.CronjobTemplate, error) {
	result, err := c.DO.Find()
	return result.([]*model.CronjobTemplate), err
}

func (c cronjobTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CronjobTemplate, err error) {
	buf := make([]*model.CronjobTemplate, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cronjobTemplateDo) FindInBatches(result *[]*model.CronjobTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cronjobTemplateDo) Attrs(attrs ...field.AssignExpr) ICronjobTemplateDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cronjobTemplateDo) Assign(attrs ...field.AssignExpr) ICronjobTemplateDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cronjobTemplateDo) Joins(fields ...field.RelationField) ICronjobTemplateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cronjobTemplateDo) Preload(fields ...field.RelationField) ICronjobTemplateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cronjobTemplateDo) FirstOrInit() (*model.CronjobTemplate, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CronjobTemplate), nil
	}
}

func (c cronjobTemplateDo) FirstOrCreate() (*model.CronjobTemplate, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CronjobTemplate), nil
	}
}

func (c cronjobTemplateDo) FindByPage(offset int, limit int) (result []*model.CronjobTemplate, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cronjobTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cronjobTemplateDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cronjobTemplateDo) Delete(models ...*model.CronjobTemplate) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cronjobTemplateDo) withDO(do gen.Dao) *cronjobTemplateDo {
	c.DO = *do.(*gen.DO)
	return c
}
