// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newDaemonSet(db *gorm.DB, opts ...gen.DOOption) daemonSet {
	_daemonSet := daemonSet{}

	_daemonSet.daemonSetDo.UseDB(db, opts...)
	_daemonSet.daemonSetDo.UseModel(&model.DaemonSet{})

	tableName := _daemonSet.daemonSetDo.TableName()
	_daemonSet.ALL = field.NewAsterisk(tableName)
	_daemonSet.ID = field.NewInt64(tableName, "id")
	_daemonSet.Name = field.NewString(tableName, "name")
	_daemonSet.MetaData = field.NewString(tableName, "meta_data")
	_daemonSet.AppID = field.NewInt64(tableName, "app_id")
	_daemonSet.Description = field.NewString(tableName, "description")
	_daemonSet.OrderID = field.NewInt64(tableName, "order_id")
	_daemonSet.CreateTime = field.NewTime(tableName, "create_time")
	_daemonSet.UpdateTime = field.NewTime(tableName, "update_time")
	_daemonSet.User = field.NewString(tableName, "user")
	_daemonSet.Deleted = field.NewBool(tableName, "deleted")

	_daemonSet.fillFieldMap()

	return _daemonSet
}

type daemonSet struct {
	daemonSetDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	MetaData    field.String
	AppID       field.Int64
	Description field.String
	OrderID     field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (d daemonSet) Table(newTableName string) *daemonSet {
	d.daemonSetDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d daemonSet) As(alias string) *daemonSet {
	d.daemonSetDo.DO = *(d.daemonSetDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *daemonSet) updateTableName(table string) *daemonSet {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.Name = field.NewString(table, "name")
	d.MetaData = field.NewString(table, "meta_data")
	d.AppID = field.NewInt64(table, "app_id")
	d.Description = field.NewString(table, "description")
	d.OrderID = field.NewInt64(table, "order_id")
	d.CreateTime = field.NewTime(table, "create_time")
	d.UpdateTime = field.NewTime(table, "update_time")
	d.User = field.NewString(table, "user")
	d.Deleted = field.NewBool(table, "deleted")

	d.fillFieldMap()

	return d
}

func (d *daemonSet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *daemonSet) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["name"] = d.Name
	d.fieldMap["meta_data"] = d.MetaData
	d.fieldMap["app_id"] = d.AppID
	d.fieldMap["description"] = d.Description
	d.fieldMap["order_id"] = d.OrderID
	d.fieldMap["create_time"] = d.CreateTime
	d.fieldMap["update_time"] = d.UpdateTime
	d.fieldMap["user"] = d.User
	d.fieldMap["deleted"] = d.Deleted
}

func (d daemonSet) clone(db *gorm.DB) daemonSet {
	d.daemonSetDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d daemonSet) replaceDB(db *gorm.DB) daemonSet {
	d.daemonSetDo.ReplaceDB(db)
	return d
}

type daemonSetDo struct{ gen.DO }

type IDaemonSetDo interface {
	gen.SubQuery
	Debug() IDaemonSetDo
	WithContext(ctx context.Context) IDaemonSetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDaemonSetDo
	WriteDB() IDaemonSetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDaemonSetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDaemonSetDo
	Not(conds ...gen.Condition) IDaemonSetDo
	Or(conds ...gen.Condition) IDaemonSetDo
	Select(conds ...field.Expr) IDaemonSetDo
	Where(conds ...gen.Condition) IDaemonSetDo
	Order(conds ...field.Expr) IDaemonSetDo
	Distinct(cols ...field.Expr) IDaemonSetDo
	Omit(cols ...field.Expr) IDaemonSetDo
	Join(table schema.Tabler, on ...field.Expr) IDaemonSetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDaemonSetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDaemonSetDo
	Group(cols ...field.Expr) IDaemonSetDo
	Having(conds ...gen.Condition) IDaemonSetDo
	Limit(limit int) IDaemonSetDo
	Offset(offset int) IDaemonSetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDaemonSetDo
	Unscoped() IDaemonSetDo
	Create(values ...*model.DaemonSet) error
	CreateInBatches(values []*model.DaemonSet, batchSize int) error
	Save(values ...*model.DaemonSet) error
	First() (*model.DaemonSet, error)
	Take() (*model.DaemonSet, error)
	Last() (*model.DaemonSet, error)
	Find() ([]*model.DaemonSet, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DaemonSet, err error)
	FindInBatches(result *[]*model.DaemonSet, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DaemonSet) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDaemonSetDo
	Assign(attrs ...field.AssignExpr) IDaemonSetDo
	Joins(fields ...field.RelationField) IDaemonSetDo
	Preload(fields ...field.RelationField) IDaemonSetDo
	FirstOrInit() (*model.DaemonSet, error)
	FirstOrCreate() (*model.DaemonSet, error)
	FindByPage(offset int, limit int) (result []*model.DaemonSet, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDaemonSetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d daemonSetDo) Debug() IDaemonSetDo {
	return d.withDO(d.DO.Debug())
}

func (d daemonSetDo) WithContext(ctx context.Context) IDaemonSetDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d daemonSetDo) ReadDB() IDaemonSetDo {
	return d.Clauses(dbresolver.Read)
}

func (d daemonSetDo) WriteDB() IDaemonSetDo {
	return d.Clauses(dbresolver.Write)
}

func (d daemonSetDo) Session(config *gorm.Session) IDaemonSetDo {
	return d.withDO(d.DO.Session(config))
}

func (d daemonSetDo) Clauses(conds ...clause.Expression) IDaemonSetDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d daemonSetDo) Returning(value interface{}, columns ...string) IDaemonSetDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d daemonSetDo) Not(conds ...gen.Condition) IDaemonSetDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d daemonSetDo) Or(conds ...gen.Condition) IDaemonSetDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d daemonSetDo) Select(conds ...field.Expr) IDaemonSetDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d daemonSetDo) Where(conds ...gen.Condition) IDaemonSetDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d daemonSetDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IDaemonSetDo {
	return d.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (d daemonSetDo) Order(conds ...field.Expr) IDaemonSetDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d daemonSetDo) Distinct(cols ...field.Expr) IDaemonSetDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d daemonSetDo) Omit(cols ...field.Expr) IDaemonSetDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d daemonSetDo) Join(table schema.Tabler, on ...field.Expr) IDaemonSetDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d daemonSetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDaemonSetDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d daemonSetDo) RightJoin(table schema.Tabler, on ...field.Expr) IDaemonSetDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d daemonSetDo) Group(cols ...field.Expr) IDaemonSetDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d daemonSetDo) Having(conds ...gen.Condition) IDaemonSetDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d daemonSetDo) Limit(limit int) IDaemonSetDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d daemonSetDo) Offset(offset int) IDaemonSetDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d daemonSetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDaemonSetDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d daemonSetDo) Unscoped() IDaemonSetDo {
	return d.withDO(d.DO.Unscoped())
}

func (d daemonSetDo) Create(values ...*model.DaemonSet) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d daemonSetDo) CreateInBatches(values []*model.DaemonSet, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d daemonSetDo) Save(values ...*model.DaemonSet) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d daemonSetDo) First() (*model.DaemonSet, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DaemonSet), nil
	}
}

func (d daemonSetDo) Take() (*model.DaemonSet, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DaemonSet), nil
	}
}

func (d daemonSetDo) Last() (*model.DaemonSet, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DaemonSet), nil
	}
}

func (d daemonSetDo) Find() ([]*model.DaemonSet, error) {
	result, err := d.DO.Find()
	return result.([]*model.DaemonSet), err
}

func (d daemonSetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DaemonSet, err error) {
	buf := make([]*model.DaemonSet, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d daemonSetDo) FindInBatches(result *[]*model.DaemonSet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d daemonSetDo) Attrs(attrs ...field.AssignExpr) IDaemonSetDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d daemonSetDo) Assign(attrs ...field.AssignExpr) IDaemonSetDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d daemonSetDo) Joins(fields ...field.RelationField) IDaemonSetDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d daemonSetDo) Preload(fields ...field.RelationField) IDaemonSetDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d daemonSetDo) FirstOrInit() (*model.DaemonSet, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DaemonSet), nil
	}
}

func (d daemonSetDo) FirstOrCreate() (*model.DaemonSet, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DaemonSet), nil
	}
}

func (d daemonSetDo) FindByPage(offset int, limit int) (result []*model.DaemonSet, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d daemonSetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d daemonSetDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d daemonSetDo) Delete(models ...*model.DaemonSet) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *daemonSetDo) withDO(do gen.Dao) *daemonSetDo {
	d.DO = *do.(*gen.DO)
	return d
}
