// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newDaemonSetTemplate(db *gorm.DB, opts ...gen.DOOption) daemonSetTemplate {
	_daemonSetTemplate := daemonSetTemplate{}

	_daemonSetTemplate.daemonSetTemplateDo.UseDB(db, opts...)
	_daemonSetTemplate.daemonSetTemplateDo.UseModel(&model.DaemonSetTemplate{})

	tableName := _daemonSetTemplate.daemonSetTemplateDo.TableName()
	_daemonSetTemplate.ALL = field.NewAsterisk(tableName)
	_daemonSetTemplate.ID = field.NewInt64(tableName, "id")
	_daemonSetTemplate.Name = field.NewString(tableName, "name")
	_daemonSetTemplate.Template = field.NewString(tableName, "template")
	_daemonSetTemplate.DaemonSetID = field.NewInt64(tableName, "daemon_set_id")
	_daemonSetTemplate.Description = field.NewString(tableName, "description")
	_daemonSetTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_daemonSetTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_daemonSetTemplate.User = field.NewString(tableName, "user")
	_daemonSetTemplate.Deleted = field.NewBool(tableName, "deleted")

	_daemonSetTemplate.fillFieldMap()

	return _daemonSetTemplate
}

type daemonSetTemplate struct {
	daemonSetTemplateDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Template    field.String
	DaemonSetID field.Int64
	Description field.String
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (d daemonSetTemplate) Table(newTableName string) *daemonSetTemplate {
	d.daemonSetTemplateDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d daemonSetTemplate) As(alias string) *daemonSetTemplate {
	d.daemonSetTemplateDo.DO = *(d.daemonSetTemplateDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *daemonSetTemplate) updateTableName(table string) *daemonSetTemplate {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.Name = field.NewString(table, "name")
	d.Template = field.NewString(table, "template")
	d.DaemonSetID = field.NewInt64(table, "daemon_set_id")
	d.Description = field.NewString(table, "description")
	d.CreateTime = field.NewTime(table, "create_time")
	d.UpdateTime = field.NewTime(table, "update_time")
	d.User = field.NewString(table, "user")
	d.Deleted = field.NewBool(table, "deleted")

	d.fillFieldMap()

	return d
}

func (d *daemonSetTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *daemonSetTemplate) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["id"] = d.ID
	d.fieldMap["name"] = d.Name
	d.fieldMap["template"] = d.Template
	d.fieldMap["daemon_set_id"] = d.DaemonSetID
	d.fieldMap["description"] = d.Description
	d.fieldMap["create_time"] = d.CreateTime
	d.fieldMap["update_time"] = d.UpdateTime
	d.fieldMap["user"] = d.User
	d.fieldMap["deleted"] = d.Deleted
}

func (d daemonSetTemplate) clone(db *gorm.DB) daemonSetTemplate {
	d.daemonSetTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d daemonSetTemplate) replaceDB(db *gorm.DB) daemonSetTemplate {
	d.daemonSetTemplateDo.ReplaceDB(db)
	return d
}

type daemonSetTemplateDo struct{ gen.DO }

type IDaemonSetTemplateDo interface {
	gen.SubQuery
	Debug() IDaemonSetTemplateDo
	WithContext(ctx context.Context) IDaemonSetTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDaemonSetTemplateDo
	WriteDB() IDaemonSetTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDaemonSetTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDaemonSetTemplateDo
	Not(conds ...gen.Condition) IDaemonSetTemplateDo
	Or(conds ...gen.Condition) IDaemonSetTemplateDo
	Select(conds ...field.Expr) IDaemonSetTemplateDo
	Where(conds ...gen.Condition) IDaemonSetTemplateDo
	Order(conds ...field.Expr) IDaemonSetTemplateDo
	Distinct(cols ...field.Expr) IDaemonSetTemplateDo
	Omit(cols ...field.Expr) IDaemonSetTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IDaemonSetTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDaemonSetTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDaemonSetTemplateDo
	Group(cols ...field.Expr) IDaemonSetTemplateDo
	Having(conds ...gen.Condition) IDaemonSetTemplateDo
	Limit(limit int) IDaemonSetTemplateDo
	Offset(offset int) IDaemonSetTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDaemonSetTemplateDo
	Unscoped() IDaemonSetTemplateDo
	Create(values ...*model.DaemonSetTemplate) error
	CreateInBatches(values []*model.DaemonSetTemplate, batchSize int) error
	Save(values ...*model.DaemonSetTemplate) error
	First() (*model.DaemonSetTemplate, error)
	Take() (*model.DaemonSetTemplate, error)
	Last() (*model.DaemonSetTemplate, error)
	Find() ([]*model.DaemonSetTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DaemonSetTemplate, err error)
	FindInBatches(result *[]*model.DaemonSetTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DaemonSetTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDaemonSetTemplateDo
	Assign(attrs ...field.AssignExpr) IDaemonSetTemplateDo
	Joins(fields ...field.RelationField) IDaemonSetTemplateDo
	Preload(fields ...field.RelationField) IDaemonSetTemplateDo
	FirstOrInit() (*model.DaemonSetTemplate, error)
	FirstOrCreate() (*model.DaemonSetTemplate, error)
	FindByPage(offset int, limit int) (result []*model.DaemonSetTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDaemonSetTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d daemonSetTemplateDo) Debug() IDaemonSetTemplateDo {
	return d.withDO(d.DO.Debug())
}

func (d daemonSetTemplateDo) WithContext(ctx context.Context) IDaemonSetTemplateDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d daemonSetTemplateDo) ReadDB() IDaemonSetTemplateDo {
	return d.Clauses(dbresolver.Read)
}

func (d daemonSetTemplateDo) WriteDB() IDaemonSetTemplateDo {
	return d.Clauses(dbresolver.Write)
}

func (d daemonSetTemplateDo) Session(config *gorm.Session) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Session(config))
}

func (d daemonSetTemplateDo) Clauses(conds ...clause.Expression) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d daemonSetTemplateDo) Returning(value interface{}, columns ...string) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d daemonSetTemplateDo) Not(conds ...gen.Condition) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d daemonSetTemplateDo) Or(conds ...gen.Condition) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d daemonSetTemplateDo) Select(conds ...field.Expr) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d daemonSetTemplateDo) Where(conds ...gen.Condition) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d daemonSetTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IDaemonSetTemplateDo {
	return d.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (d daemonSetTemplateDo) Order(conds ...field.Expr) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d daemonSetTemplateDo) Distinct(cols ...field.Expr) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d daemonSetTemplateDo) Omit(cols ...field.Expr) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d daemonSetTemplateDo) Join(table schema.Tabler, on ...field.Expr) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d daemonSetTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDaemonSetTemplateDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d daemonSetTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IDaemonSetTemplateDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d daemonSetTemplateDo) Group(cols ...field.Expr) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d daemonSetTemplateDo) Having(conds ...gen.Condition) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d daemonSetTemplateDo) Limit(limit int) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d daemonSetTemplateDo) Offset(offset int) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d daemonSetTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d daemonSetTemplateDo) Unscoped() IDaemonSetTemplateDo {
	return d.withDO(d.DO.Unscoped())
}

func (d daemonSetTemplateDo) Create(values ...*model.DaemonSetTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d daemonSetTemplateDo) CreateInBatches(values []*model.DaemonSetTemplate, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d daemonSetTemplateDo) Save(values ...*model.DaemonSetTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d daemonSetTemplateDo) First() (*model.DaemonSetTemplate, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DaemonSetTemplate), nil
	}
}

func (d daemonSetTemplateDo) Take() (*model.DaemonSetTemplate, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DaemonSetTemplate), nil
	}
}

func (d daemonSetTemplateDo) Last() (*model.DaemonSetTemplate, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DaemonSetTemplate), nil
	}
}

func (d daemonSetTemplateDo) Find() ([]*model.DaemonSetTemplate, error) {
	result, err := d.DO.Find()
	return result.([]*model.DaemonSetTemplate), err
}

func (d daemonSetTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DaemonSetTemplate, err error) {
	buf := make([]*model.DaemonSetTemplate, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d daemonSetTemplateDo) FindInBatches(result *[]*model.DaemonSetTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d daemonSetTemplateDo) Attrs(attrs ...field.AssignExpr) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d daemonSetTemplateDo) Assign(attrs ...field.AssignExpr) IDaemonSetTemplateDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d daemonSetTemplateDo) Joins(fields ...field.RelationField) IDaemonSetTemplateDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d daemonSetTemplateDo) Preload(fields ...field.RelationField) IDaemonSetTemplateDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d daemonSetTemplateDo) FirstOrInit() (*model.DaemonSetTemplate, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DaemonSetTemplate), nil
	}
}

func (d daemonSetTemplateDo) FirstOrCreate() (*model.DaemonSetTemplate, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DaemonSetTemplate), nil
	}
}

func (d daemonSetTemplateDo) FindByPage(offset int, limit int) (result []*model.DaemonSetTemplate, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d daemonSetTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d daemonSetTemplateDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d daemonSetTemplateDo) Delete(models ...*model.DaemonSetTemplate) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *daemonSetTemplateDo) withDO(do gen.Dao) *daemonSetTemplateDo {
	d.DO = *do.(*gen.DO)
	return d
}
