// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newDeploymentTemplate(db *gorm.DB, opts ...gen.DOOption) deploymentTemplate {
	_deploymentTemplate := deploymentTemplate{}

	_deploymentTemplate.deploymentTemplateDo.UseDB(db, opts...)
	_deploymentTemplate.deploymentTemplateDo.UseModel(&model.DeploymentTemplate{})

	tableName := _deploymentTemplate.deploymentTemplateDo.TableName()
	_deploymentTemplate.ALL = field.NewAsterisk(tableName)
	_deploymentTemplate.ID = field.NewInt64(tableName, "id")
	_deploymentTemplate.Name = field.NewString(tableName, "name")
	_deploymentTemplate.Template = field.NewString(tableName, "template")
	_deploymentTemplate.DeploymentID = field.NewInt64(tableName, "deployment_id")
	_deploymentTemplate.Description = field.NewString(tableName, "description")
	_deploymentTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_deploymentTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_deploymentTemplate.User = field.NewString(tableName, "user")
	_deploymentTemplate.Deleted = field.NewBool(tableName, "deleted")

	_deploymentTemplate.fillFieldMap()

	return _deploymentTemplate
}

type deploymentTemplate struct {
	deploymentTemplateDo

	ALL          field.Asterisk
	ID           field.Int64
	Name         field.String
	Template     field.String
	DeploymentID field.Int64
	Description  field.String
	CreateTime   field.Time
	UpdateTime   field.Time
	User         field.String
	Deleted      field.Bool

	fieldMap map[string]field.Expr
}

func (d deploymentTemplate) Table(newTableName string) *deploymentTemplate {
	d.deploymentTemplateDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deploymentTemplate) As(alias string) *deploymentTemplate {
	d.deploymentTemplateDo.DO = *(d.deploymentTemplateDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deploymentTemplate) updateTableName(table string) *deploymentTemplate {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.Name = field.NewString(table, "name")
	d.Template = field.NewString(table, "template")
	d.DeploymentID = field.NewInt64(table, "deployment_id")
	d.Description = field.NewString(table, "description")
	d.CreateTime = field.NewTime(table, "create_time")
	d.UpdateTime = field.NewTime(table, "update_time")
	d.User = field.NewString(table, "user")
	d.Deleted = field.NewBool(table, "deleted")

	d.fillFieldMap()

	return d
}

func (d *deploymentTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deploymentTemplate) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["id"] = d.ID
	d.fieldMap["name"] = d.Name
	d.fieldMap["template"] = d.Template
	d.fieldMap["deployment_id"] = d.DeploymentID
	d.fieldMap["description"] = d.Description
	d.fieldMap["create_time"] = d.CreateTime
	d.fieldMap["update_time"] = d.UpdateTime
	d.fieldMap["user"] = d.User
	d.fieldMap["deleted"] = d.Deleted
}

func (d deploymentTemplate) clone(db *gorm.DB) deploymentTemplate {
	d.deploymentTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deploymentTemplate) replaceDB(db *gorm.DB) deploymentTemplate {
	d.deploymentTemplateDo.ReplaceDB(db)
	return d
}

type deploymentTemplateDo struct{ gen.DO }

type IDeploymentTemplateDo interface {
	gen.SubQuery
	Debug() IDeploymentTemplateDo
	WithContext(ctx context.Context) IDeploymentTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeploymentTemplateDo
	WriteDB() IDeploymentTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeploymentTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeploymentTemplateDo
	Not(conds ...gen.Condition) IDeploymentTemplateDo
	Or(conds ...gen.Condition) IDeploymentTemplateDo
	Select(conds ...field.Expr) IDeploymentTemplateDo
	Where(conds ...gen.Condition) IDeploymentTemplateDo
	Order(conds ...field.Expr) IDeploymentTemplateDo
	Distinct(cols ...field.Expr) IDeploymentTemplateDo
	Omit(cols ...field.Expr) IDeploymentTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IDeploymentTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeploymentTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeploymentTemplateDo
	Group(cols ...field.Expr) IDeploymentTemplateDo
	Having(conds ...gen.Condition) IDeploymentTemplateDo
	Limit(limit int) IDeploymentTemplateDo
	Offset(offset int) IDeploymentTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeploymentTemplateDo
	Unscoped() IDeploymentTemplateDo
	Create(values ...*model.DeploymentTemplate) error
	CreateInBatches(values []*model.DeploymentTemplate, batchSize int) error
	Save(values ...*model.DeploymentTemplate) error
	First() (*model.DeploymentTemplate, error)
	Take() (*model.DeploymentTemplate, error)
	Last() (*model.DeploymentTemplate, error)
	Find() ([]*model.DeploymentTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeploymentTemplate, err error)
	FindInBatches(result *[]*model.DeploymentTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeploymentTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeploymentTemplateDo
	Assign(attrs ...field.AssignExpr) IDeploymentTemplateDo
	Joins(fields ...field.RelationField) IDeploymentTemplateDo
	Preload(fields ...field.RelationField) IDeploymentTemplateDo
	FirstOrInit() (*model.DeploymentTemplate, error)
	FirstOrCreate() (*model.DeploymentTemplate, error)
	FindByPage(offset int, limit int) (result []*model.DeploymentTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeploymentTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deploymentTemplateDo) Debug() IDeploymentTemplateDo {
	return d.withDO(d.DO.Debug())
}

func (d deploymentTemplateDo) WithContext(ctx context.Context) IDeploymentTemplateDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deploymentTemplateDo) ReadDB() IDeploymentTemplateDo {
	return d.Clauses(dbresolver.Read)
}

func (d deploymentTemplateDo) WriteDB() IDeploymentTemplateDo {
	return d.Clauses(dbresolver.Write)
}

func (d deploymentTemplateDo) Session(config *gorm.Session) IDeploymentTemplateDo {
	return d.withDO(d.DO.Session(config))
}

func (d deploymentTemplateDo) Clauses(conds ...clause.Expression) IDeploymentTemplateDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deploymentTemplateDo) Returning(value interface{}, columns ...string) IDeploymentTemplateDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deploymentTemplateDo) Not(conds ...gen.Condition) IDeploymentTemplateDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deploymentTemplateDo) Or(conds ...gen.Condition) IDeploymentTemplateDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deploymentTemplateDo) Select(conds ...field.Expr) IDeploymentTemplateDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deploymentTemplateDo) Where(conds ...gen.Condition) IDeploymentTemplateDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deploymentTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IDeploymentTemplateDo {
	return d.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (d deploymentTemplateDo) Order(conds ...field.Expr) IDeploymentTemplateDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deploymentTemplateDo) Distinct(cols ...field.Expr) IDeploymentTemplateDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deploymentTemplateDo) Omit(cols ...field.Expr) IDeploymentTemplateDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deploymentTemplateDo) Join(table schema.Tabler, on ...field.Expr) IDeploymentTemplateDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deploymentTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeploymentTemplateDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deploymentTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeploymentTemplateDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deploymentTemplateDo) Group(cols ...field.Expr) IDeploymentTemplateDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deploymentTemplateDo) Having(conds ...gen.Condition) IDeploymentTemplateDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deploymentTemplateDo) Limit(limit int) IDeploymentTemplateDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deploymentTemplateDo) Offset(offset int) IDeploymentTemplateDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deploymentTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeploymentTemplateDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deploymentTemplateDo) Unscoped() IDeploymentTemplateDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deploymentTemplateDo) Create(values ...*model.DeploymentTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deploymentTemplateDo) CreateInBatches(values []*model.DeploymentTemplate, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deploymentTemplateDo) Save(values ...*model.DeploymentTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deploymentTemplateDo) First() (*model.DeploymentTemplate, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeploymentTemplate), nil
	}
}

func (d deploymentTemplateDo) Take() (*model.DeploymentTemplate, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeploymentTemplate), nil
	}
}

func (d deploymentTemplateDo) Last() (*model.DeploymentTemplate, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeploymentTemplate), nil
	}
}

func (d deploymentTemplateDo) Find() ([]*model.DeploymentTemplate, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeploymentTemplate), err
}

func (d deploymentTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeploymentTemplate, err error) {
	buf := make([]*model.DeploymentTemplate, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deploymentTemplateDo) FindInBatches(result *[]*model.DeploymentTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deploymentTemplateDo) Attrs(attrs ...field.AssignExpr) IDeploymentTemplateDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deploymentTemplateDo) Assign(attrs ...field.AssignExpr) IDeploymentTemplateDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deploymentTemplateDo) Joins(fields ...field.RelationField) IDeploymentTemplateDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deploymentTemplateDo) Preload(fields ...field.RelationField) IDeploymentTemplateDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deploymentTemplateDo) FirstOrInit() (*model.DeploymentTemplate, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeploymentTemplate), nil
	}
}

func (d deploymentTemplateDo) FirstOrCreate() (*model.DeploymentTemplate, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeploymentTemplate), nil
	}
}

func (d deploymentTemplateDo) FindByPage(offset int, limit int) (result []*model.DeploymentTemplate, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deploymentTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deploymentTemplateDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deploymentTemplateDo) Delete(models ...*model.DeploymentTemplate) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deploymentTemplateDo) withDO(do gen.Dao) *deploymentTemplateDo {
	d.DO = *do.(*gen.DO)
	return d
}
