// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newDeployment(db *gorm.DB, opts ...gen.DOOption) deployment {
	_deployment := deployment{}

	_deployment.deploymentDo.UseDB(db, opts...)
	_deployment.deploymentDo.UseModel(&model.Deployment{})

	tableName := _deployment.deploymentDo.TableName()
	_deployment.ALL = field.NewAsterisk(tableName)
	_deployment.ID = field.NewInt64(tableName, "id")
	_deployment.Name = field.NewString(tableName, "name")
	_deployment.MetaData = field.NewString(tableName, "meta_data")
	_deployment.AppID = field.NewInt64(tableName, "app_id")
	_deployment.Description = field.NewString(tableName, "description")
	_deployment.OrderID = field.NewInt64(tableName, "order_id")
	_deployment.CreateTime = field.NewTime(tableName, "create_time")
	_deployment.UpdateTime = field.NewTime(tableName, "update_time")
	_deployment.User = field.NewString(tableName, "user")
	_deployment.Deleted = field.NewBool(tableName, "deleted")

	_deployment.fillFieldMap()

	return _deployment
}

type deployment struct {
	deploymentDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	MetaData    field.String
	AppID       field.Int64
	Description field.String
	OrderID     field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (d deployment) Table(newTableName string) *deployment {
	d.deploymentDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deployment) As(alias string) *deployment {
	d.deploymentDo.DO = *(d.deploymentDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deployment) updateTableName(table string) *deployment {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.Name = field.NewString(table, "name")
	d.MetaData = field.NewString(table, "meta_data")
	d.AppID = field.NewInt64(table, "app_id")
	d.Description = field.NewString(table, "description")
	d.OrderID = field.NewInt64(table, "order_id")
	d.CreateTime = field.NewTime(table, "create_time")
	d.UpdateTime = field.NewTime(table, "update_time")
	d.User = field.NewString(table, "user")
	d.Deleted = field.NewBool(table, "deleted")

	d.fillFieldMap()

	return d
}

func (d *deployment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deployment) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["name"] = d.Name
	d.fieldMap["meta_data"] = d.MetaData
	d.fieldMap["app_id"] = d.AppID
	d.fieldMap["description"] = d.Description
	d.fieldMap["order_id"] = d.OrderID
	d.fieldMap["create_time"] = d.CreateTime
	d.fieldMap["update_time"] = d.UpdateTime
	d.fieldMap["user"] = d.User
	d.fieldMap["deleted"] = d.Deleted
}

func (d deployment) clone(db *gorm.DB) deployment {
	d.deploymentDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deployment) replaceDB(db *gorm.DB) deployment {
	d.deploymentDo.ReplaceDB(db)
	return d
}

type deploymentDo struct{ gen.DO }

type IDeploymentDo interface {
	gen.SubQuery
	Debug() IDeploymentDo
	WithContext(ctx context.Context) IDeploymentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeploymentDo
	WriteDB() IDeploymentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeploymentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeploymentDo
	Not(conds ...gen.Condition) IDeploymentDo
	Or(conds ...gen.Condition) IDeploymentDo
	Select(conds ...field.Expr) IDeploymentDo
	Where(conds ...gen.Condition) IDeploymentDo
	Order(conds ...field.Expr) IDeploymentDo
	Distinct(cols ...field.Expr) IDeploymentDo
	Omit(cols ...field.Expr) IDeploymentDo
	Join(table schema.Tabler, on ...field.Expr) IDeploymentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeploymentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeploymentDo
	Group(cols ...field.Expr) IDeploymentDo
	Having(conds ...gen.Condition) IDeploymentDo
	Limit(limit int) IDeploymentDo
	Offset(offset int) IDeploymentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeploymentDo
	Unscoped() IDeploymentDo
	Create(values ...*model.Deployment) error
	CreateInBatches(values []*model.Deployment, batchSize int) error
	Save(values ...*model.Deployment) error
	First() (*model.Deployment, error)
	Take() (*model.Deployment, error)
	Last() (*model.Deployment, error)
	Find() ([]*model.Deployment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Deployment, err error)
	FindInBatches(result *[]*model.Deployment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Deployment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeploymentDo
	Assign(attrs ...field.AssignExpr) IDeploymentDo
	Joins(fields ...field.RelationField) IDeploymentDo
	Preload(fields ...field.RelationField) IDeploymentDo
	FirstOrInit() (*model.Deployment, error)
	FirstOrCreate() (*model.Deployment, error)
	FindByPage(offset int, limit int) (result []*model.Deployment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeploymentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deploymentDo) Debug() IDeploymentDo {
	return d.withDO(d.DO.Debug())
}

func (d deploymentDo) WithContext(ctx context.Context) IDeploymentDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deploymentDo) ReadDB() IDeploymentDo {
	return d.Clauses(dbresolver.Read)
}

func (d deploymentDo) WriteDB() IDeploymentDo {
	return d.Clauses(dbresolver.Write)
}

func (d deploymentDo) Session(config *gorm.Session) IDeploymentDo {
	return d.withDO(d.DO.Session(config))
}

func (d deploymentDo) Clauses(conds ...clause.Expression) IDeploymentDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deploymentDo) Returning(value interface{}, columns ...string) IDeploymentDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deploymentDo) Not(conds ...gen.Condition) IDeploymentDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deploymentDo) Or(conds ...gen.Condition) IDeploymentDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deploymentDo) Select(conds ...field.Expr) IDeploymentDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deploymentDo) Where(conds ...gen.Condition) IDeploymentDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deploymentDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IDeploymentDo {
	return d.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (d deploymentDo) Order(conds ...field.Expr) IDeploymentDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deploymentDo) Distinct(cols ...field.Expr) IDeploymentDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deploymentDo) Omit(cols ...field.Expr) IDeploymentDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deploymentDo) Join(table schema.Tabler, on ...field.Expr) IDeploymentDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deploymentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeploymentDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deploymentDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeploymentDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deploymentDo) Group(cols ...field.Expr) IDeploymentDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deploymentDo) Having(conds ...gen.Condition) IDeploymentDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deploymentDo) Limit(limit int) IDeploymentDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deploymentDo) Offset(offset int) IDeploymentDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deploymentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeploymentDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deploymentDo) Unscoped() IDeploymentDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deploymentDo) Create(values ...*model.Deployment) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deploymentDo) CreateInBatches(values []*model.Deployment, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deploymentDo) Save(values ...*model.Deployment) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deploymentDo) First() (*model.Deployment, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Deployment), nil
	}
}

func (d deploymentDo) Take() (*model.Deployment, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Deployment), nil
	}
}

func (d deploymentDo) Last() (*model.Deployment, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Deployment), nil
	}
}

func (d deploymentDo) Find() ([]*model.Deployment, error) {
	result, err := d.DO.Find()
	return result.([]*model.Deployment), err
}

func (d deploymentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Deployment, err error) {
	buf := make([]*model.Deployment, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deploymentDo) FindInBatches(result *[]*model.Deployment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deploymentDo) Attrs(attrs ...field.AssignExpr) IDeploymentDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deploymentDo) Assign(attrs ...field.AssignExpr) IDeploymentDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deploymentDo) Joins(fields ...field.RelationField) IDeploymentDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deploymentDo) Preload(fields ...field.RelationField) IDeploymentDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deploymentDo) FirstOrInit() (*model.Deployment, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Deployment), nil
	}
}

func (d deploymentDo) FirstOrCreate() (*model.Deployment, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Deployment), nil
	}
}

func (d deploymentDo) FindByPage(offset int, limit int) (result []*model.Deployment, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deploymentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deploymentDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deploymentDo) Delete(models ...*model.Deployment) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deploymentDo) withDO(do gen.Dao) *deploymentDo {
	d.DO = *do.(*gen.DO)
	return d
}
