// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                             = new(Query)
	APIKey                        *aPIKey
	App                           *app
	AppStarred                    *appStarred
	AppUser                       *appUser
	AuditLog                      *auditLog
	Config                        *config
	ConfigMap                     *configMap
	ConfigMapTemplate             *configMapTemplate
	Cronjob                       *cronjob
	CronjobTemplate               *cronjobTemplate
	DaemonSet                     *daemonSet
	DaemonSetTemplate             *daemonSetTemplate
	Deployment                    *deployment
	DeploymentTemplate            *deploymentTemplate
	Group                         *group
	GroupPermission               *groupPermission
	Hpa                           *hpa
	HpaTemplate                   *hpaTemplate
	Ingress                       *ingress
	IngressTemplate               *ingressTemplate
	Namespace                     *namespace
	NamespaceUser                 *namespaceUser
	Permission                    *permission
	PersistentVolumeClaim         *persistentVolumeClaim
	PersistentVolumeClaimTemplate *persistentVolumeClaimTemplate
	PublishHistory                *publishHistory
	PublishStatus                 *publishStatus
	Secret                        *secret
	SecretTemplate                *secretTemplate
	Service                       *service
	ServiceTemplate               *serviceTemplate
	Statefulset                   *statefulset
	StatefulsetTemplate           *statefulsetTemplate
	User                          *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	APIKey = &Q.APIKey
	App = &Q.App
	AppStarred = &Q.AppStarred
	AppUser = &Q.AppUser
	AuditLog = &Q.AuditLog
	Config = &Q.Config
	ConfigMap = &Q.ConfigMap
	ConfigMapTemplate = &Q.ConfigMapTemplate
	Cronjob = &Q.Cronjob
	CronjobTemplate = &Q.CronjobTemplate
	DaemonSet = &Q.DaemonSet
	DaemonSetTemplate = &Q.DaemonSetTemplate
	Deployment = &Q.Deployment
	DeploymentTemplate = &Q.DeploymentTemplate
	Group = &Q.Group
	GroupPermission = &Q.GroupPermission
	Hpa = &Q.Hpa
	HpaTemplate = &Q.HpaTemplate
	Ingress = &Q.Ingress
	IngressTemplate = &Q.IngressTemplate
	Namespace = &Q.Namespace
	NamespaceUser = &Q.NamespaceUser
	Permission = &Q.Permission
	PersistentVolumeClaim = &Q.PersistentVolumeClaim
	PersistentVolumeClaimTemplate = &Q.PersistentVolumeClaimTemplate
	PublishHistory = &Q.PublishHistory
	PublishStatus = &Q.PublishStatus
	Secret = &Q.Secret
	SecretTemplate = &Q.SecretTemplate
	Service = &Q.Service
	ServiceTemplate = &Q.ServiceTemplate
	Statefulset = &Q.Statefulset
	StatefulsetTemplate = &Q.StatefulsetTemplate
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                            db,
		APIKey:                        newAPIKey(db, opts...),
		App:                           newApp(db, opts...),
		AppStarred:                    newAppStarred(db, opts...),
		AppUser:                       newAppUser(db, opts...),
		AuditLog:                      newAuditLog(db, opts...),
		Config:                        newConfig(db, opts...),
		ConfigMap:                     newConfigMap(db, opts...),
		ConfigMapTemplate:             newConfigMapTemplate(db, opts...),
		Cronjob:                       newCronjob(db, opts...),
		CronjobTemplate:               newCronjobTemplate(db, opts...),
		DaemonSet:                     newDaemonSet(db, opts...),
		DaemonSetTemplate:             newDaemonSetTemplate(db, opts...),
		Deployment:                    newDeployment(db, opts...),
		DeploymentTemplate:            newDeploymentTemplate(db, opts...),
		Group:                         newGroup(db, opts...),
		GroupPermission:               newGroupPermission(db, opts...),
		Hpa:                           newHpa(db, opts...),
		HpaTemplate:                   newHpaTemplate(db, opts...),
		Ingress:                       newIngress(db, opts...),
		IngressTemplate:               newIngressTemplate(db, opts...),
		Namespace:                     newNamespace(db, opts...),
		NamespaceUser:                 newNamespaceUser(db, opts...),
		Permission:                    newPermission(db, opts...),
		PersistentVolumeClaim:         newPersistentVolumeClaim(db, opts...),
		PersistentVolumeClaimTemplate: newPersistentVolumeClaimTemplate(db, opts...),
		PublishHistory:                newPublishHistory(db, opts...),
		PublishStatus:                 newPublishStatus(db, opts...),
		Secret:                        newSecret(db, opts...),
		SecretTemplate:                newSecretTemplate(db, opts...),
		Service:                       newService(db, opts...),
		ServiceTemplate:               newServiceTemplate(db, opts...),
		Statefulset:                   newStatefulset(db, opts...),
		StatefulsetTemplate:           newStatefulsetTemplate(db, opts...),
		User:                          newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	APIKey                        aPIKey
	App                           app
	AppStarred                    appStarred
	AppUser                       appUser
	AuditLog                      auditLog
	Config                        config
	ConfigMap                     configMap
	ConfigMapTemplate             configMapTemplate
	Cronjob                       cronjob
	CronjobTemplate               cronjobTemplate
	DaemonSet                     daemonSet
	DaemonSetTemplate             daemonSetTemplate
	Deployment                    deployment
	DeploymentTemplate            deploymentTemplate
	Group                         group
	GroupPermission               groupPermission
	Hpa                           hpa
	HpaTemplate                   hpaTemplate
	Ingress                       ingress
	IngressTemplate               ingressTemplate
	Namespace                     namespace
	NamespaceUser                 namespaceUser
	Permission                    permission
	PersistentVolumeClaim         persistentVolumeClaim
	PersistentVolumeClaimTemplate persistentVolumeClaimTemplate
	PublishHistory                publishHistory
	PublishStatus                 publishStatus
	Secret                        secret
	SecretTemplate                secretTemplate
	Service                       service
	ServiceTemplate               serviceTemplate
	Statefulset                   statefulset
	StatefulsetTemplate           statefulsetTemplate
	User                          user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                            db,
		APIKey:                        q.APIKey.clone(db),
		App:                           q.App.clone(db),
		AppStarred:                    q.AppStarred.clone(db),
		AppUser:                       q.AppUser.clone(db),
		AuditLog:                      q.AuditLog.clone(db),
		Config:                        q.Config.clone(db),
		ConfigMap:                     q.ConfigMap.clone(db),
		ConfigMapTemplate:             q.ConfigMapTemplate.clone(db),
		Cronjob:                       q.Cronjob.clone(db),
		CronjobTemplate:               q.CronjobTemplate.clone(db),
		DaemonSet:                     q.DaemonSet.clone(db),
		DaemonSetTemplate:             q.DaemonSetTemplate.clone(db),
		Deployment:                    q.Deployment.clone(db),
		DeploymentTemplate:            q.DeploymentTemplate.clone(db),
		Group:                         q.Group.clone(db),
		GroupPermission:               q.GroupPermission.clone(db),
		Hpa:                           q.Hpa.clone(db),
		HpaTemplate:                   q.HpaTemplate.clone(db),
		Ingress:                       q.Ingress.clone(db),
		IngressTemplate:               q.IngressTemplate.clone(db),
		Namespace:                     q.Namespace.clone(db),
		NamespaceUser:                 q.NamespaceUser.clone(db),
		Permission:                    q.Permission.clone(db),
		PersistentVolumeClaim:         q.PersistentVolumeClaim.clone(db),
		PersistentVolumeClaimTemplate: q.PersistentVolumeClaimTemplate.clone(db),
		PublishHistory:                q.PublishHistory.clone(db),
		PublishStatus:                 q.PublishStatus.clone(db),
		Secret:                        q.Secret.clone(db),
		SecretTemplate:                q.SecretTemplate.clone(db),
		Service:                       q.Service.clone(db),
		ServiceTemplate:               q.ServiceTemplate.clone(db),
		Statefulset:                   q.Statefulset.clone(db),
		StatefulsetTemplate:           q.StatefulsetTemplate.clone(db),
		User:                          q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                            db,
		APIKey:                        q.APIKey.replaceDB(db),
		App:                           q.App.replaceDB(db),
		AppStarred:                    q.AppStarred.replaceDB(db),
		AppUser:                       q.AppUser.replaceDB(db),
		AuditLog:                      q.AuditLog.replaceDB(db),
		Config:                        q.Config.replaceDB(db),
		ConfigMap:                     q.ConfigMap.replaceDB(db),
		ConfigMapTemplate:             q.ConfigMapTemplate.replaceDB(db),
		Cronjob:                       q.Cronjob.replaceDB(db),
		CronjobTemplate:               q.CronjobTemplate.replaceDB(db),
		DaemonSet:                     q.DaemonSet.replaceDB(db),
		DaemonSetTemplate:             q.DaemonSetTemplate.replaceDB(db),
		Deployment:                    q.Deployment.replaceDB(db),
		DeploymentTemplate:            q.DeploymentTemplate.replaceDB(db),
		Group:                         q.Group.replaceDB(db),
		GroupPermission:               q.GroupPermission.replaceDB(db),
		Hpa:                           q.Hpa.replaceDB(db),
		HpaTemplate:                   q.HpaTemplate.replaceDB(db),
		Ingress:                       q.Ingress.replaceDB(db),
		IngressTemplate:               q.IngressTemplate.replaceDB(db),
		Namespace:                     q.Namespace.replaceDB(db),
		NamespaceUser:                 q.NamespaceUser.replaceDB(db),
		Permission:                    q.Permission.replaceDB(db),
		PersistentVolumeClaim:         q.PersistentVolumeClaim.replaceDB(db),
		PersistentVolumeClaimTemplate: q.PersistentVolumeClaimTemplate.replaceDB(db),
		PublishHistory:                q.PublishHistory.replaceDB(db),
		PublishStatus:                 q.PublishStatus.replaceDB(db),
		Secret:                        q.Secret.replaceDB(db),
		SecretTemplate:                q.SecretTemplate.replaceDB(db),
		Service:                       q.Service.replaceDB(db),
		ServiceTemplate:               q.ServiceTemplate.replaceDB(db),
		Statefulset:                   q.Statefulset.replaceDB(db),
		StatefulsetTemplate:           q.StatefulsetTemplate.replaceDB(db),
		User:                          q.User.replaceDB(db),
	}
}

type queryCtx struct {
	APIKey                        IAPIKeyDo
	App                           IAppDo
	AppStarred                    IAppStarredDo
	AppUser                       IAppUserDo
	AuditLog                      IAuditLogDo
	Config                        IConfigDo
	ConfigMap                     IConfigMapDo
	ConfigMapTemplate             IConfigMapTemplateDo
	Cronjob                       ICronjobDo
	CronjobTemplate               ICronjobTemplateDo
	DaemonSet                     IDaemonSetDo
	DaemonSetTemplate             IDaemonSetTemplateDo
	Deployment                    IDeploymentDo
	DeploymentTemplate            IDeploymentTemplateDo
	Group                         IGroupDo
	GroupPermission               IGroupPermissionDo
	Hpa                           IHpaDo
	HpaTemplate                   IHpaTemplateDo
	Ingress                       IIngressDo
	IngressTemplate               IIngressTemplateDo
	Namespace                     INamespaceDo
	NamespaceUser                 INamespaceUserDo
	Permission                    IPermissionDo
	PersistentVolumeClaim         IPersistentVolumeClaimDo
	PersistentVolumeClaimTemplate IPersistentVolumeClaimTemplateDo
	PublishHistory                IPublishHistoryDo
	PublishStatus                 IPublishStatusDo
	Secret                        ISecretDo
	SecretTemplate                ISecretTemplateDo
	Service                       IServiceDo
	ServiceTemplate               IServiceTemplateDo
	Statefulset                   IStatefulsetDo
	StatefulsetTemplate           IStatefulsetTemplateDo
	User                          IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		APIKey:                        q.APIKey.WithContext(ctx),
		App:                           q.App.WithContext(ctx),
		AppStarred:                    q.AppStarred.WithContext(ctx),
		AppUser:                       q.AppUser.WithContext(ctx),
		AuditLog:                      q.AuditLog.WithContext(ctx),
		Config:                        q.Config.WithContext(ctx),
		ConfigMap:                     q.ConfigMap.WithContext(ctx),
		ConfigMapTemplate:             q.ConfigMapTemplate.WithContext(ctx),
		Cronjob:                       q.Cronjob.WithContext(ctx),
		CronjobTemplate:               q.CronjobTemplate.WithContext(ctx),
		DaemonSet:                     q.DaemonSet.WithContext(ctx),
		DaemonSetTemplate:             q.DaemonSetTemplate.WithContext(ctx),
		Deployment:                    q.Deployment.WithContext(ctx),
		DeploymentTemplate:            q.DeploymentTemplate.WithContext(ctx),
		Group:                         q.Group.WithContext(ctx),
		GroupPermission:               q.GroupPermission.WithContext(ctx),
		Hpa:                           q.Hpa.WithContext(ctx),
		HpaTemplate:                   q.HpaTemplate.WithContext(ctx),
		Ingress:                       q.Ingress.WithContext(ctx),
		IngressTemplate:               q.IngressTemplate.WithContext(ctx),
		Namespace:                     q.Namespace.WithContext(ctx),
		NamespaceUser:                 q.NamespaceUser.WithContext(ctx),
		Permission:                    q.Permission.WithContext(ctx),
		PersistentVolumeClaim:         q.PersistentVolumeClaim.WithContext(ctx),
		PersistentVolumeClaimTemplate: q.PersistentVolumeClaimTemplate.WithContext(ctx),
		PublishHistory:                q.PublishHistory.WithContext(ctx),
		PublishStatus:                 q.PublishStatus.WithContext(ctx),
		Secret:                        q.Secret.WithContext(ctx),
		SecretTemplate:                q.SecretTemplate.WithContext(ctx),
		Service:                       q.Service.WithContext(ctx),
		ServiceTemplate:               q.ServiceTemplate.WithContext(ctx),
		Statefulset:                   q.Statefulset.WithContext(ctx),
		StatefulsetTemplate:           q.StatefulsetTemplate.WithContext(ctx),
		User:                          q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
