// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newGroupPermission(db *gorm.DB, opts ...gen.DOOption) groupPermission {
	_groupPermission := groupPermission{}

	_groupPermission.groupPermissionDo.UseDB(db, opts...)
	_groupPermission.groupPermissionDo.UseModel(&model.GroupPermission{})

	tableName := _groupPermission.groupPermissionDo.TableName()
	_groupPermission.ALL = field.NewAsterisk(tableName)
	_groupPermission.ID = field.NewInt64(tableName, "id")
	_groupPermission.GroupID = field.NewInt64(tableName, "group_id")
	_groupPermission.PermissionID = field.NewInt64(tableName, "permission_id")

	_groupPermission.fillFieldMap()

	return _groupPermission
}

type groupPermission struct {
	groupPermissionDo

	ALL          field.Asterisk
	ID           field.Int64
	GroupID      field.Int64
	PermissionID field.Int64

	fieldMap map[string]field.Expr
}

func (g groupPermission) Table(newTableName string) *groupPermission {
	g.groupPermissionDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g groupPermission) As(alias string) *groupPermission {
	g.groupPermissionDo.DO = *(g.groupPermissionDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *groupPermission) updateTableName(table string) *groupPermission {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.GroupID = field.NewInt64(table, "group_id")
	g.PermissionID = field.NewInt64(table, "permission_id")

	g.fillFieldMap()

	return g
}

func (g *groupPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *groupPermission) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 3)
	g.fieldMap["id"] = g.ID
	g.fieldMap["group_id"] = g.GroupID
	g.fieldMap["permission_id"] = g.PermissionID
}

func (g groupPermission) clone(db *gorm.DB) groupPermission {
	g.groupPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g groupPermission) replaceDB(db *gorm.DB) groupPermission {
	g.groupPermissionDo.ReplaceDB(db)
	return g
}

type groupPermissionDo struct{ gen.DO }

type IGroupPermissionDo interface {
	gen.SubQuery
	Debug() IGroupPermissionDo
	WithContext(ctx context.Context) IGroupPermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGroupPermissionDo
	WriteDB() IGroupPermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGroupPermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGroupPermissionDo
	Not(conds ...gen.Condition) IGroupPermissionDo
	Or(conds ...gen.Condition) IGroupPermissionDo
	Select(conds ...field.Expr) IGroupPermissionDo
	Where(conds ...gen.Condition) IGroupPermissionDo
	Order(conds ...field.Expr) IGroupPermissionDo
	Distinct(cols ...field.Expr) IGroupPermissionDo
	Omit(cols ...field.Expr) IGroupPermissionDo
	Join(table schema.Tabler, on ...field.Expr) IGroupPermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGroupPermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGroupPermissionDo
	Group(cols ...field.Expr) IGroupPermissionDo
	Having(conds ...gen.Condition) IGroupPermissionDo
	Limit(limit int) IGroupPermissionDo
	Offset(offset int) IGroupPermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupPermissionDo
	Unscoped() IGroupPermissionDo
	Create(values ...*model.GroupPermission) error
	CreateInBatches(values []*model.GroupPermission, batchSize int) error
	Save(values ...*model.GroupPermission) error
	First() (*model.GroupPermission, error)
	Take() (*model.GroupPermission, error)
	Last() (*model.GroupPermission, error)
	Find() ([]*model.GroupPermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GroupPermission, err error)
	FindInBatches(result *[]*model.GroupPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GroupPermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGroupPermissionDo
	Assign(attrs ...field.AssignExpr) IGroupPermissionDo
	Joins(fields ...field.RelationField) IGroupPermissionDo
	Preload(fields ...field.RelationField) IGroupPermissionDo
	FirstOrInit() (*model.GroupPermission, error)
	FirstOrCreate() (*model.GroupPermission, error)
	FindByPage(offset int, limit int) (result []*model.GroupPermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGroupPermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g groupPermissionDo) Debug() IGroupPermissionDo {
	return g.withDO(g.DO.Debug())
}

func (g groupPermissionDo) WithContext(ctx context.Context) IGroupPermissionDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g groupPermissionDo) ReadDB() IGroupPermissionDo {
	return g.Clauses(dbresolver.Read)
}

func (g groupPermissionDo) WriteDB() IGroupPermissionDo {
	return g.Clauses(dbresolver.Write)
}

func (g groupPermissionDo) Session(config *gorm.Session) IGroupPermissionDo {
	return g.withDO(g.DO.Session(config))
}

func (g groupPermissionDo) Clauses(conds ...clause.Expression) IGroupPermissionDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g groupPermissionDo) Returning(value interface{}, columns ...string) IGroupPermissionDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g groupPermissionDo) Not(conds ...gen.Condition) IGroupPermissionDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g groupPermissionDo) Or(conds ...gen.Condition) IGroupPermissionDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g groupPermissionDo) Select(conds ...field.Expr) IGroupPermissionDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g groupPermissionDo) Where(conds ...gen.Condition) IGroupPermissionDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g groupPermissionDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IGroupPermissionDo {
	return g.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (g groupPermissionDo) Order(conds ...field.Expr) IGroupPermissionDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g groupPermissionDo) Distinct(cols ...field.Expr) IGroupPermissionDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g groupPermissionDo) Omit(cols ...field.Expr) IGroupPermissionDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g groupPermissionDo) Join(table schema.Tabler, on ...field.Expr) IGroupPermissionDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g groupPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGroupPermissionDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g groupPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) IGroupPermissionDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g groupPermissionDo) Group(cols ...field.Expr) IGroupPermissionDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g groupPermissionDo) Having(conds ...gen.Condition) IGroupPermissionDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g groupPermissionDo) Limit(limit int) IGroupPermissionDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g groupPermissionDo) Offset(offset int) IGroupPermissionDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g groupPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupPermissionDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g groupPermissionDo) Unscoped() IGroupPermissionDo {
	return g.withDO(g.DO.Unscoped())
}

func (g groupPermissionDo) Create(values ...*model.GroupPermission) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g groupPermissionDo) CreateInBatches(values []*model.GroupPermission, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g groupPermissionDo) Save(values ...*model.GroupPermission) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g groupPermissionDo) First() (*model.GroupPermission, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupPermission), nil
	}
}

func (g groupPermissionDo) Take() (*model.GroupPermission, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupPermission), nil
	}
}

func (g groupPermissionDo) Last() (*model.GroupPermission, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupPermission), nil
	}
}

func (g groupPermissionDo) Find() ([]*model.GroupPermission, error) {
	result, err := g.DO.Find()
	return result.([]*model.GroupPermission), err
}

func (g groupPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GroupPermission, err error) {
	buf := make([]*model.GroupPermission, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g groupPermissionDo) FindInBatches(result *[]*model.GroupPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g groupPermissionDo) Attrs(attrs ...field.AssignExpr) IGroupPermissionDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g groupPermissionDo) Assign(attrs ...field.AssignExpr) IGroupPermissionDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g groupPermissionDo) Joins(fields ...field.RelationField) IGroupPermissionDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g groupPermissionDo) Preload(fields ...field.RelationField) IGroupPermissionDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g groupPermissionDo) FirstOrInit() (*model.GroupPermission, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupPermission), nil
	}
}

func (g groupPermissionDo) FirstOrCreate() (*model.GroupPermission, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupPermission), nil
	}
}

func (g groupPermissionDo) FindByPage(offset int, limit int) (result []*model.GroupPermission, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g groupPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g groupPermissionDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g groupPermissionDo) Delete(models ...*model.GroupPermission) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *groupPermissionDo) withDO(do gen.Dao) *groupPermissionDo {
	g.DO = *do.(*gen.DO)
	return g
}
