// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newHpa(db *gorm.DB, opts ...gen.DOOption) hpa {
	_hpa := hpa{}

	_hpa.hpaDo.UseDB(db, opts...)
	_hpa.hpaDo.UseModel(&model.Hpa{})

	tableName := _hpa.hpaDo.TableName()
	_hpa.ALL = field.NewAsterisk(tableName)
	_hpa.ID = field.NewInt64(tableName, "id")
	_hpa.Name = field.NewString(tableName, "name")
	_hpa.MetaData = field.NewString(tableName, "meta_data")
	_hpa.AppID = field.NewInt64(tableName, "app_id")
	_hpa.Description = field.NewString(tableName, "description")
	_hpa.OrderID = field.NewInt64(tableName, "order_id")
	_hpa.CreateTime = field.NewTime(tableName, "create_time")
	_hpa.UpdateTime = field.NewTime(tableName, "update_time")
	_hpa.User = field.NewString(tableName, "user")
	_hpa.Deleted = field.NewBool(tableName, "deleted")

	_hpa.fillFieldMap()

	return _hpa
}

type hpa struct {
	hpaDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	MetaData    field.String
	AppID       field.Int64
	Description field.String
	OrderID     field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (h hpa) Table(newTableName string) *hpa {
	h.hpaDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hpa) As(alias string) *hpa {
	h.hpaDo.DO = *(h.hpaDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hpa) updateTableName(table string) *hpa {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.Name = field.NewString(table, "name")
	h.MetaData = field.NewString(table, "meta_data")
	h.AppID = field.NewInt64(table, "app_id")
	h.Description = field.NewString(table, "description")
	h.OrderID = field.NewInt64(table, "order_id")
	h.CreateTime = field.NewTime(table, "create_time")
	h.UpdateTime = field.NewTime(table, "update_time")
	h.User = field.NewString(table, "user")
	h.Deleted = field.NewBool(table, "deleted")

	h.fillFieldMap()

	return h
}

func (h *hpa) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hpa) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 10)
	h.fieldMap["id"] = h.ID
	h.fieldMap["name"] = h.Name
	h.fieldMap["meta_data"] = h.MetaData
	h.fieldMap["app_id"] = h.AppID
	h.fieldMap["description"] = h.Description
	h.fieldMap["order_id"] = h.OrderID
	h.fieldMap["create_time"] = h.CreateTime
	h.fieldMap["update_time"] = h.UpdateTime
	h.fieldMap["user"] = h.User
	h.fieldMap["deleted"] = h.Deleted
}

func (h hpa) clone(db *gorm.DB) hpa {
	h.hpaDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hpa) replaceDB(db *gorm.DB) hpa {
	h.hpaDo.ReplaceDB(db)
	return h
}

type hpaDo struct{ gen.DO }

type IHpaDo interface {
	gen.SubQuery
	Debug() IHpaDo
	WithContext(ctx context.Context) IHpaDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHpaDo
	WriteDB() IHpaDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHpaDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHpaDo
	Not(conds ...gen.Condition) IHpaDo
	Or(conds ...gen.Condition) IHpaDo
	Select(conds ...field.Expr) IHpaDo
	Where(conds ...gen.Condition) IHpaDo
	Order(conds ...field.Expr) IHpaDo
	Distinct(cols ...field.Expr) IHpaDo
	Omit(cols ...field.Expr) IHpaDo
	Join(table schema.Tabler, on ...field.Expr) IHpaDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHpaDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHpaDo
	Group(cols ...field.Expr) IHpaDo
	Having(conds ...gen.Condition) IHpaDo
	Limit(limit int) IHpaDo
	Offset(offset int) IHpaDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHpaDo
	Unscoped() IHpaDo
	Create(values ...*model.Hpa) error
	CreateInBatches(values []*model.Hpa, batchSize int) error
	Save(values ...*model.Hpa) error
	First() (*model.Hpa, error)
	Take() (*model.Hpa, error)
	Last() (*model.Hpa, error)
	Find() ([]*model.Hpa, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Hpa, err error)
	FindInBatches(result *[]*model.Hpa, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Hpa) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHpaDo
	Assign(attrs ...field.AssignExpr) IHpaDo
	Joins(fields ...field.RelationField) IHpaDo
	Preload(fields ...field.RelationField) IHpaDo
	FirstOrInit() (*model.Hpa, error)
	FirstOrCreate() (*model.Hpa, error)
	FindByPage(offset int, limit int) (result []*model.Hpa, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHpaDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hpaDo) Debug() IHpaDo {
	return h.withDO(h.DO.Debug())
}

func (h hpaDo) WithContext(ctx context.Context) IHpaDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hpaDo) ReadDB() IHpaDo {
	return h.Clauses(dbresolver.Read)
}

func (h hpaDo) WriteDB() IHpaDo {
	return h.Clauses(dbresolver.Write)
}

func (h hpaDo) Session(config *gorm.Session) IHpaDo {
	return h.withDO(h.DO.Session(config))
}

func (h hpaDo) Clauses(conds ...clause.Expression) IHpaDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hpaDo) Returning(value interface{}, columns ...string) IHpaDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hpaDo) Not(conds ...gen.Condition) IHpaDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hpaDo) Or(conds ...gen.Condition) IHpaDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hpaDo) Select(conds ...field.Expr) IHpaDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hpaDo) Where(conds ...gen.Condition) IHpaDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hpaDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IHpaDo {
	return h.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (h hpaDo) Order(conds ...field.Expr) IHpaDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hpaDo) Distinct(cols ...field.Expr) IHpaDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hpaDo) Omit(cols ...field.Expr) IHpaDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hpaDo) Join(table schema.Tabler, on ...field.Expr) IHpaDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hpaDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHpaDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hpaDo) RightJoin(table schema.Tabler, on ...field.Expr) IHpaDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hpaDo) Group(cols ...field.Expr) IHpaDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hpaDo) Having(conds ...gen.Condition) IHpaDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hpaDo) Limit(limit int) IHpaDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hpaDo) Offset(offset int) IHpaDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hpaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHpaDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hpaDo) Unscoped() IHpaDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hpaDo) Create(values ...*model.Hpa) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hpaDo) CreateInBatches(values []*model.Hpa, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hpaDo) Save(values ...*model.Hpa) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hpaDo) First() (*model.Hpa, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Hpa), nil
	}
}

func (h hpaDo) Take() (*model.Hpa, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Hpa), nil
	}
}

func (h hpaDo) Last() (*model.Hpa, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Hpa), nil
	}
}

func (h hpaDo) Find() ([]*model.Hpa, error) {
	result, err := h.DO.Find()
	return result.([]*model.Hpa), err
}

func (h hpaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Hpa, err error) {
	buf := make([]*model.Hpa, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hpaDo) FindInBatches(result *[]*model.Hpa, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hpaDo) Attrs(attrs ...field.AssignExpr) IHpaDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hpaDo) Assign(attrs ...field.AssignExpr) IHpaDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hpaDo) Joins(fields ...field.RelationField) IHpaDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hpaDo) Preload(fields ...field.RelationField) IHpaDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hpaDo) FirstOrInit() (*model.Hpa, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Hpa), nil
	}
}

func (h hpaDo) FirstOrCreate() (*model.Hpa, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Hpa), nil
	}
}

func (h hpaDo) FindByPage(offset int, limit int) (result []*model.Hpa, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hpaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hpaDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hpaDo) Delete(models ...*model.Hpa) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hpaDo) withDO(do gen.Dao) *hpaDo {
	h.DO = *do.(*gen.DO)
	return h
}
