// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newHpaTemplate(db *gorm.DB, opts ...gen.DOOption) hpaTemplate {
	_hpaTemplate := hpaTemplate{}

	_hpaTemplate.hpaTemplateDo.UseDB(db, opts...)
	_hpaTemplate.hpaTemplateDo.UseModel(&model.HpaTemplate{})

	tableName := _hpaTemplate.hpaTemplateDo.TableName()
	_hpaTemplate.ALL = field.NewAsterisk(tableName)
	_hpaTemplate.ID = field.NewInt64(tableName, "id")
	_hpaTemplate.Name = field.NewString(tableName, "name")
	_hpaTemplate.Template = field.NewString(tableName, "template")
	_hpaTemplate.HpaID = field.NewInt64(tableName, "hpa_id")
	_hpaTemplate.Description = field.NewString(tableName, "description")
	_hpaTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_hpaTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_hpaTemplate.User = field.NewString(tableName, "user")
	_hpaTemplate.Deleted = field.NewBool(tableName, "deleted")

	_hpaTemplate.fillFieldMap()

	return _hpaTemplate
}

type hpaTemplate struct {
	hpaTemplateDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Template    field.String
	HpaID       field.Int64
	Description field.String
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (h hpaTemplate) Table(newTableName string) *hpaTemplate {
	h.hpaTemplateDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hpaTemplate) As(alias string) *hpaTemplate {
	h.hpaTemplateDo.DO = *(h.hpaTemplateDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hpaTemplate) updateTableName(table string) *hpaTemplate {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.Name = field.NewString(table, "name")
	h.Template = field.NewString(table, "template")
	h.HpaID = field.NewInt64(table, "hpa_id")
	h.Description = field.NewString(table, "description")
	h.CreateTime = field.NewTime(table, "create_time")
	h.UpdateTime = field.NewTime(table, "update_time")
	h.User = field.NewString(table, "user")
	h.Deleted = field.NewBool(table, "deleted")

	h.fillFieldMap()

	return h
}

func (h *hpaTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hpaTemplate) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 9)
	h.fieldMap["id"] = h.ID
	h.fieldMap["name"] = h.Name
	h.fieldMap["template"] = h.Template
	h.fieldMap["hpa_id"] = h.HpaID
	h.fieldMap["description"] = h.Description
	h.fieldMap["create_time"] = h.CreateTime
	h.fieldMap["update_time"] = h.UpdateTime
	h.fieldMap["user"] = h.User
	h.fieldMap["deleted"] = h.Deleted
}

func (h hpaTemplate) clone(db *gorm.DB) hpaTemplate {
	h.hpaTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hpaTemplate) replaceDB(db *gorm.DB) hpaTemplate {
	h.hpaTemplateDo.ReplaceDB(db)
	return h
}

type hpaTemplateDo struct{ gen.DO }

type IHpaTemplateDo interface {
	gen.SubQuery
	Debug() IHpaTemplateDo
	WithContext(ctx context.Context) IHpaTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHpaTemplateDo
	WriteDB() IHpaTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHpaTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHpaTemplateDo
	Not(conds ...gen.Condition) IHpaTemplateDo
	Or(conds ...gen.Condition) IHpaTemplateDo
	Select(conds ...field.Expr) IHpaTemplateDo
	Where(conds ...gen.Condition) IHpaTemplateDo
	Order(conds ...field.Expr) IHpaTemplateDo
	Distinct(cols ...field.Expr) IHpaTemplateDo
	Omit(cols ...field.Expr) IHpaTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IHpaTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHpaTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHpaTemplateDo
	Group(cols ...field.Expr) IHpaTemplateDo
	Having(conds ...gen.Condition) IHpaTemplateDo
	Limit(limit int) IHpaTemplateDo
	Offset(offset int) IHpaTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHpaTemplateDo
	Unscoped() IHpaTemplateDo
	Create(values ...*model.HpaTemplate) error
	CreateInBatches(values []*model.HpaTemplate, batchSize int) error
	Save(values ...*model.HpaTemplate) error
	First() (*model.HpaTemplate, error)
	Take() (*model.HpaTemplate, error)
	Last() (*model.HpaTemplate, error)
	Find() ([]*model.HpaTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HpaTemplate, err error)
	FindInBatches(result *[]*model.HpaTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HpaTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHpaTemplateDo
	Assign(attrs ...field.AssignExpr) IHpaTemplateDo
	Joins(fields ...field.RelationField) IHpaTemplateDo
	Preload(fields ...field.RelationField) IHpaTemplateDo
	FirstOrInit() (*model.HpaTemplate, error)
	FirstOrCreate() (*model.HpaTemplate, error)
	FindByPage(offset int, limit int) (result []*model.HpaTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHpaTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hpaTemplateDo) Debug() IHpaTemplateDo {
	return h.withDO(h.DO.Debug())
}

func (h hpaTemplateDo) WithContext(ctx context.Context) IHpaTemplateDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hpaTemplateDo) ReadDB() IHpaTemplateDo {
	return h.Clauses(dbresolver.Read)
}

func (h hpaTemplateDo) WriteDB() IHpaTemplateDo {
	return h.Clauses(dbresolver.Write)
}

func (h hpaTemplateDo) Session(config *gorm.Session) IHpaTemplateDo {
	return h.withDO(h.DO.Session(config))
}

func (h hpaTemplateDo) Clauses(conds ...clause.Expression) IHpaTemplateDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hpaTemplateDo) Returning(value interface{}, columns ...string) IHpaTemplateDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hpaTemplateDo) Not(conds ...gen.Condition) IHpaTemplateDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hpaTemplateDo) Or(conds ...gen.Condition) IHpaTemplateDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hpaTemplateDo) Select(conds ...field.Expr) IHpaTemplateDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hpaTemplateDo) Where(conds ...gen.Condition) IHpaTemplateDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hpaTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IHpaTemplateDo {
	return h.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (h hpaTemplateDo) Order(conds ...field.Expr) IHpaTemplateDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hpaTemplateDo) Distinct(cols ...field.Expr) IHpaTemplateDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hpaTemplateDo) Omit(cols ...field.Expr) IHpaTemplateDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hpaTemplateDo) Join(table schema.Tabler, on ...field.Expr) IHpaTemplateDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hpaTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHpaTemplateDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hpaTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IHpaTemplateDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hpaTemplateDo) Group(cols ...field.Expr) IHpaTemplateDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hpaTemplateDo) Having(conds ...gen.Condition) IHpaTemplateDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hpaTemplateDo) Limit(limit int) IHpaTemplateDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hpaTemplateDo) Offset(offset int) IHpaTemplateDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hpaTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHpaTemplateDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hpaTemplateDo) Unscoped() IHpaTemplateDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hpaTemplateDo) Create(values ...*model.HpaTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hpaTemplateDo) CreateInBatches(values []*model.HpaTemplate, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hpaTemplateDo) Save(values ...*model.HpaTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hpaTemplateDo) First() (*model.HpaTemplate, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HpaTemplate), nil
	}
}

func (h hpaTemplateDo) Take() (*model.HpaTemplate, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HpaTemplate), nil
	}
}

func (h hpaTemplateDo) Last() (*model.HpaTemplate, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HpaTemplate), nil
	}
}

func (h hpaTemplateDo) Find() ([]*model.HpaTemplate, error) {
	result, err := h.DO.Find()
	return result.([]*model.HpaTemplate), err
}

func (h hpaTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HpaTemplate, err error) {
	buf := make([]*model.HpaTemplate, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hpaTemplateDo) FindInBatches(result *[]*model.HpaTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hpaTemplateDo) Attrs(attrs ...field.AssignExpr) IHpaTemplateDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hpaTemplateDo) Assign(attrs ...field.AssignExpr) IHpaTemplateDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hpaTemplateDo) Joins(fields ...field.RelationField) IHpaTemplateDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hpaTemplateDo) Preload(fields ...field.RelationField) IHpaTemplateDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hpaTemplateDo) FirstOrInit() (*model.HpaTemplate, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HpaTemplate), nil
	}
}

func (h hpaTemplateDo) FirstOrCreate() (*model.HpaTemplate, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HpaTemplate), nil
	}
}

func (h hpaTemplateDo) FindByPage(offset int, limit int) (result []*model.HpaTemplate, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hpaTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hpaTemplateDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hpaTemplateDo) Delete(models ...*model.HpaTemplate) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hpaTemplateDo) withDO(do gen.Dao) *hpaTemplateDo {
	h.DO = *do.(*gen.DO)
	return h
}
