// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newIngressTemplate(db *gorm.DB, opts ...gen.DOOption) ingressTemplate {
	_ingressTemplate := ingressTemplate{}

	_ingressTemplate.ingressTemplateDo.UseDB(db, opts...)
	_ingressTemplate.ingressTemplateDo.UseModel(&model.IngressTemplate{})

	tableName := _ingressTemplate.ingressTemplateDo.TableName()
	_ingressTemplate.ALL = field.NewAsterisk(tableName)
	_ingressTemplate.ID = field.NewInt64(tableName, "id")
	_ingressTemplate.Name = field.NewString(tableName, "name")
	_ingressTemplate.Template = field.NewString(tableName, "template")
	_ingressTemplate.IngressID = field.NewInt64(tableName, "ingress_id")
	_ingressTemplate.Description = field.NewString(tableName, "description")
	_ingressTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_ingressTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_ingressTemplate.User = field.NewString(tableName, "user")
	_ingressTemplate.Deleted = field.NewBool(tableName, "deleted")

	_ingressTemplate.fillFieldMap()

	return _ingressTemplate
}

type ingressTemplate struct {
	ingressTemplateDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Template    field.String
	IngressID   field.Int64
	Description field.String
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (i ingressTemplate) Table(newTableName string) *ingressTemplate {
	i.ingressTemplateDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i ingressTemplate) As(alias string) *ingressTemplate {
	i.ingressTemplateDo.DO = *(i.ingressTemplateDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *ingressTemplate) updateTableName(table string) *ingressTemplate {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.Name = field.NewString(table, "name")
	i.Template = field.NewString(table, "template")
	i.IngressID = field.NewInt64(table, "ingress_id")
	i.Description = field.NewString(table, "description")
	i.CreateTime = field.NewTime(table, "create_time")
	i.UpdateTime = field.NewTime(table, "update_time")
	i.User = field.NewString(table, "user")
	i.Deleted = field.NewBool(table, "deleted")

	i.fillFieldMap()

	return i
}

func (i *ingressTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *ingressTemplate) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 9)
	i.fieldMap["id"] = i.ID
	i.fieldMap["name"] = i.Name
	i.fieldMap["template"] = i.Template
	i.fieldMap["ingress_id"] = i.IngressID
	i.fieldMap["description"] = i.Description
	i.fieldMap["create_time"] = i.CreateTime
	i.fieldMap["update_time"] = i.UpdateTime
	i.fieldMap["user"] = i.User
	i.fieldMap["deleted"] = i.Deleted
}

func (i ingressTemplate) clone(db *gorm.DB) ingressTemplate {
	i.ingressTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i ingressTemplate) replaceDB(db *gorm.DB) ingressTemplate {
	i.ingressTemplateDo.ReplaceDB(db)
	return i
}

type ingressTemplateDo struct{ gen.DO }

type IIngressTemplateDo interface {
	gen.SubQuery
	Debug() IIngressTemplateDo
	WithContext(ctx context.Context) IIngressTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIngressTemplateDo
	WriteDB() IIngressTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIngressTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIngressTemplateDo
	Not(conds ...gen.Condition) IIngressTemplateDo
	Or(conds ...gen.Condition) IIngressTemplateDo
	Select(conds ...field.Expr) IIngressTemplateDo
	Where(conds ...gen.Condition) IIngressTemplateDo
	Order(conds ...field.Expr) IIngressTemplateDo
	Distinct(cols ...field.Expr) IIngressTemplateDo
	Omit(cols ...field.Expr) IIngressTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IIngressTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIngressTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIngressTemplateDo
	Group(cols ...field.Expr) IIngressTemplateDo
	Having(conds ...gen.Condition) IIngressTemplateDo
	Limit(limit int) IIngressTemplateDo
	Offset(offset int) IIngressTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIngressTemplateDo
	Unscoped() IIngressTemplateDo
	Create(values ...*model.IngressTemplate) error
	CreateInBatches(values []*model.IngressTemplate, batchSize int) error
	Save(values ...*model.IngressTemplate) error
	First() (*model.IngressTemplate, error)
	Take() (*model.IngressTemplate, error)
	Last() (*model.IngressTemplate, error)
	Find() ([]*model.IngressTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IngressTemplate, err error)
	FindInBatches(result *[]*model.IngressTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IngressTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIngressTemplateDo
	Assign(attrs ...field.AssignExpr) IIngressTemplateDo
	Joins(fields ...field.RelationField) IIngressTemplateDo
	Preload(fields ...field.RelationField) IIngressTemplateDo
	FirstOrInit() (*model.IngressTemplate, error)
	FirstOrCreate() (*model.IngressTemplate, error)
	FindByPage(offset int, limit int) (result []*model.IngressTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIngressTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i ingressTemplateDo) Debug() IIngressTemplateDo {
	return i.withDO(i.DO.Debug())
}

func (i ingressTemplateDo) WithContext(ctx context.Context) IIngressTemplateDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i ingressTemplateDo) ReadDB() IIngressTemplateDo {
	return i.Clauses(dbresolver.Read)
}

func (i ingressTemplateDo) WriteDB() IIngressTemplateDo {
	return i.Clauses(dbresolver.Write)
}

func (i ingressTemplateDo) Session(config *gorm.Session) IIngressTemplateDo {
	return i.withDO(i.DO.Session(config))
}

func (i ingressTemplateDo) Clauses(conds ...clause.Expression) IIngressTemplateDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i ingressTemplateDo) Returning(value interface{}, columns ...string) IIngressTemplateDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i ingressTemplateDo) Not(conds ...gen.Condition) IIngressTemplateDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i ingressTemplateDo) Or(conds ...gen.Condition) IIngressTemplateDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i ingressTemplateDo) Select(conds ...field.Expr) IIngressTemplateDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i ingressTemplateDo) Where(conds ...gen.Condition) IIngressTemplateDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i ingressTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IIngressTemplateDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i ingressTemplateDo) Order(conds ...field.Expr) IIngressTemplateDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i ingressTemplateDo) Distinct(cols ...field.Expr) IIngressTemplateDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i ingressTemplateDo) Omit(cols ...field.Expr) IIngressTemplateDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i ingressTemplateDo) Join(table schema.Tabler, on ...field.Expr) IIngressTemplateDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i ingressTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIngressTemplateDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i ingressTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IIngressTemplateDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i ingressTemplateDo) Group(cols ...field.Expr) IIngressTemplateDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i ingressTemplateDo) Having(conds ...gen.Condition) IIngressTemplateDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i ingressTemplateDo) Limit(limit int) IIngressTemplateDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i ingressTemplateDo) Offset(offset int) IIngressTemplateDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i ingressTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIngressTemplateDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i ingressTemplateDo) Unscoped() IIngressTemplateDo {
	return i.withDO(i.DO.Unscoped())
}

func (i ingressTemplateDo) Create(values ...*model.IngressTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i ingressTemplateDo) CreateInBatches(values []*model.IngressTemplate, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i ingressTemplateDo) Save(values ...*model.IngressTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i ingressTemplateDo) First() (*model.IngressTemplate, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IngressTemplate), nil
	}
}

func (i ingressTemplateDo) Take() (*model.IngressTemplate, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IngressTemplate), nil
	}
}

func (i ingressTemplateDo) Last() (*model.IngressTemplate, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IngressTemplate), nil
	}
}

func (i ingressTemplateDo) Find() ([]*model.IngressTemplate, error) {
	result, err := i.DO.Find()
	return result.([]*model.IngressTemplate), err
}

func (i ingressTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IngressTemplate, err error) {
	buf := make([]*model.IngressTemplate, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i ingressTemplateDo) FindInBatches(result *[]*model.IngressTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i ingressTemplateDo) Attrs(attrs ...field.AssignExpr) IIngressTemplateDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i ingressTemplateDo) Assign(attrs ...field.AssignExpr) IIngressTemplateDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i ingressTemplateDo) Joins(fields ...field.RelationField) IIngressTemplateDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i ingressTemplateDo) Preload(fields ...field.RelationField) IIngressTemplateDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i ingressTemplateDo) FirstOrInit() (*model.IngressTemplate, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IngressTemplate), nil
	}
}

func (i ingressTemplateDo) FirstOrCreate() (*model.IngressTemplate, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IngressTemplate), nil
	}
}

func (i ingressTemplateDo) FindByPage(offset int, limit int) (result []*model.IngressTemplate, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i ingressTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i ingressTemplateDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i ingressTemplateDo) Delete(models ...*model.IngressTemplate) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *ingressTemplateDo) withDO(do gen.Dao) *ingressTemplateDo {
	i.DO = *do.(*gen.DO)
	return i
}
