// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newIngress(db *gorm.DB, opts ...gen.DOOption) ingress {
	_ingress := ingress{}

	_ingress.ingressDo.UseDB(db, opts...)
	_ingress.ingressDo.UseModel(&model.Ingress{})

	tableName := _ingress.ingressDo.TableName()
	_ingress.ALL = field.NewAsterisk(tableName)
	_ingress.ID = field.NewInt64(tableName, "id")
	_ingress.Name = field.NewString(tableName, "name")
	_ingress.MetaData = field.NewString(tableName, "meta_data")
	_ingress.AppID = field.NewInt64(tableName, "app_id")
	_ingress.Description = field.NewString(tableName, "description")
	_ingress.OrderID = field.NewInt64(tableName, "order_id")
	_ingress.CreateTime = field.NewTime(tableName, "create_time")
	_ingress.UpdateTime = field.NewTime(tableName, "update_time")
	_ingress.User = field.NewString(tableName, "user")
	_ingress.Deleted = field.NewBool(tableName, "deleted")

	_ingress.fillFieldMap()

	return _ingress
}

type ingress struct {
	ingressDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	MetaData    field.String
	AppID       field.Int64
	Description field.String
	OrderID     field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (i ingress) Table(newTableName string) *ingress {
	i.ingressDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i ingress) As(alias string) *ingress {
	i.ingressDo.DO = *(i.ingressDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *ingress) updateTableName(table string) *ingress {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.Name = field.NewString(table, "name")
	i.MetaData = field.NewString(table, "meta_data")
	i.AppID = field.NewInt64(table, "app_id")
	i.Description = field.NewString(table, "description")
	i.OrderID = field.NewInt64(table, "order_id")
	i.CreateTime = field.NewTime(table, "create_time")
	i.UpdateTime = field.NewTime(table, "update_time")
	i.User = field.NewString(table, "user")
	i.Deleted = field.NewBool(table, "deleted")

	i.fillFieldMap()

	return i
}

func (i *ingress) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *ingress) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 10)
	i.fieldMap["id"] = i.ID
	i.fieldMap["name"] = i.Name
	i.fieldMap["meta_data"] = i.MetaData
	i.fieldMap["app_id"] = i.AppID
	i.fieldMap["description"] = i.Description
	i.fieldMap["order_id"] = i.OrderID
	i.fieldMap["create_time"] = i.CreateTime
	i.fieldMap["update_time"] = i.UpdateTime
	i.fieldMap["user"] = i.User
	i.fieldMap["deleted"] = i.Deleted
}

func (i ingress) clone(db *gorm.DB) ingress {
	i.ingressDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i ingress) replaceDB(db *gorm.DB) ingress {
	i.ingressDo.ReplaceDB(db)
	return i
}

type ingressDo struct{ gen.DO }

type IIngressDo interface {
	gen.SubQuery
	Debug() IIngressDo
	WithContext(ctx context.Context) IIngressDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIngressDo
	WriteDB() IIngressDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIngressDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIngressDo
	Not(conds ...gen.Condition) IIngressDo
	Or(conds ...gen.Condition) IIngressDo
	Select(conds ...field.Expr) IIngressDo
	Where(conds ...gen.Condition) IIngressDo
	Order(conds ...field.Expr) IIngressDo
	Distinct(cols ...field.Expr) IIngressDo
	Omit(cols ...field.Expr) IIngressDo
	Join(table schema.Tabler, on ...field.Expr) IIngressDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIngressDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIngressDo
	Group(cols ...field.Expr) IIngressDo
	Having(conds ...gen.Condition) IIngressDo
	Limit(limit int) IIngressDo
	Offset(offset int) IIngressDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIngressDo
	Unscoped() IIngressDo
	Create(values ...*model.Ingress) error
	CreateInBatches(values []*model.Ingress, batchSize int) error
	Save(values ...*model.Ingress) error
	First() (*model.Ingress, error)
	Take() (*model.Ingress, error)
	Last() (*model.Ingress, error)
	Find() ([]*model.Ingress, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Ingress, err error)
	FindInBatches(result *[]*model.Ingress, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Ingress) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIngressDo
	Assign(attrs ...field.AssignExpr) IIngressDo
	Joins(fields ...field.RelationField) IIngressDo
	Preload(fields ...field.RelationField) IIngressDo
	FirstOrInit() (*model.Ingress, error)
	FirstOrCreate() (*model.Ingress, error)
	FindByPage(offset int, limit int) (result []*model.Ingress, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIngressDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i ingressDo) Debug() IIngressDo {
	return i.withDO(i.DO.Debug())
}

func (i ingressDo) WithContext(ctx context.Context) IIngressDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i ingressDo) ReadDB() IIngressDo {
	return i.Clauses(dbresolver.Read)
}

func (i ingressDo) WriteDB() IIngressDo {
	return i.Clauses(dbresolver.Write)
}

func (i ingressDo) Session(config *gorm.Session) IIngressDo {
	return i.withDO(i.DO.Session(config))
}

func (i ingressDo) Clauses(conds ...clause.Expression) IIngressDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i ingressDo) Returning(value interface{}, columns ...string) IIngressDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i ingressDo) Not(conds ...gen.Condition) IIngressDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i ingressDo) Or(conds ...gen.Condition) IIngressDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i ingressDo) Select(conds ...field.Expr) IIngressDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i ingressDo) Where(conds ...gen.Condition) IIngressDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i ingressDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IIngressDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i ingressDo) Order(conds ...field.Expr) IIngressDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i ingressDo) Distinct(cols ...field.Expr) IIngressDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i ingressDo) Omit(cols ...field.Expr) IIngressDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i ingressDo) Join(table schema.Tabler, on ...field.Expr) IIngressDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i ingressDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIngressDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i ingressDo) RightJoin(table schema.Tabler, on ...field.Expr) IIngressDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i ingressDo) Group(cols ...field.Expr) IIngressDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i ingressDo) Having(conds ...gen.Condition) IIngressDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i ingressDo) Limit(limit int) IIngressDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i ingressDo) Offset(offset int) IIngressDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i ingressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIngressDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i ingressDo) Unscoped() IIngressDo {
	return i.withDO(i.DO.Unscoped())
}

func (i ingressDo) Create(values ...*model.Ingress) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i ingressDo) CreateInBatches(values []*model.Ingress, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i ingressDo) Save(values ...*model.Ingress) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i ingressDo) First() (*model.Ingress, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ingress), nil
	}
}

func (i ingressDo) Take() (*model.Ingress, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ingress), nil
	}
}

func (i ingressDo) Last() (*model.Ingress, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ingress), nil
	}
}

func (i ingressDo) Find() ([]*model.Ingress, error) {
	result, err := i.DO.Find()
	return result.([]*model.Ingress), err
}

func (i ingressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Ingress, err error) {
	buf := make([]*model.Ingress, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i ingressDo) FindInBatches(result *[]*model.Ingress, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i ingressDo) Attrs(attrs ...field.AssignExpr) IIngressDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i ingressDo) Assign(attrs ...field.AssignExpr) IIngressDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i ingressDo) Joins(fields ...field.RelationField) IIngressDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i ingressDo) Preload(fields ...field.RelationField) IIngressDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i ingressDo) FirstOrInit() (*model.Ingress, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ingress), nil
	}
}

func (i ingressDo) FirstOrCreate() (*model.Ingress, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Ingress), nil
	}
}

func (i ingressDo) FindByPage(offset int, limit int) (result []*model.Ingress, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i ingressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i ingressDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i ingressDo) Delete(models ...*model.Ingress) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *ingressDo) withDO(do gen.Dao) *ingressDo {
	i.DO = *do.(*gen.DO)
	return i
}
