// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newNamespaceUser(db *gorm.DB, opts ...gen.DOOption) namespaceUser {
	_namespaceUser := namespaceUser{}

	_namespaceUser.namespaceUserDo.UseDB(db, opts...)
	_namespaceUser.namespaceUserDo.UseModel(&model.NamespaceUser{})

	tableName := _namespaceUser.namespaceUserDo.TableName()
	_namespaceUser.ALL = field.NewAsterisk(tableName)
	_namespaceUser.ID = field.NewInt64(tableName, "id")
	_namespaceUser.NamespaceID = field.NewInt64(tableName, "namespace_id")
	_namespaceUser.UserID = field.NewInt64(tableName, "user_id")
	_namespaceUser.GroupID = field.NewInt64(tableName, "group_id")
	_namespaceUser.CreateTime = field.NewTime(tableName, "create_time")
	_namespaceUser.UpdateTime = field.NewTime(tableName, "update_time")

	_namespaceUser.fillFieldMap()

	return _namespaceUser
}

type namespaceUser struct {
	namespaceUserDo

	ALL         field.Asterisk
	ID          field.Int64
	NamespaceID field.Int64
	UserID      field.Int64
	GroupID     field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time

	fieldMap map[string]field.Expr
}

func (n namespaceUser) Table(newTableName string) *namespaceUser {
	n.namespaceUserDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n namespaceUser) As(alias string) *namespaceUser {
	n.namespaceUserDo.DO = *(n.namespaceUserDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *namespaceUser) updateTableName(table string) *namespaceUser {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NamespaceID = field.NewInt64(table, "namespace_id")
	n.UserID = field.NewInt64(table, "user_id")
	n.GroupID = field.NewInt64(table, "group_id")
	n.CreateTime = field.NewTime(table, "create_time")
	n.UpdateTime = field.NewTime(table, "update_time")

	n.fillFieldMap()

	return n
}

func (n *namespaceUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *namespaceUser) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 6)
	n.fieldMap["id"] = n.ID
	n.fieldMap["namespace_id"] = n.NamespaceID
	n.fieldMap["user_id"] = n.UserID
	n.fieldMap["group_id"] = n.GroupID
	n.fieldMap["create_time"] = n.CreateTime
	n.fieldMap["update_time"] = n.UpdateTime
}

func (n namespaceUser) clone(db *gorm.DB) namespaceUser {
	n.namespaceUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n namespaceUser) replaceDB(db *gorm.DB) namespaceUser {
	n.namespaceUserDo.ReplaceDB(db)
	return n
}

type namespaceUserDo struct{ gen.DO }

type INamespaceUserDo interface {
	gen.SubQuery
	Debug() INamespaceUserDo
	WithContext(ctx context.Context) INamespaceUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INamespaceUserDo
	WriteDB() INamespaceUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INamespaceUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INamespaceUserDo
	Not(conds ...gen.Condition) INamespaceUserDo
	Or(conds ...gen.Condition) INamespaceUserDo
	Select(conds ...field.Expr) INamespaceUserDo
	Where(conds ...gen.Condition) INamespaceUserDo
	Order(conds ...field.Expr) INamespaceUserDo
	Distinct(cols ...field.Expr) INamespaceUserDo
	Omit(cols ...field.Expr) INamespaceUserDo
	Join(table schema.Tabler, on ...field.Expr) INamespaceUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INamespaceUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) INamespaceUserDo
	Group(cols ...field.Expr) INamespaceUserDo
	Having(conds ...gen.Condition) INamespaceUserDo
	Limit(limit int) INamespaceUserDo
	Offset(offset int) INamespaceUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INamespaceUserDo
	Unscoped() INamespaceUserDo
	Create(values ...*model.NamespaceUser) error
	CreateInBatches(values []*model.NamespaceUser, batchSize int) error
	Save(values ...*model.NamespaceUser) error
	First() (*model.NamespaceUser, error)
	Take() (*model.NamespaceUser, error)
	Last() (*model.NamespaceUser, error)
	Find() ([]*model.NamespaceUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NamespaceUser, err error)
	FindInBatches(result *[]*model.NamespaceUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NamespaceUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INamespaceUserDo
	Assign(attrs ...field.AssignExpr) INamespaceUserDo
	Joins(fields ...field.RelationField) INamespaceUserDo
	Preload(fields ...field.RelationField) INamespaceUserDo
	FirstOrInit() (*model.NamespaceUser, error)
	FirstOrCreate() (*model.NamespaceUser, error)
	FindByPage(offset int, limit int) (result []*model.NamespaceUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INamespaceUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n namespaceUserDo) Debug() INamespaceUserDo {
	return n.withDO(n.DO.Debug())
}

func (n namespaceUserDo) WithContext(ctx context.Context) INamespaceUserDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n namespaceUserDo) ReadDB() INamespaceUserDo {
	return n.Clauses(dbresolver.Read)
}

func (n namespaceUserDo) WriteDB() INamespaceUserDo {
	return n.Clauses(dbresolver.Write)
}

func (n namespaceUserDo) Session(config *gorm.Session) INamespaceUserDo {
	return n.withDO(n.DO.Session(config))
}

func (n namespaceUserDo) Clauses(conds ...clause.Expression) INamespaceUserDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n namespaceUserDo) Returning(value interface{}, columns ...string) INamespaceUserDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n namespaceUserDo) Not(conds ...gen.Condition) INamespaceUserDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n namespaceUserDo) Or(conds ...gen.Condition) INamespaceUserDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n namespaceUserDo) Select(conds ...field.Expr) INamespaceUserDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n namespaceUserDo) Where(conds ...gen.Condition) INamespaceUserDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n namespaceUserDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) INamespaceUserDo {
	return n.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (n namespaceUserDo) Order(conds ...field.Expr) INamespaceUserDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n namespaceUserDo) Distinct(cols ...field.Expr) INamespaceUserDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n namespaceUserDo) Omit(cols ...field.Expr) INamespaceUserDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n namespaceUserDo) Join(table schema.Tabler, on ...field.Expr) INamespaceUserDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n namespaceUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) INamespaceUserDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n namespaceUserDo) RightJoin(table schema.Tabler, on ...field.Expr) INamespaceUserDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n namespaceUserDo) Group(cols ...field.Expr) INamespaceUserDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n namespaceUserDo) Having(conds ...gen.Condition) INamespaceUserDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n namespaceUserDo) Limit(limit int) INamespaceUserDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n namespaceUserDo) Offset(offset int) INamespaceUserDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n namespaceUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INamespaceUserDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n namespaceUserDo) Unscoped() INamespaceUserDo {
	return n.withDO(n.DO.Unscoped())
}

func (n namespaceUserDo) Create(values ...*model.NamespaceUser) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n namespaceUserDo) CreateInBatches(values []*model.NamespaceUser, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n namespaceUserDo) Save(values ...*model.NamespaceUser) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n namespaceUserDo) First() (*model.NamespaceUser, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NamespaceUser), nil
	}
}

func (n namespaceUserDo) Take() (*model.NamespaceUser, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NamespaceUser), nil
	}
}

func (n namespaceUserDo) Last() (*model.NamespaceUser, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NamespaceUser), nil
	}
}

func (n namespaceUserDo) Find() ([]*model.NamespaceUser, error) {
	result, err := n.DO.Find()
	return result.([]*model.NamespaceUser), err
}

func (n namespaceUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NamespaceUser, err error) {
	buf := make([]*model.NamespaceUser, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n namespaceUserDo) FindInBatches(result *[]*model.NamespaceUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n namespaceUserDo) Attrs(attrs ...field.AssignExpr) INamespaceUserDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n namespaceUserDo) Assign(attrs ...field.AssignExpr) INamespaceUserDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n namespaceUserDo) Joins(fields ...field.RelationField) INamespaceUserDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n namespaceUserDo) Preload(fields ...field.RelationField) INamespaceUserDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n namespaceUserDo) FirstOrInit() (*model.NamespaceUser, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NamespaceUser), nil
	}
}

func (n namespaceUserDo) FirstOrCreate() (*model.NamespaceUser, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NamespaceUser), nil
	}
}

func (n namespaceUserDo) FindByPage(offset int, limit int) (result []*model.NamespaceUser, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n namespaceUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n namespaceUserDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n namespaceUserDo) Delete(models ...*model.NamespaceUser) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *namespaceUserDo) withDO(do gen.Dao) *namespaceUserDo {
	n.DO = *do.(*gen.DO)
	return n
}
