// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newPersistentVolumeClaimTemplate(db *gorm.DB, opts ...gen.DOOption) persistentVolumeClaimTemplate {
	_persistentVolumeClaimTemplate := persistentVolumeClaimTemplate{}

	_persistentVolumeClaimTemplate.persistentVolumeClaimTemplateDo.UseDB(db, opts...)
	_persistentVolumeClaimTemplate.persistentVolumeClaimTemplateDo.UseModel(&model.PersistentVolumeClaimTemplate{})

	tableName := _persistentVolumeClaimTemplate.persistentVolumeClaimTemplateDo.TableName()
	_persistentVolumeClaimTemplate.ALL = field.NewAsterisk(tableName)
	_persistentVolumeClaimTemplate.ID = field.NewInt64(tableName, "id")
	_persistentVolumeClaimTemplate.Name = field.NewString(tableName, "name")
	_persistentVolumeClaimTemplate.Template = field.NewString(tableName, "template")
	_persistentVolumeClaimTemplate.PersistentVolumeClaimID = field.NewInt64(tableName, "persistent_volume_claim_id")
	_persistentVolumeClaimTemplate.MetaData = field.NewString(tableName, "meta_data")
	_persistentVolumeClaimTemplate.Description = field.NewString(tableName, "description")
	_persistentVolumeClaimTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_persistentVolumeClaimTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_persistentVolumeClaimTemplate.User = field.NewString(tableName, "user")
	_persistentVolumeClaimTemplate.Deleted = field.NewBool(tableName, "deleted")

	_persistentVolumeClaimTemplate.fillFieldMap()

	return _persistentVolumeClaimTemplate
}

type persistentVolumeClaimTemplate struct {
	persistentVolumeClaimTemplateDo

	ALL                     field.Asterisk
	ID                      field.Int64
	Name                    field.String
	Template                field.String
	PersistentVolumeClaimID field.Int64
	MetaData                field.String
	Description             field.String
	CreateTime              field.Time
	UpdateTime              field.Time
	User                    field.String
	Deleted                 field.Bool

	fieldMap map[string]field.Expr
}

func (p persistentVolumeClaimTemplate) Table(newTableName string) *persistentVolumeClaimTemplate {
	p.persistentVolumeClaimTemplateDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p persistentVolumeClaimTemplate) As(alias string) *persistentVolumeClaimTemplate {
	p.persistentVolumeClaimTemplateDo.DO = *(p.persistentVolumeClaimTemplateDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *persistentVolumeClaimTemplate) updateTableName(table string) *persistentVolumeClaimTemplate {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.Template = field.NewString(table, "template")
	p.PersistentVolumeClaimID = field.NewInt64(table, "persistent_volume_claim_id")
	p.MetaData = field.NewString(table, "meta_data")
	p.Description = field.NewString(table, "description")
	p.CreateTime = field.NewTime(table, "create_time")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.User = field.NewString(table, "user")
	p.Deleted = field.NewBool(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *persistentVolumeClaimTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *persistentVolumeClaimTemplate) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["template"] = p.Template
	p.fieldMap["persistent_volume_claim_id"] = p.PersistentVolumeClaimID
	p.fieldMap["meta_data"] = p.MetaData
	p.fieldMap["description"] = p.Description
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["user"] = p.User
	p.fieldMap["deleted"] = p.Deleted
}

func (p persistentVolumeClaimTemplate) clone(db *gorm.DB) persistentVolumeClaimTemplate {
	p.persistentVolumeClaimTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p persistentVolumeClaimTemplate) replaceDB(db *gorm.DB) persistentVolumeClaimTemplate {
	p.persistentVolumeClaimTemplateDo.ReplaceDB(db)
	return p
}

type persistentVolumeClaimTemplateDo struct{ gen.DO }

type IPersistentVolumeClaimTemplateDo interface {
	gen.SubQuery
	Debug() IPersistentVolumeClaimTemplateDo
	WithContext(ctx context.Context) IPersistentVolumeClaimTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPersistentVolumeClaimTemplateDo
	WriteDB() IPersistentVolumeClaimTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPersistentVolumeClaimTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPersistentVolumeClaimTemplateDo
	Not(conds ...gen.Condition) IPersistentVolumeClaimTemplateDo
	Or(conds ...gen.Condition) IPersistentVolumeClaimTemplateDo
	Select(conds ...field.Expr) IPersistentVolumeClaimTemplateDo
	Where(conds ...gen.Condition) IPersistentVolumeClaimTemplateDo
	Order(conds ...field.Expr) IPersistentVolumeClaimTemplateDo
	Distinct(cols ...field.Expr) IPersistentVolumeClaimTemplateDo
	Omit(cols ...field.Expr) IPersistentVolumeClaimTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimTemplateDo
	Group(cols ...field.Expr) IPersistentVolumeClaimTemplateDo
	Having(conds ...gen.Condition) IPersistentVolumeClaimTemplateDo
	Limit(limit int) IPersistentVolumeClaimTemplateDo
	Offset(offset int) IPersistentVolumeClaimTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPersistentVolumeClaimTemplateDo
	Unscoped() IPersistentVolumeClaimTemplateDo
	Create(values ...*model.PersistentVolumeClaimTemplate) error
	CreateInBatches(values []*model.PersistentVolumeClaimTemplate, batchSize int) error
	Save(values ...*model.PersistentVolumeClaimTemplate) error
	First() (*model.PersistentVolumeClaimTemplate, error)
	Take() (*model.PersistentVolumeClaimTemplate, error)
	Last() (*model.PersistentVolumeClaimTemplate, error)
	Find() ([]*model.PersistentVolumeClaimTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PersistentVolumeClaimTemplate, err error)
	FindInBatches(result *[]*model.PersistentVolumeClaimTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PersistentVolumeClaimTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPersistentVolumeClaimTemplateDo
	Assign(attrs ...field.AssignExpr) IPersistentVolumeClaimTemplateDo
	Joins(fields ...field.RelationField) IPersistentVolumeClaimTemplateDo
	Preload(fields ...field.RelationField) IPersistentVolumeClaimTemplateDo
	FirstOrInit() (*model.PersistentVolumeClaimTemplate, error)
	FirstOrCreate() (*model.PersistentVolumeClaimTemplate, error)
	FindByPage(offset int, limit int) (result []*model.PersistentVolumeClaimTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPersistentVolumeClaimTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p persistentVolumeClaimTemplateDo) Debug() IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Debug())
}

func (p persistentVolumeClaimTemplateDo) WithContext(ctx context.Context) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p persistentVolumeClaimTemplateDo) ReadDB() IPersistentVolumeClaimTemplateDo {
	return p.Clauses(dbresolver.Read)
}

func (p persistentVolumeClaimTemplateDo) WriteDB() IPersistentVolumeClaimTemplateDo {
	return p.Clauses(dbresolver.Write)
}

func (p persistentVolumeClaimTemplateDo) Session(config *gorm.Session) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Session(config))
}

func (p persistentVolumeClaimTemplateDo) Clauses(conds ...clause.Expression) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p persistentVolumeClaimTemplateDo) Returning(value interface{}, columns ...string) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p persistentVolumeClaimTemplateDo) Not(conds ...gen.Condition) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p persistentVolumeClaimTemplateDo) Or(conds ...gen.Condition) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p persistentVolumeClaimTemplateDo) Select(conds ...field.Expr) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p persistentVolumeClaimTemplateDo) Where(conds ...gen.Condition) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p persistentVolumeClaimTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IPersistentVolumeClaimTemplateDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p persistentVolumeClaimTemplateDo) Order(conds ...field.Expr) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p persistentVolumeClaimTemplateDo) Distinct(cols ...field.Expr) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p persistentVolumeClaimTemplateDo) Omit(cols ...field.Expr) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p persistentVolumeClaimTemplateDo) Join(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p persistentVolumeClaimTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p persistentVolumeClaimTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p persistentVolumeClaimTemplateDo) Group(cols ...field.Expr) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p persistentVolumeClaimTemplateDo) Having(conds ...gen.Condition) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p persistentVolumeClaimTemplateDo) Limit(limit int) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p persistentVolumeClaimTemplateDo) Offset(offset int) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p persistentVolumeClaimTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p persistentVolumeClaimTemplateDo) Unscoped() IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Unscoped())
}

func (p persistentVolumeClaimTemplateDo) Create(values ...*model.PersistentVolumeClaimTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p persistentVolumeClaimTemplateDo) CreateInBatches(values []*model.PersistentVolumeClaimTemplate, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p persistentVolumeClaimTemplateDo) Save(values ...*model.PersistentVolumeClaimTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p persistentVolumeClaimTemplateDo) First() (*model.PersistentVolumeClaimTemplate, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersistentVolumeClaimTemplate), nil
	}
}

func (p persistentVolumeClaimTemplateDo) Take() (*model.PersistentVolumeClaimTemplate, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersistentVolumeClaimTemplate), nil
	}
}

func (p persistentVolumeClaimTemplateDo) Last() (*model.PersistentVolumeClaimTemplate, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersistentVolumeClaimTemplate), nil
	}
}

func (p persistentVolumeClaimTemplateDo) Find() ([]*model.PersistentVolumeClaimTemplate, error) {
	result, err := p.DO.Find()
	return result.([]*model.PersistentVolumeClaimTemplate), err
}

func (p persistentVolumeClaimTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PersistentVolumeClaimTemplate, err error) {
	buf := make([]*model.PersistentVolumeClaimTemplate, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p persistentVolumeClaimTemplateDo) FindInBatches(result *[]*model.PersistentVolumeClaimTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p persistentVolumeClaimTemplateDo) Attrs(attrs ...field.AssignExpr) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p persistentVolumeClaimTemplateDo) Assign(attrs ...field.AssignExpr) IPersistentVolumeClaimTemplateDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p persistentVolumeClaimTemplateDo) Joins(fields ...field.RelationField) IPersistentVolumeClaimTemplateDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p persistentVolumeClaimTemplateDo) Preload(fields ...field.RelationField) IPersistentVolumeClaimTemplateDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p persistentVolumeClaimTemplateDo) FirstOrInit() (*model.PersistentVolumeClaimTemplate, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersistentVolumeClaimTemplate), nil
	}
}

func (p persistentVolumeClaimTemplateDo) FirstOrCreate() (*model.PersistentVolumeClaimTemplate, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersistentVolumeClaimTemplate), nil
	}
}

func (p persistentVolumeClaimTemplateDo) FindByPage(offset int, limit int) (result []*model.PersistentVolumeClaimTemplate, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p persistentVolumeClaimTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p persistentVolumeClaimTemplateDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p persistentVolumeClaimTemplateDo) Delete(models ...*model.PersistentVolumeClaimTemplate) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *persistentVolumeClaimTemplateDo) withDO(do gen.Dao) *persistentVolumeClaimTemplateDo {
	p.DO = *do.(*gen.DO)
	return p
}
