// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newPersistentVolumeClaim(db *gorm.DB, opts ...gen.DOOption) persistentVolumeClaim {
	_persistentVolumeClaim := persistentVolumeClaim{}

	_persistentVolumeClaim.persistentVolumeClaimDo.UseDB(db, opts...)
	_persistentVolumeClaim.persistentVolumeClaimDo.UseModel(&model.PersistentVolumeClaim{})

	tableName := _persistentVolumeClaim.persistentVolumeClaimDo.TableName()
	_persistentVolumeClaim.ALL = field.NewAsterisk(tableName)
	_persistentVolumeClaim.ID = field.NewInt64(tableName, "id")
	_persistentVolumeClaim.Name = field.NewString(tableName, "name")
	_persistentVolumeClaim.MetaData = field.NewString(tableName, "meta_data")
	_persistentVolumeClaim.AppID = field.NewInt64(tableName, "app_id")
	_persistentVolumeClaim.Description = field.NewString(tableName, "description")
	_persistentVolumeClaim.OrderID = field.NewInt64(tableName, "order_id")
	_persistentVolumeClaim.CreateTime = field.NewTime(tableName, "create_time")
	_persistentVolumeClaim.UpdateTime = field.NewTime(tableName, "update_time")
	_persistentVolumeClaim.User = field.NewString(tableName, "user")
	_persistentVolumeClaim.Deleted = field.NewBool(tableName, "deleted")

	_persistentVolumeClaim.fillFieldMap()

	return _persistentVolumeClaim
}

type persistentVolumeClaim struct {
	persistentVolumeClaimDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	MetaData    field.String
	AppID       field.Int64
	Description field.String
	OrderID     field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (p persistentVolumeClaim) Table(newTableName string) *persistentVolumeClaim {
	p.persistentVolumeClaimDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p persistentVolumeClaim) As(alias string) *persistentVolumeClaim {
	p.persistentVolumeClaimDo.DO = *(p.persistentVolumeClaimDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *persistentVolumeClaim) updateTableName(table string) *persistentVolumeClaim {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.MetaData = field.NewString(table, "meta_data")
	p.AppID = field.NewInt64(table, "app_id")
	p.Description = field.NewString(table, "description")
	p.OrderID = field.NewInt64(table, "order_id")
	p.CreateTime = field.NewTime(table, "create_time")
	p.UpdateTime = field.NewTime(table, "update_time")
	p.User = field.NewString(table, "user")
	p.Deleted = field.NewBool(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *persistentVolumeClaim) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *persistentVolumeClaim) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["meta_data"] = p.MetaData
	p.fieldMap["app_id"] = p.AppID
	p.fieldMap["description"] = p.Description
	p.fieldMap["order_id"] = p.OrderID
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["update_time"] = p.UpdateTime
	p.fieldMap["user"] = p.User
	p.fieldMap["deleted"] = p.Deleted
}

func (p persistentVolumeClaim) clone(db *gorm.DB) persistentVolumeClaim {
	p.persistentVolumeClaimDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p persistentVolumeClaim) replaceDB(db *gorm.DB) persistentVolumeClaim {
	p.persistentVolumeClaimDo.ReplaceDB(db)
	return p
}

type persistentVolumeClaimDo struct{ gen.DO }

type IPersistentVolumeClaimDo interface {
	gen.SubQuery
	Debug() IPersistentVolumeClaimDo
	WithContext(ctx context.Context) IPersistentVolumeClaimDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPersistentVolumeClaimDo
	WriteDB() IPersistentVolumeClaimDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPersistentVolumeClaimDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPersistentVolumeClaimDo
	Not(conds ...gen.Condition) IPersistentVolumeClaimDo
	Or(conds ...gen.Condition) IPersistentVolumeClaimDo
	Select(conds ...field.Expr) IPersistentVolumeClaimDo
	Where(conds ...gen.Condition) IPersistentVolumeClaimDo
	Order(conds ...field.Expr) IPersistentVolumeClaimDo
	Distinct(cols ...field.Expr) IPersistentVolumeClaimDo
	Omit(cols ...field.Expr) IPersistentVolumeClaimDo
	Join(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimDo
	Group(cols ...field.Expr) IPersistentVolumeClaimDo
	Having(conds ...gen.Condition) IPersistentVolumeClaimDo
	Limit(limit int) IPersistentVolumeClaimDo
	Offset(offset int) IPersistentVolumeClaimDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPersistentVolumeClaimDo
	Unscoped() IPersistentVolumeClaimDo
	Create(values ...*model.PersistentVolumeClaim) error
	CreateInBatches(values []*model.PersistentVolumeClaim, batchSize int) error
	Save(values ...*model.PersistentVolumeClaim) error
	First() (*model.PersistentVolumeClaim, error)
	Take() (*model.PersistentVolumeClaim, error)
	Last() (*model.PersistentVolumeClaim, error)
	Find() ([]*model.PersistentVolumeClaim, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PersistentVolumeClaim, err error)
	FindInBatches(result *[]*model.PersistentVolumeClaim, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PersistentVolumeClaim) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPersistentVolumeClaimDo
	Assign(attrs ...field.AssignExpr) IPersistentVolumeClaimDo
	Joins(fields ...field.RelationField) IPersistentVolumeClaimDo
	Preload(fields ...field.RelationField) IPersistentVolumeClaimDo
	FirstOrInit() (*model.PersistentVolumeClaim, error)
	FirstOrCreate() (*model.PersistentVolumeClaim, error)
	FindByPage(offset int, limit int) (result []*model.PersistentVolumeClaim, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPersistentVolumeClaimDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p persistentVolumeClaimDo) Debug() IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Debug())
}

func (p persistentVolumeClaimDo) WithContext(ctx context.Context) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p persistentVolumeClaimDo) ReadDB() IPersistentVolumeClaimDo {
	return p.Clauses(dbresolver.Read)
}

func (p persistentVolumeClaimDo) WriteDB() IPersistentVolumeClaimDo {
	return p.Clauses(dbresolver.Write)
}

func (p persistentVolumeClaimDo) Session(config *gorm.Session) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Session(config))
}

func (p persistentVolumeClaimDo) Clauses(conds ...clause.Expression) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p persistentVolumeClaimDo) Returning(value interface{}, columns ...string) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p persistentVolumeClaimDo) Not(conds ...gen.Condition) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p persistentVolumeClaimDo) Or(conds ...gen.Condition) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p persistentVolumeClaimDo) Select(conds ...field.Expr) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p persistentVolumeClaimDo) Where(conds ...gen.Condition) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p persistentVolumeClaimDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IPersistentVolumeClaimDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p persistentVolumeClaimDo) Order(conds ...field.Expr) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p persistentVolumeClaimDo) Distinct(cols ...field.Expr) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p persistentVolumeClaimDo) Omit(cols ...field.Expr) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p persistentVolumeClaimDo) Join(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p persistentVolumeClaimDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p persistentVolumeClaimDo) RightJoin(table schema.Tabler, on ...field.Expr) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p persistentVolumeClaimDo) Group(cols ...field.Expr) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p persistentVolumeClaimDo) Having(conds ...gen.Condition) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p persistentVolumeClaimDo) Limit(limit int) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p persistentVolumeClaimDo) Offset(offset int) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p persistentVolumeClaimDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p persistentVolumeClaimDo) Unscoped() IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Unscoped())
}

func (p persistentVolumeClaimDo) Create(values ...*model.PersistentVolumeClaim) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p persistentVolumeClaimDo) CreateInBatches(values []*model.PersistentVolumeClaim, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p persistentVolumeClaimDo) Save(values ...*model.PersistentVolumeClaim) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p persistentVolumeClaimDo) First() (*model.PersistentVolumeClaim, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersistentVolumeClaim), nil
	}
}

func (p persistentVolumeClaimDo) Take() (*model.PersistentVolumeClaim, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersistentVolumeClaim), nil
	}
}

func (p persistentVolumeClaimDo) Last() (*model.PersistentVolumeClaim, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersistentVolumeClaim), nil
	}
}

func (p persistentVolumeClaimDo) Find() ([]*model.PersistentVolumeClaim, error) {
	result, err := p.DO.Find()
	return result.([]*model.PersistentVolumeClaim), err
}

func (p persistentVolumeClaimDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PersistentVolumeClaim, err error) {
	buf := make([]*model.PersistentVolumeClaim, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p persistentVolumeClaimDo) FindInBatches(result *[]*model.PersistentVolumeClaim, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p persistentVolumeClaimDo) Attrs(attrs ...field.AssignExpr) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p persistentVolumeClaimDo) Assign(attrs ...field.AssignExpr) IPersistentVolumeClaimDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p persistentVolumeClaimDo) Joins(fields ...field.RelationField) IPersistentVolumeClaimDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p persistentVolumeClaimDo) Preload(fields ...field.RelationField) IPersistentVolumeClaimDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p persistentVolumeClaimDo) FirstOrInit() (*model.PersistentVolumeClaim, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersistentVolumeClaim), nil
	}
}

func (p persistentVolumeClaimDo) FirstOrCreate() (*model.PersistentVolumeClaim, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PersistentVolumeClaim), nil
	}
}

func (p persistentVolumeClaimDo) FindByPage(offset int, limit int) (result []*model.PersistentVolumeClaim, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p persistentVolumeClaimDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p persistentVolumeClaimDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p persistentVolumeClaimDo) Delete(models ...*model.PersistentVolumeClaim) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *persistentVolumeClaimDo) withDO(do gen.Dao) *persistentVolumeClaimDo {
	p.DO = *do.(*gen.DO)
	return p
}
