// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newPublishStatus(db *gorm.DB, opts ...gen.DOOption) publishStatus {
	_publishStatus := publishStatus{}

	_publishStatus.publishStatusDo.UseDB(db, opts...)
	_publishStatus.publishStatusDo.UseModel(&model.PublishStatus{})

	tableName := _publishStatus.publishStatusDo.TableName()
	_publishStatus.ALL = field.NewAsterisk(tableName)
	_publishStatus.ID = field.NewInt64(tableName, "id")
	_publishStatus.Type = field.NewInt32(tableName, "type")
	_publishStatus.ResourceID = field.NewInt64(tableName, "resource_id")
	_publishStatus.TemplateID = field.NewInt64(tableName, "template_id")
	_publishStatus.Cluster = field.NewString(tableName, "cluster")

	_publishStatus.fillFieldMap()

	return _publishStatus
}

type publishStatus struct {
	publishStatusDo

	ALL        field.Asterisk
	ID         field.Int64
	Type       field.Int32
	ResourceID field.Int64
	TemplateID field.Int64
	Cluster    field.String

	fieldMap map[string]field.Expr
}

func (p publishStatus) Table(newTableName string) *publishStatus {
	p.publishStatusDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p publishStatus) As(alias string) *publishStatus {
	p.publishStatusDo.DO = *(p.publishStatusDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *publishStatus) updateTableName(table string) *publishStatus {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Type = field.NewInt32(table, "type")
	p.ResourceID = field.NewInt64(table, "resource_id")
	p.TemplateID = field.NewInt64(table, "template_id")
	p.Cluster = field.NewString(table, "cluster")

	p.fillFieldMap()

	return p
}

func (p *publishStatus) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *publishStatus) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["id"] = p.ID
	p.fieldMap["type"] = p.Type
	p.fieldMap["resource_id"] = p.ResourceID
	p.fieldMap["template_id"] = p.TemplateID
	p.fieldMap["cluster"] = p.Cluster
}

func (p publishStatus) clone(db *gorm.DB) publishStatus {
	p.publishStatusDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p publishStatus) replaceDB(db *gorm.DB) publishStatus {
	p.publishStatusDo.ReplaceDB(db)
	return p
}

type publishStatusDo struct{ gen.DO }

type IPublishStatusDo interface {
	gen.SubQuery
	Debug() IPublishStatusDo
	WithContext(ctx context.Context) IPublishStatusDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPublishStatusDo
	WriteDB() IPublishStatusDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPublishStatusDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPublishStatusDo
	Not(conds ...gen.Condition) IPublishStatusDo
	Or(conds ...gen.Condition) IPublishStatusDo
	Select(conds ...field.Expr) IPublishStatusDo
	Where(conds ...gen.Condition) IPublishStatusDo
	Order(conds ...field.Expr) IPublishStatusDo
	Distinct(cols ...field.Expr) IPublishStatusDo
	Omit(cols ...field.Expr) IPublishStatusDo
	Join(table schema.Tabler, on ...field.Expr) IPublishStatusDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPublishStatusDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPublishStatusDo
	Group(cols ...field.Expr) IPublishStatusDo
	Having(conds ...gen.Condition) IPublishStatusDo
	Limit(limit int) IPublishStatusDo
	Offset(offset int) IPublishStatusDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPublishStatusDo
	Unscoped() IPublishStatusDo
	Create(values ...*model.PublishStatus) error
	CreateInBatches(values []*model.PublishStatus, batchSize int) error
	Save(values ...*model.PublishStatus) error
	First() (*model.PublishStatus, error)
	Take() (*model.PublishStatus, error)
	Last() (*model.PublishStatus, error)
	Find() ([]*model.PublishStatus, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PublishStatus, err error)
	FindInBatches(result *[]*model.PublishStatus, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PublishStatus) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPublishStatusDo
	Assign(attrs ...field.AssignExpr) IPublishStatusDo
	Joins(fields ...field.RelationField) IPublishStatusDo
	Preload(fields ...field.RelationField) IPublishStatusDo
	FirstOrInit() (*model.PublishStatus, error)
	FirstOrCreate() (*model.PublishStatus, error)
	FindByPage(offset int, limit int) (result []*model.PublishStatus, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPublishStatusDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p publishStatusDo) Debug() IPublishStatusDo {
	return p.withDO(p.DO.Debug())
}

func (p publishStatusDo) WithContext(ctx context.Context) IPublishStatusDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p publishStatusDo) ReadDB() IPublishStatusDo {
	return p.Clauses(dbresolver.Read)
}

func (p publishStatusDo) WriteDB() IPublishStatusDo {
	return p.Clauses(dbresolver.Write)
}

func (p publishStatusDo) Session(config *gorm.Session) IPublishStatusDo {
	return p.withDO(p.DO.Session(config))
}

func (p publishStatusDo) Clauses(conds ...clause.Expression) IPublishStatusDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p publishStatusDo) Returning(value interface{}, columns ...string) IPublishStatusDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p publishStatusDo) Not(conds ...gen.Condition) IPublishStatusDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p publishStatusDo) Or(conds ...gen.Condition) IPublishStatusDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p publishStatusDo) Select(conds ...field.Expr) IPublishStatusDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p publishStatusDo) Where(conds ...gen.Condition) IPublishStatusDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p publishStatusDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IPublishStatusDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p publishStatusDo) Order(conds ...field.Expr) IPublishStatusDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p publishStatusDo) Distinct(cols ...field.Expr) IPublishStatusDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p publishStatusDo) Omit(cols ...field.Expr) IPublishStatusDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p publishStatusDo) Join(table schema.Tabler, on ...field.Expr) IPublishStatusDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p publishStatusDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPublishStatusDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p publishStatusDo) RightJoin(table schema.Tabler, on ...field.Expr) IPublishStatusDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p publishStatusDo) Group(cols ...field.Expr) IPublishStatusDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p publishStatusDo) Having(conds ...gen.Condition) IPublishStatusDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p publishStatusDo) Limit(limit int) IPublishStatusDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p publishStatusDo) Offset(offset int) IPublishStatusDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p publishStatusDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPublishStatusDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p publishStatusDo) Unscoped() IPublishStatusDo {
	return p.withDO(p.DO.Unscoped())
}

func (p publishStatusDo) Create(values ...*model.PublishStatus) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p publishStatusDo) CreateInBatches(values []*model.PublishStatus, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p publishStatusDo) Save(values ...*model.PublishStatus) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p publishStatusDo) First() (*model.PublishStatus, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishStatus), nil
	}
}

func (p publishStatusDo) Take() (*model.PublishStatus, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishStatus), nil
	}
}

func (p publishStatusDo) Last() (*model.PublishStatus, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishStatus), nil
	}
}

func (p publishStatusDo) Find() ([]*model.PublishStatus, error) {
	result, err := p.DO.Find()
	return result.([]*model.PublishStatus), err
}

func (p publishStatusDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PublishStatus, err error) {
	buf := make([]*model.PublishStatus, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p publishStatusDo) FindInBatches(result *[]*model.PublishStatus, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p publishStatusDo) Attrs(attrs ...field.AssignExpr) IPublishStatusDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p publishStatusDo) Assign(attrs ...field.AssignExpr) IPublishStatusDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p publishStatusDo) Joins(fields ...field.RelationField) IPublishStatusDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p publishStatusDo) Preload(fields ...field.RelationField) IPublishStatusDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p publishStatusDo) FirstOrInit() (*model.PublishStatus, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishStatus), nil
	}
}

func (p publishStatusDo) FirstOrCreate() (*model.PublishStatus, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishStatus), nil
	}
}

func (p publishStatusDo) FindByPage(offset int, limit int) (result []*model.PublishStatus, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p publishStatusDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p publishStatusDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p publishStatusDo) Delete(models ...*model.PublishStatus) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *publishStatusDo) withDO(do gen.Dao) *publishStatusDo {
	p.DO = *do.(*gen.DO)
	return p
}
