// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newPublishHistory(db *gorm.DB, opts ...gen.DOOption) publishHistory {
	_publishHistory := publishHistory{}

	_publishHistory.publishHistoryDo.UseDB(db, opts...)
	_publishHistory.publishHistoryDo.UseModel(&model.PublishHistory{})

	tableName := _publishHistory.publishHistoryDo.TableName()
	_publishHistory.ALL = field.NewAsterisk(tableName)
	_publishHistory.ID = field.NewInt64(tableName, "id")
	_publishHistory.Type = field.NewInt32(tableName, "type")
	_publishHistory.ResourceID = field.NewInt64(tableName, "resource_id")
	_publishHistory.ResourceName = field.NewString(tableName, "resource_name")
	_publishHistory.TemplateID = field.NewInt64(tableName, "template_id")
	_publishHistory.Cluster = field.NewString(tableName, "cluster")
	_publishHistory.Status = field.NewInt32(tableName, "status")
	_publishHistory.Message = field.NewString(tableName, "message")
	_publishHistory.User = field.NewString(tableName, "user")
	_publishHistory.CreateTime = field.NewTime(tableName, "create_time")

	_publishHistory.fillFieldMap()

	return _publishHistory
}

type publishHistory struct {
	publishHistoryDo

	ALL          field.Asterisk
	ID           field.Int64
	Type         field.Int32
	ResourceID   field.Int64
	ResourceName field.String
	TemplateID   field.Int64
	Cluster      field.String
	Status       field.Int32
	Message      field.String
	User         field.String
	CreateTime   field.Time

	fieldMap map[string]field.Expr
}

func (p publishHistory) Table(newTableName string) *publishHistory {
	p.publishHistoryDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p publishHistory) As(alias string) *publishHistory {
	p.publishHistoryDo.DO = *(p.publishHistoryDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *publishHistory) updateTableName(table string) *publishHistory {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Type = field.NewInt32(table, "type")
	p.ResourceID = field.NewInt64(table, "resource_id")
	p.ResourceName = field.NewString(table, "resource_name")
	p.TemplateID = field.NewInt64(table, "template_id")
	p.Cluster = field.NewString(table, "cluster")
	p.Status = field.NewInt32(table, "status")
	p.Message = field.NewString(table, "message")
	p.User = field.NewString(table, "user")
	p.CreateTime = field.NewTime(table, "create_time")

	p.fillFieldMap()

	return p
}

func (p *publishHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *publishHistory) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["id"] = p.ID
	p.fieldMap["type"] = p.Type
	p.fieldMap["resource_id"] = p.ResourceID
	p.fieldMap["resource_name"] = p.ResourceName
	p.fieldMap["template_id"] = p.TemplateID
	p.fieldMap["cluster"] = p.Cluster
	p.fieldMap["status"] = p.Status
	p.fieldMap["message"] = p.Message
	p.fieldMap["user"] = p.User
	p.fieldMap["create_time"] = p.CreateTime
}

func (p publishHistory) clone(db *gorm.DB) publishHistory {
	p.publishHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p publishHistory) replaceDB(db *gorm.DB) publishHistory {
	p.publishHistoryDo.ReplaceDB(db)
	return p
}

type publishHistoryDo struct{ gen.DO }

type IPublishHistoryDo interface {
	gen.SubQuery
	Debug() IPublishHistoryDo
	WithContext(ctx context.Context) IPublishHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPublishHistoryDo
	WriteDB() IPublishHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPublishHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPublishHistoryDo
	Not(conds ...gen.Condition) IPublishHistoryDo
	Or(conds ...gen.Condition) IPublishHistoryDo
	Select(conds ...field.Expr) IPublishHistoryDo
	Where(conds ...gen.Condition) IPublishHistoryDo
	Order(conds ...field.Expr) IPublishHistoryDo
	Distinct(cols ...field.Expr) IPublishHistoryDo
	Omit(cols ...field.Expr) IPublishHistoryDo
	Join(table schema.Tabler, on ...field.Expr) IPublishHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPublishHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPublishHistoryDo
	Group(cols ...field.Expr) IPublishHistoryDo
	Having(conds ...gen.Condition) IPublishHistoryDo
	Limit(limit int) IPublishHistoryDo
	Offset(offset int) IPublishHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPublishHistoryDo
	Unscoped() IPublishHistoryDo
	Create(values ...*model.PublishHistory) error
	CreateInBatches(values []*model.PublishHistory, batchSize int) error
	Save(values ...*model.PublishHistory) error
	First() (*model.PublishHistory, error)
	Take() (*model.PublishHistory, error)
	Last() (*model.PublishHistory, error)
	Find() ([]*model.PublishHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PublishHistory, err error)
	FindInBatches(result *[]*model.PublishHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PublishHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPublishHistoryDo
	Assign(attrs ...field.AssignExpr) IPublishHistoryDo
	Joins(fields ...field.RelationField) IPublishHistoryDo
	Preload(fields ...field.RelationField) IPublishHistoryDo
	FirstOrInit() (*model.PublishHistory, error)
	FirstOrCreate() (*model.PublishHistory, error)
	FindByPage(offset int, limit int) (result []*model.PublishHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPublishHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p publishHistoryDo) Debug() IPublishHistoryDo {
	return p.withDO(p.DO.Debug())
}

func (p publishHistoryDo) WithContext(ctx context.Context) IPublishHistoryDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p publishHistoryDo) ReadDB() IPublishHistoryDo {
	return p.Clauses(dbresolver.Read)
}

func (p publishHistoryDo) WriteDB() IPublishHistoryDo {
	return p.Clauses(dbresolver.Write)
}

func (p publishHistoryDo) Session(config *gorm.Session) IPublishHistoryDo {
	return p.withDO(p.DO.Session(config))
}

func (p publishHistoryDo) Clauses(conds ...clause.Expression) IPublishHistoryDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p publishHistoryDo) Returning(value interface{}, columns ...string) IPublishHistoryDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p publishHistoryDo) Not(conds ...gen.Condition) IPublishHistoryDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p publishHistoryDo) Or(conds ...gen.Condition) IPublishHistoryDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p publishHistoryDo) Select(conds ...field.Expr) IPublishHistoryDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p publishHistoryDo) Where(conds ...gen.Condition) IPublishHistoryDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p publishHistoryDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IPublishHistoryDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p publishHistoryDo) Order(conds ...field.Expr) IPublishHistoryDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p publishHistoryDo) Distinct(cols ...field.Expr) IPublishHistoryDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p publishHistoryDo) Omit(cols ...field.Expr) IPublishHistoryDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p publishHistoryDo) Join(table schema.Tabler, on ...field.Expr) IPublishHistoryDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p publishHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPublishHistoryDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p publishHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IPublishHistoryDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p publishHistoryDo) Group(cols ...field.Expr) IPublishHistoryDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p publishHistoryDo) Having(conds ...gen.Condition) IPublishHistoryDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p publishHistoryDo) Limit(limit int) IPublishHistoryDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p publishHistoryDo) Offset(offset int) IPublishHistoryDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p publishHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPublishHistoryDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p publishHistoryDo) Unscoped() IPublishHistoryDo {
	return p.withDO(p.DO.Unscoped())
}

func (p publishHistoryDo) Create(values ...*model.PublishHistory) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p publishHistoryDo) CreateInBatches(values []*model.PublishHistory, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p publishHistoryDo) Save(values ...*model.PublishHistory) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p publishHistoryDo) First() (*model.PublishHistory, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishHistory), nil
	}
}

func (p publishHistoryDo) Take() (*model.PublishHistory, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishHistory), nil
	}
}

func (p publishHistoryDo) Last() (*model.PublishHistory, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishHistory), nil
	}
}

func (p publishHistoryDo) Find() ([]*model.PublishHistory, error) {
	result, err := p.DO.Find()
	return result.([]*model.PublishHistory), err
}

func (p publishHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PublishHistory, err error) {
	buf := make([]*model.PublishHistory, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p publishHistoryDo) FindInBatches(result *[]*model.PublishHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p publishHistoryDo) Attrs(attrs ...field.AssignExpr) IPublishHistoryDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p publishHistoryDo) Assign(attrs ...field.AssignExpr) IPublishHistoryDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p publishHistoryDo) Joins(fields ...field.RelationField) IPublishHistoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p publishHistoryDo) Preload(fields ...field.RelationField) IPublishHistoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p publishHistoryDo) FirstOrInit() (*model.PublishHistory, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishHistory), nil
	}
}

func (p publishHistoryDo) FirstOrCreate() (*model.PublishHistory, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishHistory), nil
	}
}

func (p publishHistoryDo) FindByPage(offset int, limit int) (result []*model.PublishHistory, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p publishHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p publishHistoryDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p publishHistoryDo) Delete(models ...*model.PublishHistory) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *publishHistoryDo) withDO(do gen.Dao) *publishHistoryDo {
	p.DO = *do.(*gen.DO)
	return p
}
