// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newSecret(db *gorm.DB, opts ...gen.DOOption) secret {
	_secret := secret{}

	_secret.secretDo.UseDB(db, opts...)
	_secret.secretDo.UseModel(&model.Secret{})

	tableName := _secret.secretDo.TableName()
	_secret.ALL = field.NewAsterisk(tableName)
	_secret.ID = field.NewInt64(tableName, "id")
	_secret.Name = field.NewString(tableName, "name")
	_secret.MetaData = field.NewString(tableName, "meta_data")
	_secret.AppID = field.NewInt64(tableName, "app_id")
	_secret.Description = field.NewString(tableName, "description")
	_secret.OrderID = field.NewInt64(tableName, "order_id")
	_secret.CreateTime = field.NewTime(tableName, "create_time")
	_secret.UpdateTime = field.NewTime(tableName, "update_time")
	_secret.User = field.NewString(tableName, "user")
	_secret.Deleted = field.NewBool(tableName, "deleted")

	_secret.fillFieldMap()

	return _secret
}

type secret struct {
	secretDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	MetaData    field.String
	AppID       field.Int64
	Description field.String
	OrderID     field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (s secret) Table(newTableName string) *secret {
	s.secretDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s secret) As(alias string) *secret {
	s.secretDo.DO = *(s.secretDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *secret) updateTableName(table string) *secret {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.MetaData = field.NewString(table, "meta_data")
	s.AppID = field.NewInt64(table, "app_id")
	s.Description = field.NewString(table, "description")
	s.OrderID = field.NewInt64(table, "order_id")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.User = field.NewString(table, "user")
	s.Deleted = field.NewBool(table, "deleted")

	s.fillFieldMap()

	return s
}

func (s *secret) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *secret) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["meta_data"] = s.MetaData
	s.fieldMap["app_id"] = s.AppID
	s.fieldMap["description"] = s.Description
	s.fieldMap["order_id"] = s.OrderID
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["user"] = s.User
	s.fieldMap["deleted"] = s.Deleted
}

func (s secret) clone(db *gorm.DB) secret {
	s.secretDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s secret) replaceDB(db *gorm.DB) secret {
	s.secretDo.ReplaceDB(db)
	return s
}

type secretDo struct{ gen.DO }

type ISecretDo interface {
	gen.SubQuery
	Debug() ISecretDo
	WithContext(ctx context.Context) ISecretDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISecretDo
	WriteDB() ISecretDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISecretDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISecretDo
	Not(conds ...gen.Condition) ISecretDo
	Or(conds ...gen.Condition) ISecretDo
	Select(conds ...field.Expr) ISecretDo
	Where(conds ...gen.Condition) ISecretDo
	Order(conds ...field.Expr) ISecretDo
	Distinct(cols ...field.Expr) ISecretDo
	Omit(cols ...field.Expr) ISecretDo
	Join(table schema.Tabler, on ...field.Expr) ISecretDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISecretDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISecretDo
	Group(cols ...field.Expr) ISecretDo
	Having(conds ...gen.Condition) ISecretDo
	Limit(limit int) ISecretDo
	Offset(offset int) ISecretDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISecretDo
	Unscoped() ISecretDo
	Create(values ...*model.Secret) error
	CreateInBatches(values []*model.Secret, batchSize int) error
	Save(values ...*model.Secret) error
	First() (*model.Secret, error)
	Take() (*model.Secret, error)
	Last() (*model.Secret, error)
	Find() ([]*model.Secret, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Secret, err error)
	FindInBatches(result *[]*model.Secret, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Secret) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISecretDo
	Assign(attrs ...field.AssignExpr) ISecretDo
	Joins(fields ...field.RelationField) ISecretDo
	Preload(fields ...field.RelationField) ISecretDo
	FirstOrInit() (*model.Secret, error)
	FirstOrCreate() (*model.Secret, error)
	FindByPage(offset int, limit int) (result []*model.Secret, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISecretDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s secretDo) Debug() ISecretDo {
	return s.withDO(s.DO.Debug())
}

func (s secretDo) WithContext(ctx context.Context) ISecretDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s secretDo) ReadDB() ISecretDo {
	return s.Clauses(dbresolver.Read)
}

func (s secretDo) WriteDB() ISecretDo {
	return s.Clauses(dbresolver.Write)
}

func (s secretDo) Session(config *gorm.Session) ISecretDo {
	return s.withDO(s.DO.Session(config))
}

func (s secretDo) Clauses(conds ...clause.Expression) ISecretDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s secretDo) Returning(value interface{}, columns ...string) ISecretDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s secretDo) Not(conds ...gen.Condition) ISecretDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s secretDo) Or(conds ...gen.Condition) ISecretDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s secretDo) Select(conds ...field.Expr) ISecretDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s secretDo) Where(conds ...gen.Condition) ISecretDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s secretDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) ISecretDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s secretDo) Order(conds ...field.Expr) ISecretDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s secretDo) Distinct(cols ...field.Expr) ISecretDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s secretDo) Omit(cols ...field.Expr) ISecretDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s secretDo) Join(table schema.Tabler, on ...field.Expr) ISecretDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s secretDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISecretDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s secretDo) RightJoin(table schema.Tabler, on ...field.Expr) ISecretDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s secretDo) Group(cols ...field.Expr) ISecretDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s secretDo) Having(conds ...gen.Condition) ISecretDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s secretDo) Limit(limit int) ISecretDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s secretDo) Offset(offset int) ISecretDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s secretDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISecretDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s secretDo) Unscoped() ISecretDo {
	return s.withDO(s.DO.Unscoped())
}

func (s secretDo) Create(values ...*model.Secret) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s secretDo) CreateInBatches(values []*model.Secret, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s secretDo) Save(values ...*model.Secret) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s secretDo) First() (*model.Secret, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Secret), nil
	}
}

func (s secretDo) Take() (*model.Secret, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Secret), nil
	}
}

func (s secretDo) Last() (*model.Secret, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Secret), nil
	}
}

func (s secretDo) Find() ([]*model.Secret, error) {
	result, err := s.DO.Find()
	return result.([]*model.Secret), err
}

func (s secretDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Secret, err error) {
	buf := make([]*model.Secret, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s secretDo) FindInBatches(result *[]*model.Secret, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s secretDo) Attrs(attrs ...field.AssignExpr) ISecretDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s secretDo) Assign(attrs ...field.AssignExpr) ISecretDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s secretDo) Joins(fields ...field.RelationField) ISecretDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s secretDo) Preload(fields ...field.RelationField) ISecretDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s secretDo) FirstOrInit() (*model.Secret, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Secret), nil
	}
}

func (s secretDo) FirstOrCreate() (*model.Secret, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Secret), nil
	}
}

func (s secretDo) FindByPage(offset int, limit int) (result []*model.Secret, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s secretDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s secretDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s secretDo) Delete(models ...*model.Secret) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *secretDo) withDO(do gen.Dao) *secretDo {
	s.DO = *do.(*gen.DO)
	return s
}
