// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newSecretTemplate(db *gorm.DB, opts ...gen.DOOption) secretTemplate {
	_secretTemplate := secretTemplate{}

	_secretTemplate.secretTemplateDo.UseDB(db, opts...)
	_secretTemplate.secretTemplateDo.UseModel(&model.SecretTemplate{})

	tableName := _secretTemplate.secretTemplateDo.TableName()
	_secretTemplate.ALL = field.NewAsterisk(tableName)
	_secretTemplate.ID = field.NewInt64(tableName, "id")
	_secretTemplate.Name = field.NewString(tableName, "name")
	_secretTemplate.Template = field.NewString(tableName, "template")
	_secretTemplate.SecretMapID = field.NewInt64(tableName, "secret_map_id")
	_secretTemplate.MetaData = field.NewString(tableName, "meta_data")
	_secretTemplate.Description = field.NewString(tableName, "description")
	_secretTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_secretTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_secretTemplate.User = field.NewString(tableName, "user")
	_secretTemplate.Deleted = field.NewBool(tableName, "deleted")

	_secretTemplate.fillFieldMap()

	return _secretTemplate
}

type secretTemplate struct {
	secretTemplateDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Template    field.String
	SecretMapID field.Int64
	MetaData    field.String
	Description field.String
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (s secretTemplate) Table(newTableName string) *secretTemplate {
	s.secretTemplateDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s secretTemplate) As(alias string) *secretTemplate {
	s.secretTemplateDo.DO = *(s.secretTemplateDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *secretTemplate) updateTableName(table string) *secretTemplate {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Template = field.NewString(table, "template")
	s.SecretMapID = field.NewInt64(table, "secret_map_id")
	s.MetaData = field.NewString(table, "meta_data")
	s.Description = field.NewString(table, "description")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.User = field.NewString(table, "user")
	s.Deleted = field.NewBool(table, "deleted")

	s.fillFieldMap()

	return s
}

func (s *secretTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *secretTemplate) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["template"] = s.Template
	s.fieldMap["secret_map_id"] = s.SecretMapID
	s.fieldMap["meta_data"] = s.MetaData
	s.fieldMap["description"] = s.Description
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["user"] = s.User
	s.fieldMap["deleted"] = s.Deleted
}

func (s secretTemplate) clone(db *gorm.DB) secretTemplate {
	s.secretTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s secretTemplate) replaceDB(db *gorm.DB) secretTemplate {
	s.secretTemplateDo.ReplaceDB(db)
	return s
}

type secretTemplateDo struct{ gen.DO }

type ISecretTemplateDo interface {
	gen.SubQuery
	Debug() ISecretTemplateDo
	WithContext(ctx context.Context) ISecretTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISecretTemplateDo
	WriteDB() ISecretTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISecretTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISecretTemplateDo
	Not(conds ...gen.Condition) ISecretTemplateDo
	Or(conds ...gen.Condition) ISecretTemplateDo
	Select(conds ...field.Expr) ISecretTemplateDo
	Where(conds ...gen.Condition) ISecretTemplateDo
	Order(conds ...field.Expr) ISecretTemplateDo
	Distinct(cols ...field.Expr) ISecretTemplateDo
	Omit(cols ...field.Expr) ISecretTemplateDo
	Join(table schema.Tabler, on ...field.Expr) ISecretTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISecretTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISecretTemplateDo
	Group(cols ...field.Expr) ISecretTemplateDo
	Having(conds ...gen.Condition) ISecretTemplateDo
	Limit(limit int) ISecretTemplateDo
	Offset(offset int) ISecretTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISecretTemplateDo
	Unscoped() ISecretTemplateDo
	Create(values ...*model.SecretTemplate) error
	CreateInBatches(values []*model.SecretTemplate, batchSize int) error
	Save(values ...*model.SecretTemplate) error
	First() (*model.SecretTemplate, error)
	Take() (*model.SecretTemplate, error)
	Last() (*model.SecretTemplate, error)
	Find() ([]*model.SecretTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SecretTemplate, err error)
	FindInBatches(result *[]*model.SecretTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SecretTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISecretTemplateDo
	Assign(attrs ...field.AssignExpr) ISecretTemplateDo
	Joins(fields ...field.RelationField) ISecretTemplateDo
	Preload(fields ...field.RelationField) ISecretTemplateDo
	FirstOrInit() (*model.SecretTemplate, error)
	FirstOrCreate() (*model.SecretTemplate, error)
	FindByPage(offset int, limit int) (result []*model.SecretTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISecretTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s secretTemplateDo) Debug() ISecretTemplateDo {
	return s.withDO(s.DO.Debug())
}

func (s secretTemplateDo) WithContext(ctx context.Context) ISecretTemplateDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s secretTemplateDo) ReadDB() ISecretTemplateDo {
	return s.Clauses(dbresolver.Read)
}

func (s secretTemplateDo) WriteDB() ISecretTemplateDo {
	return s.Clauses(dbresolver.Write)
}

func (s secretTemplateDo) Session(config *gorm.Session) ISecretTemplateDo {
	return s.withDO(s.DO.Session(config))
}

func (s secretTemplateDo) Clauses(conds ...clause.Expression) ISecretTemplateDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s secretTemplateDo) Returning(value interface{}, columns ...string) ISecretTemplateDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s secretTemplateDo) Not(conds ...gen.Condition) ISecretTemplateDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s secretTemplateDo) Or(conds ...gen.Condition) ISecretTemplateDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s secretTemplateDo) Select(conds ...field.Expr) ISecretTemplateDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s secretTemplateDo) Where(conds ...gen.Condition) ISecretTemplateDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s secretTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) ISecretTemplateDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s secretTemplateDo) Order(conds ...field.Expr) ISecretTemplateDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s secretTemplateDo) Distinct(cols ...field.Expr) ISecretTemplateDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s secretTemplateDo) Omit(cols ...field.Expr) ISecretTemplateDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s secretTemplateDo) Join(table schema.Tabler, on ...field.Expr) ISecretTemplateDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s secretTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISecretTemplateDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s secretTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) ISecretTemplateDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s secretTemplateDo) Group(cols ...field.Expr) ISecretTemplateDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s secretTemplateDo) Having(conds ...gen.Condition) ISecretTemplateDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s secretTemplateDo) Limit(limit int) ISecretTemplateDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s secretTemplateDo) Offset(offset int) ISecretTemplateDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s secretTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISecretTemplateDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s secretTemplateDo) Unscoped() ISecretTemplateDo {
	return s.withDO(s.DO.Unscoped())
}

func (s secretTemplateDo) Create(values ...*model.SecretTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s secretTemplateDo) CreateInBatches(values []*model.SecretTemplate, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s secretTemplateDo) Save(values ...*model.SecretTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s secretTemplateDo) First() (*model.SecretTemplate, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SecretTemplate), nil
	}
}

func (s secretTemplateDo) Take() (*model.SecretTemplate, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SecretTemplate), nil
	}
}

func (s secretTemplateDo) Last() (*model.SecretTemplate, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SecretTemplate), nil
	}
}

func (s secretTemplateDo) Find() ([]*model.SecretTemplate, error) {
	result, err := s.DO.Find()
	return result.([]*model.SecretTemplate), err
}

func (s secretTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SecretTemplate, err error) {
	buf := make([]*model.SecretTemplate, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s secretTemplateDo) FindInBatches(result *[]*model.SecretTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s secretTemplateDo) Attrs(attrs ...field.AssignExpr) ISecretTemplateDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s secretTemplateDo) Assign(attrs ...field.AssignExpr) ISecretTemplateDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s secretTemplateDo) Joins(fields ...field.RelationField) ISecretTemplateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s secretTemplateDo) Preload(fields ...field.RelationField) ISecretTemplateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s secretTemplateDo) FirstOrInit() (*model.SecretTemplate, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SecretTemplate), nil
	}
}

func (s secretTemplateDo) FirstOrCreate() (*model.SecretTemplate, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SecretTemplate), nil
	}
}

func (s secretTemplateDo) FindByPage(offset int, limit int) (result []*model.SecretTemplate, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s secretTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s secretTemplateDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s secretTemplateDo) Delete(models ...*model.SecretTemplate) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *secretTemplateDo) withDO(do gen.Dao) *secretTemplateDo {
	s.DO = *do.(*gen.DO)
	return s
}
