// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newServiceTemplate(db *gorm.DB, opts ...gen.DOOption) serviceTemplate {
	_serviceTemplate := serviceTemplate{}

	_serviceTemplate.serviceTemplateDo.UseDB(db, opts...)
	_serviceTemplate.serviceTemplateDo.UseModel(&model.ServiceTemplate{})

	tableName := _serviceTemplate.serviceTemplateDo.TableName()
	_serviceTemplate.ALL = field.NewAsterisk(tableName)
	_serviceTemplate.ID = field.NewInt64(tableName, "id")
	_serviceTemplate.Name = field.NewString(tableName, "name")
	_serviceTemplate.Template = field.NewString(tableName, "template")
	_serviceTemplate.ServiceID = field.NewInt64(tableName, "service_id")
	_serviceTemplate.Description = field.NewString(tableName, "description")
	_serviceTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_serviceTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_serviceTemplate.User = field.NewString(tableName, "user")
	_serviceTemplate.Deleted = field.NewBool(tableName, "deleted")

	_serviceTemplate.fillFieldMap()

	return _serviceTemplate
}

type serviceTemplate struct {
	serviceTemplateDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Template    field.String
	ServiceID   field.Int64
	Description field.String
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (s serviceTemplate) Table(newTableName string) *serviceTemplate {
	s.serviceTemplateDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s serviceTemplate) As(alias string) *serviceTemplate {
	s.serviceTemplateDo.DO = *(s.serviceTemplateDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *serviceTemplate) updateTableName(table string) *serviceTemplate {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Template = field.NewString(table, "template")
	s.ServiceID = field.NewInt64(table, "service_id")
	s.Description = field.NewString(table, "description")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.User = field.NewString(table, "user")
	s.Deleted = field.NewBool(table, "deleted")

	s.fillFieldMap()

	return s
}

func (s *serviceTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *serviceTemplate) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["template"] = s.Template
	s.fieldMap["service_id"] = s.ServiceID
	s.fieldMap["description"] = s.Description
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["user"] = s.User
	s.fieldMap["deleted"] = s.Deleted
}

func (s serviceTemplate) clone(db *gorm.DB) serviceTemplate {
	s.serviceTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s serviceTemplate) replaceDB(db *gorm.DB) serviceTemplate {
	s.serviceTemplateDo.ReplaceDB(db)
	return s
}

type serviceTemplateDo struct{ gen.DO }

type IServiceTemplateDo interface {
	gen.SubQuery
	Debug() IServiceTemplateDo
	WithContext(ctx context.Context) IServiceTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IServiceTemplateDo
	WriteDB() IServiceTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IServiceTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IServiceTemplateDo
	Not(conds ...gen.Condition) IServiceTemplateDo
	Or(conds ...gen.Condition) IServiceTemplateDo
	Select(conds ...field.Expr) IServiceTemplateDo
	Where(conds ...gen.Condition) IServiceTemplateDo
	Order(conds ...field.Expr) IServiceTemplateDo
	Distinct(cols ...field.Expr) IServiceTemplateDo
	Omit(cols ...field.Expr) IServiceTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IServiceTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IServiceTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IServiceTemplateDo
	Group(cols ...field.Expr) IServiceTemplateDo
	Having(conds ...gen.Condition) IServiceTemplateDo
	Limit(limit int) IServiceTemplateDo
	Offset(offset int) IServiceTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceTemplateDo
	Unscoped() IServiceTemplateDo
	Create(values ...*model.ServiceTemplate) error
	CreateInBatches(values []*model.ServiceTemplate, batchSize int) error
	Save(values ...*model.ServiceTemplate) error
	First() (*model.ServiceTemplate, error)
	Take() (*model.ServiceTemplate, error)
	Last() (*model.ServiceTemplate, error)
	Find() ([]*model.ServiceTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceTemplate, err error)
	FindInBatches(result *[]*model.ServiceTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ServiceTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IServiceTemplateDo
	Assign(attrs ...field.AssignExpr) IServiceTemplateDo
	Joins(fields ...field.RelationField) IServiceTemplateDo
	Preload(fields ...field.RelationField) IServiceTemplateDo
	FirstOrInit() (*model.ServiceTemplate, error)
	FirstOrCreate() (*model.ServiceTemplate, error)
	FindByPage(offset int, limit int) (result []*model.ServiceTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IServiceTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s serviceTemplateDo) Debug() IServiceTemplateDo {
	return s.withDO(s.DO.Debug())
}

func (s serviceTemplateDo) WithContext(ctx context.Context) IServiceTemplateDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s serviceTemplateDo) ReadDB() IServiceTemplateDo {
	return s.Clauses(dbresolver.Read)
}

func (s serviceTemplateDo) WriteDB() IServiceTemplateDo {
	return s.Clauses(dbresolver.Write)
}

func (s serviceTemplateDo) Session(config *gorm.Session) IServiceTemplateDo {
	return s.withDO(s.DO.Session(config))
}

func (s serviceTemplateDo) Clauses(conds ...clause.Expression) IServiceTemplateDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s serviceTemplateDo) Returning(value interface{}, columns ...string) IServiceTemplateDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s serviceTemplateDo) Not(conds ...gen.Condition) IServiceTemplateDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s serviceTemplateDo) Or(conds ...gen.Condition) IServiceTemplateDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s serviceTemplateDo) Select(conds ...field.Expr) IServiceTemplateDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s serviceTemplateDo) Where(conds ...gen.Condition) IServiceTemplateDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s serviceTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IServiceTemplateDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s serviceTemplateDo) Order(conds ...field.Expr) IServiceTemplateDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s serviceTemplateDo) Distinct(cols ...field.Expr) IServiceTemplateDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s serviceTemplateDo) Omit(cols ...field.Expr) IServiceTemplateDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s serviceTemplateDo) Join(table schema.Tabler, on ...field.Expr) IServiceTemplateDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s serviceTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IServiceTemplateDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s serviceTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IServiceTemplateDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s serviceTemplateDo) Group(cols ...field.Expr) IServiceTemplateDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s serviceTemplateDo) Having(conds ...gen.Condition) IServiceTemplateDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s serviceTemplateDo) Limit(limit int) IServiceTemplateDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s serviceTemplateDo) Offset(offset int) IServiceTemplateDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s serviceTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceTemplateDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s serviceTemplateDo) Unscoped() IServiceTemplateDo {
	return s.withDO(s.DO.Unscoped())
}

func (s serviceTemplateDo) Create(values ...*model.ServiceTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s serviceTemplateDo) CreateInBatches(values []*model.ServiceTemplate, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s serviceTemplateDo) Save(values ...*model.ServiceTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s serviceTemplateDo) First() (*model.ServiceTemplate, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceTemplate), nil
	}
}

func (s serviceTemplateDo) Take() (*model.ServiceTemplate, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceTemplate), nil
	}
}

func (s serviceTemplateDo) Last() (*model.ServiceTemplate, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceTemplate), nil
	}
}

func (s serviceTemplateDo) Find() ([]*model.ServiceTemplate, error) {
	result, err := s.DO.Find()
	return result.([]*model.ServiceTemplate), err
}

func (s serviceTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ServiceTemplate, err error) {
	buf := make([]*model.ServiceTemplate, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s serviceTemplateDo) FindInBatches(result *[]*model.ServiceTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s serviceTemplateDo) Attrs(attrs ...field.AssignExpr) IServiceTemplateDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s serviceTemplateDo) Assign(attrs ...field.AssignExpr) IServiceTemplateDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s serviceTemplateDo) Joins(fields ...field.RelationField) IServiceTemplateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s serviceTemplateDo) Preload(fields ...field.RelationField) IServiceTemplateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s serviceTemplateDo) FirstOrInit() (*model.ServiceTemplate, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceTemplate), nil
	}
}

func (s serviceTemplateDo) FirstOrCreate() (*model.ServiceTemplate, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ServiceTemplate), nil
	}
}

func (s serviceTemplateDo) FindByPage(offset int, limit int) (result []*model.ServiceTemplate, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s serviceTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s serviceTemplateDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s serviceTemplateDo) Delete(models ...*model.ServiceTemplate) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *serviceTemplateDo) withDO(do gen.Dao) *serviceTemplateDo {
	s.DO = *do.(*gen.DO)
	return s
}
