// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newStatefulsetTemplate(db *gorm.DB, opts ...gen.DOOption) statefulsetTemplate {
	_statefulsetTemplate := statefulsetTemplate{}

	_statefulsetTemplate.statefulsetTemplateDo.UseDB(db, opts...)
	_statefulsetTemplate.statefulsetTemplateDo.UseModel(&model.StatefulsetTemplate{})

	tableName := _statefulsetTemplate.statefulsetTemplateDo.TableName()
	_statefulsetTemplate.ALL = field.NewAsterisk(tableName)
	_statefulsetTemplate.ID = field.NewInt64(tableName, "id")
	_statefulsetTemplate.Name = field.NewString(tableName, "name")
	_statefulsetTemplate.Template = field.NewString(tableName, "template")
	_statefulsetTemplate.StatefulsetID = field.NewInt64(tableName, "statefulset_id")
	_statefulsetTemplate.Description = field.NewString(tableName, "description")
	_statefulsetTemplate.CreateTime = field.NewTime(tableName, "create_time")
	_statefulsetTemplate.UpdateTime = field.NewTime(tableName, "update_time")
	_statefulsetTemplate.User = field.NewString(tableName, "user")
	_statefulsetTemplate.Deleted = field.NewBool(tableName, "deleted")

	_statefulsetTemplate.fillFieldMap()

	return _statefulsetTemplate
}

type statefulsetTemplate struct {
	statefulsetTemplateDo

	ALL           field.Asterisk
	ID            field.Int64
	Name          field.String
	Template      field.String
	StatefulsetID field.Int64
	Description   field.String
	CreateTime    field.Time
	UpdateTime    field.Time
	User          field.String
	Deleted       field.Bool

	fieldMap map[string]field.Expr
}

func (s statefulsetTemplate) Table(newTableName string) *statefulsetTemplate {
	s.statefulsetTemplateDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s statefulsetTemplate) As(alias string) *statefulsetTemplate {
	s.statefulsetTemplateDo.DO = *(s.statefulsetTemplateDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *statefulsetTemplate) updateTableName(table string) *statefulsetTemplate {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Template = field.NewString(table, "template")
	s.StatefulsetID = field.NewInt64(table, "statefulset_id")
	s.Description = field.NewString(table, "description")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.User = field.NewString(table, "user")
	s.Deleted = field.NewBool(table, "deleted")

	s.fillFieldMap()

	return s
}

func (s *statefulsetTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *statefulsetTemplate) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["template"] = s.Template
	s.fieldMap["statefulset_id"] = s.StatefulsetID
	s.fieldMap["description"] = s.Description
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["user"] = s.User
	s.fieldMap["deleted"] = s.Deleted
}

func (s statefulsetTemplate) clone(db *gorm.DB) statefulsetTemplate {
	s.statefulsetTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s statefulsetTemplate) replaceDB(db *gorm.DB) statefulsetTemplate {
	s.statefulsetTemplateDo.ReplaceDB(db)
	return s
}

type statefulsetTemplateDo struct{ gen.DO }

type IStatefulsetTemplateDo interface {
	gen.SubQuery
	Debug() IStatefulsetTemplateDo
	WithContext(ctx context.Context) IStatefulsetTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStatefulsetTemplateDo
	WriteDB() IStatefulsetTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStatefulsetTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStatefulsetTemplateDo
	Not(conds ...gen.Condition) IStatefulsetTemplateDo
	Or(conds ...gen.Condition) IStatefulsetTemplateDo
	Select(conds ...field.Expr) IStatefulsetTemplateDo
	Where(conds ...gen.Condition) IStatefulsetTemplateDo
	Order(conds ...field.Expr) IStatefulsetTemplateDo
	Distinct(cols ...field.Expr) IStatefulsetTemplateDo
	Omit(cols ...field.Expr) IStatefulsetTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IStatefulsetTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStatefulsetTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStatefulsetTemplateDo
	Group(cols ...field.Expr) IStatefulsetTemplateDo
	Having(conds ...gen.Condition) IStatefulsetTemplateDo
	Limit(limit int) IStatefulsetTemplateDo
	Offset(offset int) IStatefulsetTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStatefulsetTemplateDo
	Unscoped() IStatefulsetTemplateDo
	Create(values ...*model.StatefulsetTemplate) error
	CreateInBatches(values []*model.StatefulsetTemplate, batchSize int) error
	Save(values ...*model.StatefulsetTemplate) error
	First() (*model.StatefulsetTemplate, error)
	Take() (*model.StatefulsetTemplate, error)
	Last() (*model.StatefulsetTemplate, error)
	Find() ([]*model.StatefulsetTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StatefulsetTemplate, err error)
	FindInBatches(result *[]*model.StatefulsetTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StatefulsetTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStatefulsetTemplateDo
	Assign(attrs ...field.AssignExpr) IStatefulsetTemplateDo
	Joins(fields ...field.RelationField) IStatefulsetTemplateDo
	Preload(fields ...field.RelationField) IStatefulsetTemplateDo
	FirstOrInit() (*model.StatefulsetTemplate, error)
	FirstOrCreate() (*model.StatefulsetTemplate, error)
	FindByPage(offset int, limit int) (result []*model.StatefulsetTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStatefulsetTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s statefulsetTemplateDo) Debug() IStatefulsetTemplateDo {
	return s.withDO(s.DO.Debug())
}

func (s statefulsetTemplateDo) WithContext(ctx context.Context) IStatefulsetTemplateDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s statefulsetTemplateDo) ReadDB() IStatefulsetTemplateDo {
	return s.Clauses(dbresolver.Read)
}

func (s statefulsetTemplateDo) WriteDB() IStatefulsetTemplateDo {
	return s.Clauses(dbresolver.Write)
}

func (s statefulsetTemplateDo) Session(config *gorm.Session) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Session(config))
}

func (s statefulsetTemplateDo) Clauses(conds ...clause.Expression) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s statefulsetTemplateDo) Returning(value interface{}, columns ...string) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s statefulsetTemplateDo) Not(conds ...gen.Condition) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s statefulsetTemplateDo) Or(conds ...gen.Condition) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s statefulsetTemplateDo) Select(conds ...field.Expr) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s statefulsetTemplateDo) Where(conds ...gen.Condition) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s statefulsetTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IStatefulsetTemplateDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s statefulsetTemplateDo) Order(conds ...field.Expr) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s statefulsetTemplateDo) Distinct(cols ...field.Expr) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s statefulsetTemplateDo) Omit(cols ...field.Expr) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s statefulsetTemplateDo) Join(table schema.Tabler, on ...field.Expr) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s statefulsetTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStatefulsetTemplateDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s statefulsetTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IStatefulsetTemplateDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s statefulsetTemplateDo) Group(cols ...field.Expr) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s statefulsetTemplateDo) Having(conds ...gen.Condition) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s statefulsetTemplateDo) Limit(limit int) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s statefulsetTemplateDo) Offset(offset int) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s statefulsetTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s statefulsetTemplateDo) Unscoped() IStatefulsetTemplateDo {
	return s.withDO(s.DO.Unscoped())
}

func (s statefulsetTemplateDo) Create(values ...*model.StatefulsetTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s statefulsetTemplateDo) CreateInBatches(values []*model.StatefulsetTemplate, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s statefulsetTemplateDo) Save(values ...*model.StatefulsetTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s statefulsetTemplateDo) First() (*model.StatefulsetTemplate, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StatefulsetTemplate), nil
	}
}

func (s statefulsetTemplateDo) Take() (*model.StatefulsetTemplate, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StatefulsetTemplate), nil
	}
}

func (s statefulsetTemplateDo) Last() (*model.StatefulsetTemplate, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StatefulsetTemplate), nil
	}
}

func (s statefulsetTemplateDo) Find() ([]*model.StatefulsetTemplate, error) {
	result, err := s.DO.Find()
	return result.([]*model.StatefulsetTemplate), err
}

func (s statefulsetTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StatefulsetTemplate, err error) {
	buf := make([]*model.StatefulsetTemplate, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s statefulsetTemplateDo) FindInBatches(result *[]*model.StatefulsetTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s statefulsetTemplateDo) Attrs(attrs ...field.AssignExpr) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s statefulsetTemplateDo) Assign(attrs ...field.AssignExpr) IStatefulsetTemplateDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s statefulsetTemplateDo) Joins(fields ...field.RelationField) IStatefulsetTemplateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s statefulsetTemplateDo) Preload(fields ...field.RelationField) IStatefulsetTemplateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s statefulsetTemplateDo) FirstOrInit() (*model.StatefulsetTemplate, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StatefulsetTemplate), nil
	}
}

func (s statefulsetTemplateDo) FirstOrCreate() (*model.StatefulsetTemplate, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StatefulsetTemplate), nil
	}
}

func (s statefulsetTemplateDo) FindByPage(offset int, limit int) (result []*model.StatefulsetTemplate, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s statefulsetTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s statefulsetTemplateDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s statefulsetTemplateDo) Delete(models ...*model.StatefulsetTemplate) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *statefulsetTemplateDo) withDO(do gen.Dao) *statefulsetTemplateDo {
	s.DO = *do.(*gen.DO)
	return s
}
