// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wayne/clear/dal/model"
)

func newStatefulset(db *gorm.DB, opts ...gen.DOOption) statefulset {
	_statefulset := statefulset{}

	_statefulset.statefulsetDo.UseDB(db, opts...)
	_statefulset.statefulsetDo.UseModel(&model.Statefulset{})

	tableName := _statefulset.statefulsetDo.TableName()
	_statefulset.ALL = field.NewAsterisk(tableName)
	_statefulset.ID = field.NewInt64(tableName, "id")
	_statefulset.Name = field.NewString(tableName, "name")
	_statefulset.MetaData = field.NewString(tableName, "meta_data")
	_statefulset.AppID = field.NewInt64(tableName, "app_id")
	_statefulset.Description = field.NewString(tableName, "description")
	_statefulset.OrderID = field.NewInt64(tableName, "order_id")
	_statefulset.CreateTime = field.NewTime(tableName, "create_time")
	_statefulset.UpdateTime = field.NewTime(tableName, "update_time")
	_statefulset.User = field.NewString(tableName, "user")
	_statefulset.Deleted = field.NewBool(tableName, "deleted")

	_statefulset.fillFieldMap()

	return _statefulset
}

type statefulset struct {
	statefulsetDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	MetaData    field.String
	AppID       field.Int64
	Description field.String
	OrderID     field.Int64
	CreateTime  field.Time
	UpdateTime  field.Time
	User        field.String
	Deleted     field.Bool

	fieldMap map[string]field.Expr
}

func (s statefulset) Table(newTableName string) *statefulset {
	s.statefulsetDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s statefulset) As(alias string) *statefulset {
	s.statefulsetDo.DO = *(s.statefulsetDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *statefulset) updateTableName(table string) *statefulset {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.MetaData = field.NewString(table, "meta_data")
	s.AppID = field.NewInt64(table, "app_id")
	s.Description = field.NewString(table, "description")
	s.OrderID = field.NewInt64(table, "order_id")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.User = field.NewString(table, "user")
	s.Deleted = field.NewBool(table, "deleted")

	s.fillFieldMap()

	return s
}

func (s *statefulset) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *statefulset) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["meta_data"] = s.MetaData
	s.fieldMap["app_id"] = s.AppID
	s.fieldMap["description"] = s.Description
	s.fieldMap["order_id"] = s.OrderID
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["user"] = s.User
	s.fieldMap["deleted"] = s.Deleted
}

func (s statefulset) clone(db *gorm.DB) statefulset {
	s.statefulsetDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s statefulset) replaceDB(db *gorm.DB) statefulset {
	s.statefulsetDo.ReplaceDB(db)
	return s
}

type statefulsetDo struct{ gen.DO }

type IStatefulsetDo interface {
	gen.SubQuery
	Debug() IStatefulsetDo
	WithContext(ctx context.Context) IStatefulsetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStatefulsetDo
	WriteDB() IStatefulsetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStatefulsetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStatefulsetDo
	Not(conds ...gen.Condition) IStatefulsetDo
	Or(conds ...gen.Condition) IStatefulsetDo
	Select(conds ...field.Expr) IStatefulsetDo
	Where(conds ...gen.Condition) IStatefulsetDo
	Order(conds ...field.Expr) IStatefulsetDo
	Distinct(cols ...field.Expr) IStatefulsetDo
	Omit(cols ...field.Expr) IStatefulsetDo
	Join(table schema.Tabler, on ...field.Expr) IStatefulsetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStatefulsetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStatefulsetDo
	Group(cols ...field.Expr) IStatefulsetDo
	Having(conds ...gen.Condition) IStatefulsetDo
	Limit(limit int) IStatefulsetDo
	Offset(offset int) IStatefulsetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStatefulsetDo
	Unscoped() IStatefulsetDo
	Create(values ...*model.Statefulset) error
	CreateInBatches(values []*model.Statefulset, batchSize int) error
	Save(values ...*model.Statefulset) error
	First() (*model.Statefulset, error)
	Take() (*model.Statefulset, error)
	Last() (*model.Statefulset, error)
	Find() ([]*model.Statefulset, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Statefulset, err error)
	FindInBatches(result *[]*model.Statefulset, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Statefulset) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStatefulsetDo
	Assign(attrs ...field.AssignExpr) IStatefulsetDo
	Joins(fields ...field.RelationField) IStatefulsetDo
	Preload(fields ...field.RelationField) IStatefulsetDo
	FirstOrInit() (*model.Statefulset, error)
	FirstOrCreate() (*model.Statefulset, error)
	FindByPage(offset int, limit int) (result []*model.Statefulset, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStatefulsetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s statefulsetDo) Debug() IStatefulsetDo {
	return s.withDO(s.DO.Debug())
}

func (s statefulsetDo) WithContext(ctx context.Context) IStatefulsetDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s statefulsetDo) ReadDB() IStatefulsetDo {
	return s.Clauses(dbresolver.Read)
}

func (s statefulsetDo) WriteDB() IStatefulsetDo {
	return s.Clauses(dbresolver.Write)
}

func (s statefulsetDo) Session(config *gorm.Session) IStatefulsetDo {
	return s.withDO(s.DO.Session(config))
}

func (s statefulsetDo) Clauses(conds ...clause.Expression) IStatefulsetDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s statefulsetDo) Returning(value interface{}, columns ...string) IStatefulsetDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s statefulsetDo) Not(conds ...gen.Condition) IStatefulsetDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s statefulsetDo) Or(conds ...gen.Condition) IStatefulsetDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s statefulsetDo) Select(conds ...field.Expr) IStatefulsetDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s statefulsetDo) Where(conds ...gen.Condition) IStatefulsetDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s statefulsetDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IStatefulsetDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s statefulsetDo) Order(conds ...field.Expr) IStatefulsetDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s statefulsetDo) Distinct(cols ...field.Expr) IStatefulsetDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s statefulsetDo) Omit(cols ...field.Expr) IStatefulsetDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s statefulsetDo) Join(table schema.Tabler, on ...field.Expr) IStatefulsetDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s statefulsetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStatefulsetDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s statefulsetDo) RightJoin(table schema.Tabler, on ...field.Expr) IStatefulsetDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s statefulsetDo) Group(cols ...field.Expr) IStatefulsetDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s statefulsetDo) Having(conds ...gen.Condition) IStatefulsetDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s statefulsetDo) Limit(limit int) IStatefulsetDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s statefulsetDo) Offset(offset int) IStatefulsetDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s statefulsetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStatefulsetDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s statefulsetDo) Unscoped() IStatefulsetDo {
	return s.withDO(s.DO.Unscoped())
}

func (s statefulsetDo) Create(values ...*model.Statefulset) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s statefulsetDo) CreateInBatches(values []*model.Statefulset, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s statefulsetDo) Save(values ...*model.Statefulset) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s statefulsetDo) First() (*model.Statefulset, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Statefulset), nil
	}
}

func (s statefulsetDo) Take() (*model.Statefulset, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Statefulset), nil
	}
}

func (s statefulsetDo) Last() (*model.Statefulset, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Statefulset), nil
	}
}

func (s statefulsetDo) Find() ([]*model.Statefulset, error) {
	result, err := s.DO.Find()
	return result.([]*model.Statefulset), err
}

func (s statefulsetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Statefulset, err error) {
	buf := make([]*model.Statefulset, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s statefulsetDo) FindInBatches(result *[]*model.Statefulset, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s statefulsetDo) Attrs(attrs ...field.AssignExpr) IStatefulsetDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s statefulsetDo) Assign(attrs ...field.AssignExpr) IStatefulsetDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s statefulsetDo) Joins(fields ...field.RelationField) IStatefulsetDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s statefulsetDo) Preload(fields ...field.RelationField) IStatefulsetDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s statefulsetDo) FirstOrInit() (*model.Statefulset, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Statefulset), nil
	}
}

func (s statefulsetDo) FirstOrCreate() (*model.Statefulset, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Statefulset), nil
	}
}

func (s statefulsetDo) FindByPage(offset int, limit int) (result []*model.Statefulset, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s statefulsetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s statefulsetDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s statefulsetDo) Delete(models ...*model.Statefulset) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *statefulsetDo) withDO(do gen.Dao) *statefulsetDo {
	s.DO = *do.(*gen.DO)
	return s
}
