// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAPIKey = "api_key"

// APIKey mapped from table <api_key>
type APIKey struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:varchar(128);not null" json:"name"`
	Token       string    `gorm:"column:token;type:longtext;not null" json:"token"`
	Type        int32     `gorm:"column:type;type:int;not null" json:"type"`
	ResourceID  *int64    `gorm:"column:resource_id;type:bigint" json:"resource_id"`
	GroupID     *int64    `gorm:"column:group_id;type:bigint" json:"group_id"`
	Description *string   `gorm:"column:description;type:varchar(512)" json:"description"`
	User        string    `gorm:"column:user;type:varchar(128);not null" json:"user"`
	ExpireIn    int64     `gorm:"column:expire_in;type:bigint;not null" json:"expire_in"`
	Deleted     bool      `gorm:"column:deleted;type:tinyint(1);not null" json:"deleted"`
	CreateTime  time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`
}

// TableName APIKey's table name
func (*APIKey) TableName() string {
	return TableNameAPIKey
}
