// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApp = "app"

// App mapped from table <app>
type App struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:varchar(128);not null" json:"name"`
	NamespaceID int64     `gorm:"column:namespace_id;type:bigint;not null" json:"namespace_id"`
	MetaData    string    `gorm:"column:meta_data;type:longtext;not null" json:"meta_data"`
	Description *string   `gorm:"column:description;type:varchar(512)" json:"description"`
	CreateTime  time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`
	User        string    `gorm:"column:user;type:varchar(128);not null" json:"user"`
	Deleted     bool      `gorm:"column:deleted;type:tinyint(1);not null" json:"deleted"`
	Migrated    bool      `gorm:"column:migrated;type:tinyint(1) unsigned zerofill;not null" json:"migrated"`
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
