// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppUser = "app_user"

// AppUser mapped from table <app_user>
type AppUser struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	AppID      int64     `gorm:"column:app_id;type:bigint;not null" json:"app_id"`
	UserID     int64     `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	GroupID    int64     `gorm:"column:group_id;type:bigint;not null" json:"group_id"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`
}

// TableName AppUser's table name
func (*AppUser) TableName() string {
	return TableNameAppUser
}
