// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAppStarred = "app_starred"

// AppStarred mapped from table <app_starred>
type AppStarred struct {
	ID     int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	AppID  int64 `gorm:"column:app_id;type:bigint;not null" json:"app_id"`
	UserID int64 `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
}

// TableName AppStarred's table name
func (*AppStarred) TableName() string {
	return TableNameAppStarred
}
