// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuditLog = "audit_log"

// AuditLog mapped from table <audit_log>
type AuditLog struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SubjectID  int64      `gorm:"column:subject_id;type:bigint;not null" json:"subject_id"`
	LogType    string     `gorm:"column:log_type;type:varchar(128);not null" json:"log_type"`
	LogLevel   string     `gorm:"column:log_level;type:varchar(128);not null" json:"log_level"`
	Action     string     `gorm:"column:action;type:varchar(255);not null" json:"action"`
	Message    *string    `gorm:"column:message;type:longtext" json:"message"`
	UserIP     string     `gorm:"column:user_ip;type:varchar(200);not null" json:"user_ip"`
	User       string     `gorm:"column:user;type:varchar(128);not null" json:"user"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
}

// TableName AuditLog's table name
func (*AuditLog) TableName() string {
	return TableNameAuditLog
}
