// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCluster = "cluster"

// Cluster mapped from table <cluster>
type Cluster struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:varchar(128);not null" json:"name"`
	MetaData    *string   `gorm:"column:meta_data;type:longtext" json:"meta_data"`
	Master      string    `gorm:"column:master;type:varchar(128);not null" json:"master"`
	KubeConfig  *string   `gorm:"column:kube_config;type:longtext" json:"kube_config"`
	Description *string   `gorm:"column:description;type:varchar(512)" json:"description"`
	CreateTime  time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`
	User        string    `gorm:"column:user;type:varchar(128);not null" json:"user"`
	Deleted     bool      `gorm:"column:deleted;type:tinyint(1);not null" json:"deleted"`
	Status      int32     `gorm:"column:status;type:int;not null" json:"status"`
	Displayname *string   `gorm:"column:displayname;type:varchar(512)" json:"displayname"`
}

// TableName Cluster's table name
func (*Cluster) TableName() string {
	return TableNameCluster
}
