// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameConfig = "config"

// Config mapped from table <config>
type Config struct {
	ID    int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name  string `gorm:"column:name;type:varchar(256);not null" json:"name"`
	Value string `gorm:"column:value;type:longtext;not null" json:"value"`
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
