// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConfigMapTemplate = "config_map_template"

// ConfigMapTemplate mapped from table <config_map_template>
type ConfigMapTemplate struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:varchar(128);not null" json:"name"`
	Template    string    `gorm:"column:template;type:longtext;not null" json:"template"`
	ConfigMapID int64     `gorm:"column:config_map_id;type:bigint;not null" json:"config_map_id"`
	MetaData    string    `gorm:"column:meta_data;type:longtext;not null" json:"meta_data"`
	Description string    `gorm:"column:description;type:varchar(512);not null" json:"description"`
	CreateTime  time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`
	User        string    `gorm:"column:user;type:varchar(128);not null" json:"user"`
	Deleted     bool      `gorm:"column:deleted;type:tinyint(1);not null" json:"deleted"`
}

// TableName ConfigMapTemplate's table name
func (*ConfigMapTemplate) TableName() string {
	return TableNameConfigMapTemplate
}
