// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDaemonSetTemplate = "daemon_set_template"

// DaemonSetTemplate mapped from table <daemon_set_template>
type DaemonSetTemplate struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:varchar(128);not null" json:"name"`
	Template    string    `gorm:"column:template;type:longtext;not null" json:"template"`
	DaemonSetID int64     `gorm:"column:daemon_set_id;type:bigint;not null" json:"daemon_set_id"`
	Description string    `gorm:"column:description;type:varchar(512);not null" json:"description"`
	CreateTime  time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`
	User        string    `gorm:"column:user;type:varchar(128);not null" json:"user"`
	Deleted     bool      `gorm:"column:deleted;type:tinyint(1);not null" json:"deleted"`
}

// TableName DaemonSetTemplate's table name
func (*DaemonSetTemplate) TableName() string {
	return TableNameDaemonSetTemplate
}
