// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeployment = "deployment"

// Deployment mapped from table <deployment>
type Deployment struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:varchar(128);not null" json:"name"`
	MetaData    string    `gorm:"column:meta_data;type:longtext;not null" json:"meta_data"`
	AppID       int64     `gorm:"column:app_id;type:bigint;not null" json:"app_id"`
	Description *string   `gorm:"column:description;type:varchar(512)" json:"description"`
	OrderID     int64     `gorm:"column:order_id;type:bigint;not null" json:"order_id"`
	CreateTime  time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`
	User        string    `gorm:"column:user;type:varchar(128);not null" json:"user"`
	Deleted     bool      `gorm:"column:deleted;type:tinyint(1);not null" json:"deleted"`
}

// TableName Deployment's table name
func (*Deployment) TableName() string {
	return TableNameDeployment
}
