// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroupPermission = "group_permissions"

// GroupPermission mapped from table <group_permissions>
type GroupPermission struct {
	ID           int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	GroupID      int64 `gorm:"column:group_id;type:bigint;not null" json:"group_id"`
	PermissionID int64 `gorm:"column:permission_id;type:bigint;not null" json:"permission_id"`
}

// TableName GroupPermission's table name
func (*GroupPermission) TableName() string {
	return TableNameGroupPermission
}
