// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNamespaceUser = "namespace_user"

// NamespaceUser mapped from table <namespace_user>
type NamespaceUser struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	NamespaceID int64     `gorm:"column:namespace_id;type:bigint;not null" json:"namespace_id"`
	UserID      int64     `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	GroupID     int64     `gorm:"column:group_id;type:bigint;not null" json:"group_id"`
	CreateTime  time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`
}

// TableName NamespaceUser's table name
func (*NamespaceUser) TableName() string {
	return TableNameNamespaceUser
}
