// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePermission = "permission"

// Permission mapped from table <permission>
type Permission struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;type:varchar(200);not null" json:"name"`
	Comment    string    `gorm:"column:comment;type:longtext;not null" json:"comment"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
