// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePublishStatus = "publish_status"

// PublishStatus mapped from table <publish_status>
type PublishStatus struct {
	ID         int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Type       int32  `gorm:"column:type;type:int;not null" json:"type"`
	ResourceID int64  `gorm:"column:resource_id;type:bigint;not null" json:"resource_id"`
	TemplateID int64  `gorm:"column:template_id;type:bigint;not null" json:"template_id"`
	Cluster    string `gorm:"column:cluster;type:varchar(128);not null" json:"cluster"`
}

// TableName PublishStatus's table name
func (*PublishStatus) TableName() string {
	return TableNamePublishStatus
}
