// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePublishHistory = "publish_history"

// PublishHistory mapped from table <publish_history>
type PublishHistory struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Type         int32     `gorm:"column:type;type:int;not null" json:"type"`
	ResourceID   int64     `gorm:"column:resource_id;type:bigint;not null" json:"resource_id"`
	ResourceName string    `gorm:"column:resource_name;type:varchar(128);not null" json:"resource_name"`
	TemplateID   int64     `gorm:"column:template_id;type:bigint;not null" json:"template_id"`
	Cluster      string    `gorm:"column:cluster;type:varchar(128);not null" json:"cluster"`
	Status       int32     `gorm:"column:status;type:int;not null" json:"status"`
	Message      string    `gorm:"column:message;type:longtext;not null" json:"message"`
	User         string    `gorm:"column:user;type:varchar(128);not null" json:"user"`
	CreateTime   time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
}

// TableName PublishHistory's table name
func (*PublishHistory) TableName() string {
	return TableNamePublishHistory
}
