// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;type:varchar(200);not null" json:"name"`
	Password   string    `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Salt       string    `gorm:"column:salt;type:varchar(32);not null" json:"salt"`
	Email      string    `gorm:"column:email;type:varchar(200);not null" json:"email"`
	Display    string    `gorm:"column:display;type:varchar(200);not null" json:"display"`
	Comment    string    `gorm:"column:comment;type:longtext;not null" json:"comment"`
	Type       int32     `gorm:"column:type;type:int;not null" json:"type"`
	Admin      bool      `gorm:"column:admin;type:tinyint(1);not null" json:"admin"`
	LastLogin  time.Time `gorm:"column:last_login;type:datetime;not null" json:"last_login"`
	LastIP     string    `gorm:"column:last_ip;type:varchar(200);not null" json:"last_ip"`
	Deleted    bool      `gorm:"column:deleted;type:tinyint(1);not null" json:"deleted"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
