appname = wayne
httpport = 8080

# prod dev
runmode = dev
autorender = true
copyrequestbody = true
EnableDocs = true
EnableAdmin = false
StaticDir = public:static
EnableDBLogin = true

# token, generate jwt token
# web shell auth
appKey = "260a3247a91aad9b2d68d64257979124hd"
RsaPrivateKey = "./conf/rsa-private.pem"
RsaPublicKey = "./conf/rsa-public.pem"
# api-keys
EnableApiKeys = true 
# token end time. second
TokenLifeTime=86400

# kubernetes labels config
AppLabelKey= wayne-app
NamespaceLabelKey = wayne-ns
 

# database configuration:
ShowSql = true
DBName = "wayne-db"
DBTns = "tcp(10.0.1.7:7001)"
DBUser = "root"
DBPasswd = "@Pwd1234567"
DBLoc = "Asia%2FShanghai"
DBConnTTL = 30


# Set demo namespace and group id
DemoGroupId = "1"
DemoNamespaceId = "1" 
 


# 日志配置
[log]
# 日志级别(1:fatal 2:error,3:warn,4:info,5:debug)
log_level = 4
# 日志格式（支持输出格式：text/json）
format = "text"
# 日志输出(支持：stdout/stderr/file/multi)
output = "stdout"
time_format = "time"


# oauth2
[auth.oauth2]
redirect_url = "http://localhost:8080"
enabled = true
client_id = 10024
client_secret = secret
scopes = openid,email,profile,phone
auth_url = https://auth.yourdomain.com/connect/authorize
token_url = https://auth.yourdomain.com/connect/token
api_url = https://auth.yourdomain.com/connect/userinfo
# If your OAuth 2.0-based authorization service does not have email, name, and dispaly fields, use mapping criteria.
api_mapping = name:name,email:email,display:display